<?php
/**
 * Plugin Name: GK Final Frontend Guard
 * Description: Bereinigt dynamische Altlinks, Rechtsseiten-Blöcke, Autorenanzeige und Theme-Reste nach dem Rendern.
 * Version: 1.0.9
 * Author: IT Solutions – Kolja Seebauer
 * Requires at least: 6.4
 * Requires PHP: 8.0
 */
if (!defined('ABSPATH')) { exit; }

final class GK_Final_Frontend_Guard {
    private static bool $is_legal = false;
    private static bool $is_front = false;
    private static string $slug = '';
    private const AUTHOR_NAME = 'Kolja Seebauer';
    private const AUTHOR_URL  = 'https://glasfaser-kompass.de/ueber-den-autor/';
    private const HOME_TITLE  = 'Glasfaser, DSL, Router und WLAN aus der Praxis';

    public static function boot(): void {
        add_action('template_redirect', [self::class, 'start_buffer'], PHP_INT_MIN);
        add_filter('the_author', [self::class, 'author_name'], PHP_INT_MAX);
        add_filter('get_the_author_display_name', [self::class, 'author_name'], PHP_INT_MAX);
        add_filter('author_link', [self::class, 'author_link'], PHP_INT_MAX);
        add_filter('astra_footer_copyright', [self::class, 'footer'], PHP_INT_MAX);
        add_filter('rank_math/opengraph/facebook/image', [self::class, 'social_image'], PHP_INT_MAX);
        add_filter('rank_math/opengraph/twitter/image', [self::class, 'social_image'], PHP_INT_MAX);
        add_filter('rank_math/opengraph/twitter/card_type', static fn() => 'summary_large_image', PHP_INT_MAX);
        add_action('wp_head', [self::class, 'legal_visibility_guard'], PHP_INT_MAX);
        add_action('wp', [self::class, 'install_content_repairs'], PHP_INT_MAX);
    }

    public static function install_content_repairs(): void {
        if (is_admin() || wp_doing_ajax() || wp_is_json_request() || !is_singular()) { return; }
        /* Registered on wp, after normal plugin bootstrap. This makes the repair
           filter run after GK Render Guard even when both use PHP_INT_MAX. */
        add_filter('the_content', [self::class, 'repair_content'], PHP_INT_MAX);
    }

    private static function photo(string $file, string $alt, string $caption): string {
        $url = home_url('/wp-content/plugins/gk-render-guard/assets/' . $file);
        return '<figure class="gk-topic-photo"><img src="' . esc_url($url) . '" alt="' . esc_attr($alt) . '" loading="lazy"><figcaption>' . esc_html($caption) . '</figcaption></figure>';
    }

    private static function sources(): string {
        return '<h2>Offizielle Quellen</h2><ul><li><a href="https://www.bundesnetzagentur.de/DE/Vportal/TK/InternetTelefon/Internetgeschwindigkeit/start.html">Bundesnetzagentur: Internetzugang und Geschwindigkeit</a></li><li><a href="https://www.telekom.de/hilfe/internet-telefonie/internet">Deutsche Telekom: Hilfe zu Internet und Anschluss</a></li></ul>';
    }

    public static function repair_content(string $content): string {
        if (!is_singular() || !in_the_loop() || !is_main_query()) { return $content; }
        $slug = (string) get_post_field('post_name', get_queried_object_id());
        $articles = self::repair_articles();
        return isset($articles[$slug]) ? $articles[$slug] : $content;
    }

    private static function repair_articles(): array {
        $sources = self::sources();
        return [
            'dsl-bauteile-im-haus' => '<article class="gk-clean-article"><h2>DSL-Bauteile im Haus eindeutig erkennen</h2>'
                . self::photo('apl.png', 'Geöffneter Kupfer-APL mit Mehraderkabel und Anschlussklemmen.', 'APL: passiver Abschluss des Betreiber-Kupfernetzes am Gebäude.')
                . self::photo('tae-dose.jpg', 'Weiße TAE-NFF-Anschlussdose mit drei Buchsen.', 'Erste TAE: Anschluss- und Messpunkt in den Kundenräumen. Foto: Uwe Schwöbel, GNU FDL 1.2, via Wikimedia Commons.')
                . '<h2>Der korrekte Signalweg</h2><p><strong>MFG mit DSLAM/MSAN → KVz → Kupfer-Zugangsnetz → APL → Endleitung → erste TAE → DSL-Router</strong></p><h3>APL</h3><p>Der APL beendet das öffentliche Kupfer-Zugangsnetz am Gebäude. Mehraderkabel, Doppeladern und Anschlussklemmen unterscheiden ihn von einem Glasfaser-Gf-AP und einem Koax-HÜP.</p><h3>Endleitung</h3><p>Die Endleitung ist das Kupfer-Adernpaar zwischen APL und erster TAE. Abzweigungen, lose Klemmstellen und parallel geschaltete Dosen können DSL-Werte verschlechtern.</p><h3>Erste TAE und Router</h3><p>Die erste TAE ist der reguläre Anschluss- und Messpunkt. Das DSL-Modem im Router synchronisiert sich mit dem DSLAM/MSAN. Erst danach werden LAN und WLAN getrennt beurteilt.</p><h2>Vor einem Technikertermin</h2><ul><li>APL und erste TAE zugänglich machen.</li><li>Router, Netzteil und DSL-Kabel bereithalten.</li><li>Weitere Dosen und Abzweigungen nennen.</li><li>APL nicht selbst öffnen oder umklemmen.</li></ul>' . $sources . '</article>',
            'dslam-erklaert' => '<article class="gk-clean-article">' . self::photo('mfg.png', 'Graues Multifunktionsgehäuse am Straßenrand.', 'Bei FTTC/VDSL befindet sich die aktive DSLAM-/MSAN-Technik typischerweise im grauen MFG.') . '<h2>Was macht ein DSLAM oder MSAN?</h2><p>Der DSLAM stellt DSL-Verbindungen für viele Teilnehmer bereit. Bei FTTC/VDSL sitzt diese aktive Technik typischerweise <strong>im Multifunktionsgehäuse</strong>. Das MFG ist das Gehäuse und keine zusätzliche Signalstufe.</p><h2>Der korrekte FTTC-/VDSL-Signalweg</h2><p><strong>Glasfaserzuführung → MFG mit DSLAM/MSAN → KVz → Kupfer-Zugangsnetz → APL → Endleitung → erste TAE → DSL-Router</strong></p><p>Der KVz ist ein eigener passiver Kabelverzweiger. MFG und KVz sind üblicherweise graue Straßengehäuse.</p><h2>Abgrenzung zu FTTH</h2><p>Bei FTTH gibt es auf der Teilnehmerstrecke keinen DSLAM. Dort sind OLT, passives Glasfasernetz, Gf-AP, Gf-TA und gegebenenfalls ONT relevant.</p>' . $sources . '</article>',
            'dsl-stoerungen-verstehen' => '<article class="gk-clean-article">' . self::photo('apl.png', 'Geöffneter Kupfer-APL mit Mehraderkabel und Anschlussklemmen.', 'Bei DSL führt die Gebäudediagnose vom Kupfer-APL über Endleitung und erste TAE zum Router.') . '<h2>DSL-Störungen systematisch eingrenzen</h2><ol><li><strong>Synchronisation prüfen:</strong> Ohne DSL-Synchronisation liegt der Fehler vor der Internet-Einwahl.</li><li><strong>Routerwerte sichern:</strong> Datenrate, Störabstand, Dämpfung und Fehlerzähler notieren.</li><li><strong>APL und erste TAE vergleichen:</strong> Schlechtere Werte an der TAE sprechen häufig für Endleitung, Klemmstelle oder Dose.</li><li><strong>LAN vor WLAN testen:</strong> Das Heimnetz erst nach stabiler DSL-Verbindung beurteilen.</li></ol><h2>Typische Einordnung</h2><table><thead><tr><th>Beobachtung</th><th>Zu prüfender Bereich</th></tr></thead><tbody><tr><td>Keine Synchronisation</td><td>Port, Kupfernetz, APL, Endleitung, TAE oder DSL-Kabel</td></tr><tr><td>Abbrüche bei Regen</td><td>Feuchtigkeit an Muffe, Kabel, APL oder Klemmstelle</td></tr><tr><td>Am APL gut, an der TAE schlecht</td><td>Endleitung, Abzweigung oder TAE</td></tr><tr><td>LAN stabil, WLAN langsam</td><td>Routerstandort, Funkkanal und Heimnetz</td></tr></tbody></table><p>Ein Speedtest allein trennt Anschlussfehler nicht von WLAN-, LAN- oder Endgeräteproblemen.</p>' . $sources . '</article>',
            'tae-erklaert' => '<article class="gk-clean-article">' . self::photo('tae-dose.jpg', 'Weiße TAE-NFF-Anschlussdose mit drei Buchsen.', 'TAE-Dose: Anschluss- und Messpunkt eines kupferbasierten Telefon- oder DSL-Anschlusses. Foto: Uwe Schwöbel, GNU FDL 1.2, via Wikimedia Commons.') . '<h2>Was ist eine TAE?</h2><p>Die Telekommunikations-Anschluss-Einheit ist eine Anschlussdose für kupferbasierte Telefon- und DSL-Anschlüsse. Die erste TAE liegt hinter APL und Endleitung. Gf-AP, Gf-TA und ONT gehören dagegen zu Glasfaseranschlüssen.</p><h2>Warum ist die erste TAE wichtig?</h2><p>Der Vergleich einer Messung am APL mit der Messung an der ersten TAE zeigt, ob Endleitung oder Dose die DSL-Verbindung verschlechtern.</p><h2>Typische Fehler</h2><ul><li>lose oder korrodierte Kontakte</li><li>parallel angeschlossene weitere Dosen</li><li>unnötige Verlängerungen und Abzweigungen</li><li>beschädigte Anschlussleitung zum Router</li></ul><p>Dose freiräumen, DSL-Kabel kontrollieren und Routerwerte dokumentieren. Feste Leitungen nicht eigenmächtig umklemmen.</p>' . $sources . '</article>',
            'warum-misst-der-techniker-am-apl' => '<article class="gk-clean-article">' . self::photo('apl.png', 'Geöffneter Kupfer-APL mit Mehraderkabel und Anschlussklemmen.', 'APL: Messpunkt zur Trennung von Betreiber-Kupfernetz und gebäudeseitiger Endleitung.') . '<h2>Warum wird am APL gemessen?</h2><p>Die Messung am APL trennt das Betreiber-Kupfernetz von der gebäudeseitigen Endleitung. Sie zeigt, ob das DSL-Signal bereits am Hausanschluss fehlerhaft ankommt oder erst zwischen APL und erster TAE schlechter wird.</p><h2>Messvergleich in der Praxis</h2><table><thead><tr><th>Ergebnis</th><th>Einordnung</th></tr></thead><tbody><tr><td>APL und erste TAE ähnlich</td><td>Endleitung verursacht wahrscheinlich keinen großen zusätzlichen Verlust.</td></tr><tr><td>APL deutlich besser als erste TAE</td><td>Endleitung, Klemmstelle, Abzweigung oder TAE prüfen.</td></tr><tr><td>Bereits am APL auffällig</td><td>Fehler im Betreiber-Kupfernetz oder am Port weiter eingrenzen.</td></tr></tbody></table><p>Ein WLAN-Speedtest ersetzt diesen Messvergleich nicht. APL und erste TAE sollten vor dem Termin zugänglich sein; den APL nicht selbst öffnen.</p>' . $sources . '</article>',
            'ftth-anschlussarten-erklaert' => '<article class="gk-clean-article">' . self::photo('glasfaser.png', 'Aufgebautes Glasfaserkabel mit Außenmantel, Zugentlastung und einzelner Faser.', 'Glasfaserkabel transportieren Daten optisch; entscheidend ist, wie weit die Faser bis zum Nutzer geführt wird.') . '<h2>FTTH, FTTB und FTTC eindeutig unterscheiden</h2><table><thead><tr><th>Ausbauart</th><th>Glasfaser endet</th><th>Letzter Abschnitt</th></tr></thead><tbody><tr><td>FTTH</td><td>im Haus oder in der Wohnung</td><td>Glasfaser bis Gf-TA beziehungsweise ONT</td></tr><tr><td>FTTB</td><td>im Gebäude</td><td>gebäudeinterne Weiterführung nach Ausbaukonzept</td></tr><tr><td>FTTC</td><td>am Straßenverteiler</td><td>Kupfer vom MFG/KVz bis APL und TAE</td></tr></tbody></table><h2>Warum die Unterscheidung wichtig ist</h2><p>Nur bei FTTH reicht die Glasfaser bis in den Teilnehmerbereich. Ein Koaxialkabel ist weder eine DSL-Endleitung noch ein FTTH-Glasfaserkabel. Bei FTTC bleiben APL, Endleitung und TAE relevant; bei FTTH dagegen Gf-AP, Gf-TA und gegebenenfalls ONT.</p><h2>Praxisprüfung</h2><ul><li>Vertragliche Ausbauart nicht mit der beworbenen Tarifgeschwindigkeit verwechseln.</li><li>Ankommende Leitung und Netzabschluss identifizieren.</li><li>Routeranschluss prüfen: DSL-Port, Ethernet-WAN hinter ONT oder direkter Glasfaserport.</li></ul>' . $sources . '</article>',
            'gf-ap-erklaert' => '<article class="gk-clean-article">' . self::photo('gf-ap.png', 'Geöffneter Gf-AP mit Faserführung und Spleißablage.', 'Gf-AP: passiver Gebäudeabschluss des Glasfasernetzes.') . '<h2>Was ist ein Gf-AP?</h2><p>Der Glasfaser-Abschlusspunkt ist der passive Abschluss der ankommenden Glasfaser am Gebäude. Er enthält Faserführung, Spleißablage und je nach Ausbau Kupplungen oder vorbereitete Abgänge. Er ist kein Router und benötigt für seine passive Funktion keinen Strom.</p><h2>So lässt er sich einordnen</h2><ul><li><strong>Gf-AP:</strong> Gebäudeabschluss der Glasfaser.</li><li><strong>Gf-TA:</strong> optische Teilnehmeranschlussdose in Haus oder Wohnung.</li><li><strong>ONT:</strong> aktives Gerät zur Umsetzung des optischen Signals auf Ethernet.</li><li><strong>APL:</strong> Gebäudeabschluss des Kupfernetzes für Telefonie und DSL.</li></ul><h2>Montage und Zugang</h2><p>Der Gf-AP liegt häufig im Hausanschluss- oder Technikraum nahe der Gebäudeeinführung. Leitungsweg, Biegeradien und Zugang müssen vor der Montage geklärt sein. Das Gehäuse nicht eigenmächtig öffnen oder Fasern bewegen.</p>' . $sources . '</article>',
            'gf-ta-erklaert' => '<article class="gk-clean-article">' . self::photo('gf-ta.png', 'Glasfaser-Teilnehmeranschlussdose mit optischer Buchse.', 'Gf-TA: passiver optischer Anschluss in Haus oder Wohnung.') . '<h2>Was ist eine Gf-TA?</h2><p>Die Glasfaser-Teilnehmeranschlussdose stellt den passiven optischen Anschluss im Nutzungsbereich bereit. Sie liegt im Signalweg hinter dem Gf-AP und vor ONT oder Glasfaserrouter. Sie ist keine TAE-Dose und wandelt das Signal nicht elektrisch um.</p><h2>Typischer Signalweg</h2><p><strong>Gf-AP → gebäudeinterne Glasfaser → Gf-TA → optisches Patchkabel → ONT oder Glasfaserrouter</strong></p><h2>Praxis</h2><ul><li>Stecker und Buchse müssen zum Anschlusskonzept passen.</li><li>Schutzkappen erst unmittelbar vor dem Verbinden entfernen.</li><li>Faser nicht knicken, quetschen oder an verschmutzten Steckflächen berühren.</li><li>Standort so wählen, dass ONT, Router und Stromversorgung sinnvoll erreichbar sind.</li></ul>' . $sources . '</article>',
            'glasfaser-bauteile-im-haus' => '<article class="gk-clean-article"><h2>Glasfaser-Bauteile im Haus erkennen</h2><div class="gk-compare-photos">' . self::photo('gf-ap.png', 'Geöffneter Gf-AP mit Faserführung und Spleißablage.', 'Gf-AP: passiver Gebäudeabschluss.') . self::photo('gf-ta.png', 'Glasfaser-Teilnehmeranschlussdose mit optischer Buchse.', 'Gf-TA: optischer Anschluss im Nutzungsbereich.') . self::photo('ont.png', 'ONT mit optischem Eingang, Ethernet-Ausgang und Stromversorgung.', 'ONT: aktiver Übergang von Glasfaser zu Ethernet.') . '</div><h2>Der typische FTTH-Signalweg im Haus</h2><p><strong>Gf-AP → gebäudeinterne Glasfaser → Gf-TA → ONT oder Glasfaserrouter → LAN/WLAN</strong></p><h2>Aufgaben klar trennen</h2><p>Gf-AP und Gf-TA sind passive optische Abschlusspunkte. Ein ONT benötigt Strom und stellt Ethernet bereit. Der Router baut die Internetverbindung nach Anbietervorgabe auf und verteilt sie im Heimnetz.</p><h2>Häufige Verwechslungen</h2><ul><li>Ein Kupfer-APL besitzt Doppeladern und Klemmen, keine Glasfaser-Spleißablage.</li><li>Ein Koax-HÜP besitzt Koaxialkabel mit Innenleiter und Schirmung.</li><li>Der ONT ist nicht automatisch der WLAN-Router.</li></ul>' . $sources . '</article>',
            'speedpipe-erklaert' => '<article class="gk-clean-article">' . self::photo('speedpipe.png', 'Verband aus farbigen Mikrorohren für Glasfaserkabel.', 'Speedpipes sind Schutz- und Führungsrohre; sie übertragen selbst kein Signal.') . '<h2>Was ist eine Speedpipe?</h2><p>Speedpipe ist eine gebräuchliche Bezeichnung für ein Mikrorohr, in das ein dafür vorgesehenes Glasfaserkabel eingeblasen wird. Das Rohr schützt und führt das Kabel, enthält aber nicht automatisch bereits eine Faser.</p><h2>Vom Rohr zur nutzbaren Verbindung</h2><ol><li>Mikrorohrverband verlegen und dokumentieren.</li><li>Durchgängigkeit und Dichtheit prüfen.</li><li>Einblaskabel mit geeigneter Technik einbringen.</li><li>Fasern an Muffe, NVT oder Gf-AP spleißen und messen.</li></ol><h2>Typische Fehler</h2><ul><li>zu enge Biegeradien oder gequetschte Rohre</li><li>undichte Kupplungen und eindringende Feuchtigkeit</li><li>verschmutzte oder nicht verschlossene Rohrenden</li><li>nicht dokumentierte Rohrbelegung</li></ul>' . $sources . '</article>',
            'ont-erklaert' => '<article class="gk-clean-article">' . self::photo('ont.png', 'ONT mit optischem Eingang, Ethernet-Ausgang und Stromversorgung.', 'ONT: aktiver Netzabschluss zwischen optischem Anschluss und Ethernet.') . '<h2>Was macht ein ONT?</h2><p>Das Optical Network Terminal beendet die optische Teilnehmerverbindung und stellt auf der Kundenseite Ethernet bereit. Es benötigt Strom. Der ONT ist nicht automatisch ein Router und erzeugt nicht zwingend WLAN.</p><h2>Typischer Anschluss</h2><p><strong>Gf-TA → optisches Patchkabel → ONT → Ethernetkabel → WAN-Port des Routers</strong></p><p>Das Ethernetkabel gehört an den vom Hersteller vorgesehenen WAN-Port, nicht an einen DSL-Port. Anbieter können Registrierung, VLAN oder Zugangsdaten vorgeben.</p><h2>Status und Fehlersuche</h2><ul><li>Stromversorgung und Statusanzeigen prüfen.</li><li>Optisches Patchkabel nicht knicken und Steckflächen nicht berühren.</li><li>Ethernet-Link zwischen ONT und Router kontrollieren.</li><li>LAN-Test durchführen, bevor WLAN bewertet wird.</li></ul>' . $sources . '</article>',
            'ont-erklaert-einfach-erklaert' => '<article class="gk-clean-article">' . self::photo('ont.png', 'ONT mit optischem Eingang, Ethernet-Ausgang und Stromversorgung.', 'ONT: wandelt den optischen Teilnehmeranschluss in eine Ethernet-Schnittstelle für den Router um.') . '<h2>ONT kurz erklärt</h2><p>Ein ONT ist das aktive Abschlussgerät einer FTTH-Verbindung. Es setzt die optische Verbindung auf eine Ethernet-Schnittstelle um. Die Formulierung „wandelt Licht in Internet“ ist verkürzt: Zugangsdaten, Routerfunktion und Heimnetz bleiben eigenständige Aufgaben.</p><h2>ONT und Router unterscheiden</h2><table><thead><tr><th>Gerät</th><th>Aufgabe</th></tr></thead><tbody><tr><td>ONT</td><td>optische Teilnehmerverbindung abschließen und Ethernet bereitstellen</td></tr><tr><td>Router</td><td>Internetverbindung aufbauen, routen, Firewall sowie LAN/WLAN bereitstellen</td></tr></tbody></table><h2>Richtig verbinden</h2><p><strong>Gf-TA → ONT → WAN-Port des Routers.</strong> Das DSL-Modem eines Kombirouters wird hinter dem ONT nicht verwendet. Maßgeblich bleiben die Vorgaben des Anbieters.</p>' . $sources . '</article>',
            'glasfaser-spleissen-erklaert' => '<article class="gk-clean-article">' . self::photo('spleissstelle.png', 'Geschützte Glasfaser-Spleißstelle in einer Spleißkassette.', 'Fusionsspleiß: dauerhaft verbundene Fasern mit Spleißschutz in geordneter Ablage.') . '<h2>Was bedeutet Spleißen?</h2><p>Beim Fusionsspleißen werden zwei vorbereitete Glasfasern präzise ausgerichtet und mit einem Lichtbogen dauerhaft verbunden. Danach schützt eine Spleißschutzhülse die Verbindungsstelle.</p><h2>Arbeitsablauf</h2><ol><li>Faser absetzen und Beschichtung entfernen.</li><li>Faser reinigen und mit einem Cleaver rechtwinklig brechen.</li><li>Fasern im Spleißgerät ausrichten und verbinden.</li><li>Dämpfung beziehungsweise Spleißqualität bewerten.</li><li>Spleiß schützen und ohne enge Biegung in der Kassette ablegen.</li></ol><h2>Warum Fachpersonal nötig ist</h2><p>Verschmutzung, schlechter Faserbruch, ungeeignete Parameter oder falsche Ablage erhöhen die Dämpfung und können spätere Ausfälle verursachen. Offene Fasern und Laserstrahlung erfordern geeignete Arbeits- und Schutzregeln.</p>' . $sources . '</article>',
            'lc-stecker-erklaert' => '<article class="gk-clean-article">' . self::photo('steckverbinder.png', 'LC/UPC- und SC/APC-Glasfasersteckverbinder im Vergleich.', 'LC ist eine kompakte Steckverbinderbauform; Schliffart und Kupplung müssen zum Anschluss passen.') . '<h2>Was ist ein LC-Stecker?</h2><p>LC ist eine kompakte Glasfaser-Steckverbinderbauform mit 1,25-Millimeter-Ferrule und Rastmechanik. Die Bauform allein sagt noch nichts über Faserart oder Schliff aus.</p><h2>UPC und APC nicht verwechseln</h2><p>UPC- und APC-Schliffe besitzen unterschiedliche Stirnflächen. APC ist schräg geschliffen und häufig grün gekennzeichnet. Unpassende Schliffe dürfen nicht miteinander verbunden werden, auch wenn mechanisch ähnliche Adapter vorhanden sind.</p><h2>Praxisregeln</h2><ul><li>Stecker nur an gereinigte und passende Kupplungen anschließen.</li><li>Schutzkappen sauber halten.</li><li>Steckfläche vor dem Verbinden prüfen und fachgerecht reinigen.</li><li>Patchkabel nicht knicken, ziehen oder unter Spannung verlegen.</li></ul>' . $sources . '</article>',
            'router-im-keller' => '<article class="gk-clean-article">' . self::photo('wlan-heimnetz.png', 'Haus mit Router, LAN-Verbindungen und WLAN-Versorgung.', 'Ein zentraler Router oder kabelgebundener Access Point versorgt Wohnbereiche zuverlässiger als ein Router im Keller.') . '<h2>Warum der Keller für WLAN ungünstig ist</h2><p>Kellerdecken, Stahlbeton, Metall, Leitungen und große Wasserflächen schwächen das Funksignal. Das Problem entsteht nicht durch den APL oder die Kupferleitung, sondern durch den Funkweg zwischen Router und Endgerät.</p><h2>Die technisch saubere Lösung</h2><ol><li>Internetanschluss per LAN direkt am Router prüfen.</li><li>Netzwerkkabel vom Keller in einen zentralen Wohnbereich führen.</li><li>Dort Access Point oder Mesh-Knoten mit LAN-Backhaul betreiben.</li><li>Erst danach zusätzliche Funkknoten planen.</li></ol><h2>Wenn kein LAN-Kabel vorhanden ist</h2><p>Ein Repeater muss noch ein gutes Signal vom Router empfangen. Er gehört nicht in das Funkloch. Eine Platzierung im Treppenhaus oder auf halber Strecke ist meist besser.</p>' . $sources . '</article>',
            'routerstandort-optimieren' => '<article class="gk-clean-article">' . self::photo('wlan-heimnetz.png', 'Zentral platzierter Router mit kabelgebundenen und drahtlosen Endgeräten.', 'Router frei, erhöht und möglichst zentral aufstellen.') . '<h2>Der beste Routerstandort</h2><p>Der Router sollte frei, erhöht und möglichst zentral zu den genutzten Räumen stehen. Schränke, Heizungsräume, Metallflächen, Aquarien und massive Decken verschlechtern die Funkabdeckung.</p><h2>Standort systematisch prüfen</h2><ul><li>LAN-Messung direkt am Router als Referenz durchführen.</li><li>Signal und Datenrate an typischen Nutzungsorten messen.</li><li>Router versuchsweise höher und freier positionieren.</li><li>2,4 und 5 GHz getrennt bewerten.</li><li>Für weitere Etagen LAN-Backhaul bevorzugen.</li></ul><h2>Anschlussart und Standort trennen</h2><p>Bei DSL begrenzt die erste TAE den möglichen Routerstandort; bei FTTH häufig Gf-TA oder ONT. Ein längeres geeignetes Anschluss- oder Netzwerkkabel kann sinnvoller sein als ein Funk-Repeater.</p>' . $sources . '</article>',
            'ont-und-router-unterschied-premium' => '<article class="gk-clean-article">' . self::photo('ont.png', 'ONT mit optischem Eingang, Ethernet-Ausgang und Stromversorgung.', 'Der ONT beendet die optische Verbindung; der Router übernimmt Internetzugang und Heimnetz.') . '<h2>ONT und Router haben verschiedene Aufgaben</h2><table><thead><tr><th>Gerät</th><th>Aufgabe</th></tr></thead><tbody><tr><td>ONT</td><td>optische Teilnehmerverbindung abschließen und Ethernet bereitstellen</td></tr><tr><td>Router</td><td>Internetverbindung, Routing, Firewall, LAN und WLAN bereitstellen</td></tr></tbody></table><h2>Richtig anschließen</h2><p><strong>Gf-TA → optisches Patchkabel → ONT → Ethernetkabel → WAN-Port des Routers.</strong> Der DSL-Port eines Kombirouters bleibt hinter dem ONT unbenutzt.</p><h2>Fehler getrennt eingrenzen</h2><ul><li>Optischen Status und Stromversorgung des ONT prüfen.</li><li>Ethernet-Link zwischen ONT und Router kontrollieren.</li><li>Internetzugang per LAN am Router testen.</li><li>WLAN erst danach beurteilen.</li></ul>' . $sources . '</article>',
            'access-point-oder-repeater' => '<article class="gk-clean-article">' . self::photo('mesh.png', 'Router und zusätzliche WLAN-Zugangspunkte in einem Haus.', 'Kabelgebundener Access Point und Funk-Repeater erfüllen unterschiedliche Aufgaben.') . '<h2>Der entscheidende Unterschied</h2><table><thead><tr><th>Lösung</th><th>Uplink</th><th>Typische Stärke</th></tr></thead><tbody><tr><td>Access Point</td><td>LAN-Kabel</td><td>stabile Datenrate und geringe Latenz</td></tr><tr><td>Repeater</td><td>WLAN</td><td>schnelle Nachrüstung ohne Kabel</td></tr><tr><td>Mesh-Knoten</td><td>WLAN oder LAN</td><td>gemeinsame Steuerung und Roaming-Funktionen</td></tr></tbody></table><h2>Wann welche Lösung?</h2><p>Ist ein Netzwerkkabel vorhanden, ist ein Access Point meist die belastbarere Lösung. Ein Repeater eignet sich für einzelne Funklöcher, sofern er am Montageort noch ein starkes Signal empfängt. Für mehrere Etagen ist ein Mesh mit LAN-Backhaul vorzuziehen.</p><h2>Vor dem Kauf</h2><p>Vorhandene Verkabelung, benötigte LAN-Ports, Stromversorgung, Herstellerkompatibilität und gewünschte WLAN-Standards prüfen.</p>' . $sources . '</article>',
            'mesh-wlan-erklaert' => '<article class="gk-clean-article">' . self::photo('mesh.png', 'Mesh-System mit Router und mehreren Zugangspunkten.', 'Mesh koordiniert mehrere WLAN-Zugangspunkte; ein guter Uplink bleibt entscheidend.') . '<h2>Was bedeutet Mesh-WLAN?</h2><p>Ein Mesh-System verwaltet mehrere Zugangspunkte gemeinsam. Einheitliche Konfiguration, Bandsteuerung und Roaming-Hilfen können Endgeräte beim Wechsel unterstützen. Mesh ersetzt jedoch keinen leistungsfähigen Uplink.</p><h2>Funk- oder LAN-Backhaul</h2><p>Bei Funk-Backhaul teilen sich Nutzdaten und Verbindung der Knoten die verfügbare Funkkapazität. LAN-Backhaul verbindet die Knoten kabelgebunden und ist meist stabiler.</p><h2>Richtig planen</h2><ul><li>Knoten nicht im Funkloch aufstellen.</li><li>Pro Etage zuerst einen geeigneten Standort testen.</li><li>LAN-Backhaul nutzen, wo Kabel vorhanden sind.</li><li>Nach Änderungen Roaming und Durchsatz an realen Endgeräten prüfen.</li></ul>' . $sources . '</article>',
            'repeater-erklaert' => '<article class="gk-clean-article">' . self::photo('mesh.png', 'WLAN-Router und zusätzlicher Funkknoten.', 'Ein Repeater erweitert ein vorhandenes WLAN nur dort sinnvoll, wo er selbst guten Empfang hat.') . '<h2>Was macht ein WLAN-Repeater?</h2><p>Ein Repeater empfängt ein vorhandenes WLAN und sendet es weiter. Er repariert keine langsame Internetleitung und kann nur die Funkverbindung erweitern, die an seinem Standort ankommt.</p><h2>Grenzen</h2><p>Bei ungünstigem Funk-Uplink sinken nutzbare Datenrate und Stabilität. Wände und Decken wirken auf die Verbindung Router–Repeater ebenso wie auf die Verbindung Repeater–Endgerät.</p><h2>Alternativen</h2><p>Ein kabelgebundener Access Point oder ein Mesh-Knoten mit LAN-Backhaul ist für Homeoffice, mehrere Etagen und hohe konstante Datenraten meist besser geeignet.</p>' . $sources . '</article>',
            '2-4-ghz-5-ghz-oder-6-ghz' => '<article class="gk-clean-article">' . self::photo('wlan-heimnetz.png', 'Heimnetz mit WLAN-Geräten in unterschiedlichen Entfernungen.', 'Das passende Frequenzband hängt von Entfernung, Wänden und Endgeräteunterstützung ab.') . '<h2>Die drei WLAN-Bänder im Vergleich</h2><table><thead><tr><th>Band</th><th>Stärke</th><th>Grenze</th></tr></thead><tbody><tr><td>2,4 GHz</td><td>größere Reichweite und breite Geräteunterstützung</td><td>wenige überlappungsfreie Kanäle und oft stark belegt</td></tr><tr><td>5 GHz</td><td>mehr Bandbreite und mehr Kanäle</td><td>geringere Reichweite durch Bauteile</td></tr><tr><td>6 GHz</td><td>zusätzliches Spektrum für kompatible Geräte</td><td>kurze Reichweite und neue Hardware erforderlich</td></tr></tbody></table><h2>Praxisempfehlung</h2><p>2,4 GHz eignet sich häufig für entfernte oder einfache Geräte. 5 GHz ist in Routernähe meist die beste Kombination aus Tempo und Reichweite. 6 GHz lohnt sich für kompatible Geräte bei kurzem Funkweg. Automatische Bandsteuerung kann sinnvoll sein, muss aber mit den realen Endgeräten geprüft werden.</p>' . $sources . '</article>',
            'wlan-kanal-wechseln' => '<article class="gk-clean-article">' . self::photo('wlan-heimnetz.png', 'WLAN-Router und Endgeräte im Heimnetz.', 'Ein Kanalwechsel hilft nur, wenn tatsächlich Kanalbelegung oder Störungen die Ursache sind.') . '<h2>Wann ein Kanalwechsel sinnvoll ist</h2><p>Ein manueller Kanalwechsel kann helfen, wenn mehrere benachbarte WLANs denselben oder überlappende Kanäle stark nutzen. Er hilft nicht gegen einen schlechten Routerstandort, massive Wände oder einen Repeater im Funkloch.</p><h2>Vorgehen</h2><ol><li>LAN-Verbindung als Referenz prüfen.</li><li>Belegung am betroffenen Ort zu mehreren Zeiten messen.</li><li>Automatische Kanalwahl dokumentieren.</li><li>Nur bei nachvollziehbarer Belegung einen geeigneten Kanal testen.</li><li>Durchsatz und Stabilität danach erneut messen.</li></ol><h2>2,4 GHz besonders beachten</h2><p>Bei 20-MHz-Kanalbreite werden in Europa häufig 1, 5, 9 und 13 als überlappungsarme Planung verwendet; verbreitet ist auch die 1/6/11-Planung. Entscheidend ist die lokale Belegung und Gerätekompatibilität, nicht eine pauschale Kanalnummer.</p>' . $sources . '</article>',
            'wifi-7-erklaert' => '<article class="gk-clean-article">' . self::photo('wlan-heimnetz.png', 'Modernes Heimnetz mit WLAN- und LAN-Geräten.', 'Wi-Fi 7 verbessert Funkkapazität und Latenz, ersetzt aber keine gute Netzplanung.') . '<h2>Was bringt Wi-Fi 7?</h2><p>Wi-Fi 7 basiert auf IEEE 802.11be. Zu den Neuerungen gehören breitere Kanäle im 6-GHz-Band, 4096-QAM und Multi-Link Operation. Welche Funktionen nutzbar sind, hängt von Router, Endgerät, Region und Funkumgebung ab.</p><h2>Wann lohnt sich der Umstieg?</h2><p>Ein Umstieg lohnt sich vor allem bei kompatiblen Endgeräten, hoher lokaler Datenlast, schnellen NAS-Verbindungen oder wenn ohnehin neue Hardware benötigt wird. Ein stabiles Wi-Fi-6-Netz muss nicht allein wegen der höheren theoretischen Datenrate ersetzt werden.</p><h2>Realistische Grenzen</h2><ul><li>Wände, Entfernung und Störungen bleiben wirksam.</li><li>Internettempo ist durch Tarif und Anschluss begrenzt.</li><li>Für konstante niedrige Latenz bleibt LAN die Referenz.</li></ul>' . $sources . '</article>',
            'repeater-richtig-platzieren' => '<article class="gk-clean-article">' . self::photo('mesh.png', 'Router und zusätzlicher WLAN-Knoten auf halber Strecke zum Zielbereich.', 'Der Repeater gehört in den Bereich mit noch gutem Router-Signal, nicht in das Funkloch.') . '<h2>Die wichtigste Platzierungsregel</h2><p>Der Repeater muss den Router noch zuverlässig empfangen. Ein Standort direkt im schlecht versorgten Raum wiederholt nur eine bereits schwache Verbindung.</p><h2>Schrittweise platzieren</h2><ol><li>Zielbereich ohne Repeater messen.</li><li>Repeater zunächst ungefähr auf halber Strecke aufstellen.</li><li>Signalqualität des Uplinks kontrollieren.</li><li>Durchsatz und Stabilität im Zielraum testen.</li><li>Standort in kleinen Schritten optimieren.</li></ol><h2>Typische Hindernisse</h2><p>Stahlbetondecken, Metall, Fußbodenheizung, Spiegel und Wasserflächen können den Funkweg stark beeinträchtigen. Bei mehreren Etagen ist LAN-Backhaul oder ein kabelgebundener Access Point häufig die bessere Lösung.</p>' . $sources . '</article>',
            'dsl-stoerung-systematisch-eingrenzen' => '<article class="gk-clean-article">' . self::photo('apl.png', 'Geöffneter Kupfer-APL mit Mehraderkabel und Anschlussklemmen.', 'Bei einer DSL-Störung werden Betreiberstrecke, Endleitung und Heimnetz getrennt geprüft.') . '<h2>DSL-Störung in der richtigen Reihenfolge prüfen</h2><ol><li><strong>Synchronisation:</strong> Zeigt der Router eine DSL-Verbindung zum DSLAM/MSAN?</li><li><strong>Leitungswerte:</strong> Datenrate, Störabstand, Dämpfung sowie CRC- und FEC-Zähler dokumentieren.</li><li><strong>Messpunkte:</strong> Werte an erster TAE und bei Bedarf am APL vergleichen.</li><li><strong>Internetzugang:</strong> Erst nach stabiler Synchronisation Einwahl und Anbieterzugang prüfen.</li><li><strong>Heimnetz:</strong> LAN als Referenz testen und WLAN anschließend getrennt bewerten.</li></ol><h2>Beobachtung richtig zuordnen</h2><table><thead><tr><th>Beobachtung</th><th>Zu prüfender Bereich</th></tr></thead><tbody><tr><td>Keine DSL-Synchronisation</td><td>Port, Kupfer-Zugangsnetz, APL, Endleitung, TAE oder DSL-Kabel</td></tr><tr><td>APL gut, erste TAE schlechter</td><td>Endleitung, Abzweigung, Klemmstelle oder TAE</td></tr><tr><td>DSL stabil, LAN langsam</td><td>Einwahl, Tarif, Router, Ethernet oder Endgerät</td></tr><tr><td>LAN gut, WLAN langsam</td><td>Funkkanal, Standort, Reichweite oder Endgerät</td></tr></tbody></table><p>Router-Neustarts können Zähler und Verlauf löschen. Vorher Screenshots und Uhrzeiten der Abbrüche sichern.</p>' . $sources . '</article>',
            'dsl-synchronisiert-nicht' => '<article class="gk-clean-article">' . self::photo('tae-dose.jpg', 'Weiße TAE-NFF-Anschlussdose mit drei Buchsen.', 'Erste TAE: regulärer Anschluss- und Messpunkt des DSL-Routers. Foto: Uwe Schwöbel, GNU FDL 1.2, via Wikimedia Commons.') . '<h2>Was bedeutet fehlende Synchronisation?</h2><p>Ohne DSL-Synchronisation besteht keine physikalische DSL-Verbindung zwischen dem Modem im Router und dem DSLAM/MSAN. Das ist von einer fehlgeschlagenen Internet-Einwahl trotz bestehender Synchronisation zu unterscheiden.</p><h2>Sichere Erstprüfung</h2><ol><li>Statusanzeige und Ereignisprotokoll des Routers prüfen.</li><li>DSL-Kabel direkt an der ersten TAE anschließen; unnötige Verlängerungen entfernen.</li><li>Stecker, Netzteil und Routerneustart einmal kontrolliert testen.</li><li>Beginn, Dauer und Wetterbezug der Störung dokumentieren.</li><li>Bei weiter fehlender Synchronisation eine Leitungsprüfung veranlassen.</li></ol><h2>Mögliche Fehlerstellen</h2><p>Infrage kommen Port oder Rangierung, Kupfer-Zugangsnetz, Muffe, APL, Endleitung, erste TAE, DSL-Kabel oder Modem. Der Ort lässt sich erst durch Messungen und Vergleiche eingrenzen.</p><p>APL und feste Leitungen nicht selbst öffnen oder umklemmen.</p>' . $sources . '</article>',
            'dsl-ausfall-bei-regen-die-haeufigsten-ursachen' => '<article class="gk-clean-article">' . self::photo('apl.png', 'Geöffneter Kupfer-APL mit Mehraderkabel und Anschlussklemmen.', 'Wetterabhängige DSL-Fehler werden entlang der Kupferstrecke und an Verbindungsstellen gesucht.') . '<h2>Warum Regen DSL-Störungen sichtbar machen kann</h2><p>Wenn Abbrüche reproduzierbar bei Regen oder hoher Feuchtigkeit auftreten, ist eine beeinträchtigte Kabel- oder Verbindungsstelle wahrscheinlich. Wasser muss dabei nicht im Hausanschluss stehen: Auch Muffen, Kabelschäden und Anschlusspunkte im Zugangsnetz kommen infrage.</p><h2>Typische Anzeichen</h2><ul><li>sinkende Störabstandsmarge vor dem Abbruch</li><li>stark ansteigende CRC-Fehler</li><li>wiederholte Resynchronisationen</li><li>normale Werte nach längerer Trockenphase</li></ul><h2>So wird der Fehler belegbar</h2><ol><li>Datum, Uhrzeit und Wetterlage notieren.</li><li>Routerwerte und Ereignisprotokoll vor und während der Störung sichern.</li><li>DSL an der ersten TAE ohne Verlängerung betreiben.</li><li>Störung mit Hinweis „wetterabhängig“ melden.</li></ol><p>Eine Sichtprüfung ersetzt keine Messung. APL, Muffen und Netzbetreiberkabel dürfen nur durch berechtigtes Fachpersonal geöffnet oder bearbeitet werden.</p>' . $sources . '</article>',
            'endleitung-dsl-probleme' => '<article class="gk-clean-article">' . self::photo('tal.png', 'Mehraderiges Kupferkabel mit ausgewählter Doppelader.', 'Die Endleitung führt als Kupfer-Doppelader vom APL zur ersten TAE.') . '<h2>Was ist die DSL-Endleitung?</h2><p>Die Endleitung ist die gebäudeseitige Kupferverbindung zwischen APL und erster TAE. Sie gehört weder zum WLAN noch zur Glasfaserstrecke. Schlechte Kontakte, ungeeignete Leitungen und Abzweigungen können DSL-Datenrate und Stabilität verschlechtern.</p><h2>Typische Fehlerquellen</h2><ul><li>lose, korrodierte oder mehrfach belegte Klemmstellen</li><li>parallel geschaltete TAE-Dosen und ungenutzte Abzweige</li><li>alte Flach-, Klingel- oder flexible Verlängerungsleitungen</li><li>Quetschungen, Feuchtigkeit oder beschädigte Adern</li></ul><h2>Messvergleich</h2><p>Sind die Werte am APL deutlich besser als an der ersten TAE, liegt die zusätzliche Beeinträchtigung wahrscheinlich in Endleitung, Klemmstellen oder Dose. Ähnliche Werte sprechen gegen einen großen zusätzlichen Verlust im Gebäude.</p><h2>Wann erneuern?</h2><p>Eine Erneuerung ist sinnvoll, wenn der Fehler messtechnisch der Endleitung zugeordnet wurde oder die vorhandene Leitung ungeeignet beziehungsweise beschädigt ist. Die Ausführung und Zuständigkeit müssen vorab geklärt werden.</p>' . $sources . '</article>',
            'crc-fehler-erklaert-was-sie-ueber-eine-dsl-leitung-aussagen' => '<article class="gk-clean-article">' . self::photo('tae-dose.jpg', 'Weiße TAE-NFF-Anschlussdose mit drei Buchsen.', 'CRC-Fehler werden auf der DSL-Verbindung bewertet; erste TAE und Endleitung sind mögliche, aber nicht die einzigen Fehlerstellen. Foto: Uwe Schwöbel, GNU FDL 1.2, via Wikimedia Commons.') . '<h2>Was sind CRC-Fehler?</h2><p>CRC-Fehler zeigen Datenblöcke, die trotz Übertragungsschutz nicht korrekt empfangen wurden. Sie können Wiederholungen, geringeren nutzbaren Durchsatz und bei starker Häufung eine instabile Verbindung begleiten.</p><h2>Die Anzahl allein reicht nicht</h2><p>Entscheidend sind Zeitraum, Datenverkehr und gleichzeitiges Fehlerbild. Einige Fehler über lange Laufzeit sind anders zu bewerten als ein schneller Anstieg innerhalb weniger Minuten mit Abbrüchen.</p><h2>Praxisbewertung</h2><ul><li>Zählerstand und Routerlaufzeit gemeinsam notieren.</li><li>Fehlerzuwachs pro Stunde statt bloßen Gesamtwert vergleichen.</li><li>Störabstandsmarge und Resynchronisationen parallel beobachten.</li><li>DSL-Verbindung von LAN- und WLAN-Problemen trennen.</li><li>Bei auffälligem Zuwachs Messung an erster TAE und APL vergleichen lassen.</li></ul><p>CRC-Fehler beweisen nicht automatisch einen defekten Router oder eine bestimmte Kabelstelle; sie sind ein Symptom für die weitere Eingrenzung.</p>' . $sources . '</article>',
            'fec-fehler-richtig-interpretieren' => '<article class="gk-clean-article">' . self::photo('tae-dose.jpg', 'Weiße TAE-NFF-Anschlussdose mit drei Buchsen.', 'FEC-Zähler gehören zur Bewertung der DSL-Übertragung und müssen zusammen mit Laufzeit und CRC-Fehlern betrachtet werden. Foto: Uwe Schwöbel, GNU FDL 1.2, via Wikimedia Commons.') . '<h2>Was bedeuten FEC-Fehler?</h2><p>FEC steht für Forward Error Correction. Der Zähler zeigt Übertragungsfehler, die durch die Fehlerkorrektur erkannt und korrigiert werden konnten. Deshalb bedeutet ein steigender FEC-Zähler nicht automatisch einen spürbaren Ausfall.</p><h2>Richtig bewerten</h2><ul><li>Routerlaufzeit und Beobachtungszeitraum berücksichtigen.</li><li>Zuwachs pro Zeiteinheit statt Gesamtstand vergleichen.</li><li>CRC-Fehler, Störabstandsmarge und Resynchronisationen mitprüfen.</li><li>Änderungen unter Last und zu verschiedenen Tageszeiten dokumentieren.</li></ul><h2>Wann genauer prüfen?</h2><p>Wenn FEC-Werte plötzlich stark ansteigen und gleichzeitig CRC-Fehler, Paketverluste, sinkende Datenrate oder Abbrüche auftreten, sollte die DSL-Strecke systematisch geprüft werden. Ein hoher Gesamtwert nach langer Laufzeit ist ohne diesen Kontext nicht aussagekräftig.</p>' . $sources . '</article>',
            'snr-stoerabstandsmarge-erklaert' => '<article class="gk-clean-article">' . self::photo('tal.png', 'Mehraderiges Kupferkabel mit ausgewählter DSL-Doppelader.', 'Die Störabstandsmarge beschreibt die Reserve zwischen nutzbarem DSL-Signal und Störpegel.') . '<h2>Störabstandsmarge verständlich erklärt</h2><p>Die Störabstandsmarge – häufig als SNR Margin bezeichnet – ist die verbleibende Reserve gegenüber Störungen. Sie ist nicht identisch mit dem absoluten Signal-Rausch-Abstand und wird meist getrennt für Downstream und Upstream angezeigt.</p><h2>Warum ein Einzelwert nicht genügt</h2><p>Der Wert hängt unter anderem von Profil, Datenrate, Frequenzbelegung und aktuellen Störungen ab. Ein niedriger oder schwankender Wert ist vor allem dann auffällig, wenn gleichzeitig CRC-Fehler oder Resynchronisationen auftreten.</p><h2>Praxisprüfung</h2><ol><li>Werte nach stabiler Synchronisation notieren.</li><li>Verlauf zu Störungszeiten und bei normalem Betrieb vergleichen.</li><li>CRC-/FEC-Zähler sowie Datenrate parallel sichern.</li><li>Bei Abweichungen Messpunkte an erster TAE und APL vergleichen lassen.</li></ol><p>Pauschale Grenzwerte ohne Kenntnis des DSL-Profils sind keine sichere Diagnose.</p>' . $sources . '</article>',
            'was-prueft-ein-techniker-bei-einer-entstoerung' => '<article class="gk-clean-article">' . self::photo('techniker-werkzeuge.png', 'Messgerät, Reinigungs- und Montagewerkzeuge für die Telekommunikationspraxis.', 'Prüfschritte richten sich nach Anschlussart und Fehlerbild; DSL und Glasfaser benötigen unterschiedliche Messmittel.') . '<h2>Die Entstörung beginnt mit dem Fehlerbild</h2><p>Der Techniker prüft nicht automatisch jeden Punkt, sondern folgt Messwerten und Beobachtungen. Zuerst werden Anschlussart, Störungszeitraum und betroffene Dienste geklärt.</p><h2>Bei DSL</h2><ol><li>Synchronisation, Datenrate, Störabstand und Fehlerzähler prüfen.</li><li>Messung an erster TAE und bei Bedarf am APL vergleichen.</li><li>Endleitung, Klemmstellen und Anschlusskabel eingrenzen.</li><li>Betreiberstrecke beziehungsweise Port prüfen lassen, wenn der Fehler bereits am APL besteht.</li></ol><h2>Bei FTTH</h2><ol><li>Status von ONT oder Glasfaserrouter prüfen.</li><li>Steckverbindungen, Biegeradien und sichtbare Beschädigungen kontrollieren.</li><li>Optischen Pegel oder Streckenereignisse mit geeignetem Messgerät bewerten.</li><li>Ethernet- und Routerverbindung anschließend getrennt testen.</li></ol><h2>Was vorbereitet sein sollte</h2><p>Zugang zu APL und erster TAE bei DSL beziehungsweise Gf-AP, Gf-TA und ONT bei FTTH; außerdem Router, Netzteil, Anschlusskabel und dokumentierte Störungszeiten.</p>' . $sources . '</article>',
            'technikertermin-dsl-vorbereiten' => '<article class="gk-clean-article">' . self::photo('apl.png', 'Geöffneter Kupfer-APL mit Mehraderkabel und Anschlussklemmen.', 'Für einen DSL-Termin müssen APL und erste TAE erreichbar sein; den APL öffnet nur berechtigtes Fachpersonal.') . '<h2>Vor dem DSL-Technikertermin</h2><ul><li>Termin, Ansprechpartner und erreichbare Telefonnummer bestätigen.</li><li>Keller, Hausanschlussraum und Wohnung zugänglich machen.</li><li>Hausmeister oder Vermieter rechtzeitig informieren, wenn Schlüssel nötig sind.</li><li>APL und erste TAE freiräumen, aber nicht selbst öffnen oder umklemmen.</li><li>Router, Netzteil und DSL-Anschlusskabel bereithalten.</li></ul><h2>Störung dokumentieren</h2><p>Beginn, Häufigkeit, Wetterbezug, Router-Ereignisse und Leitungswerte notieren. Bei zeitweiligen Fehlern sind genaue Uhrzeiten besonders hilfreich.</p><h2>Was der Techniker vergleichen kann</h2><p>Die Messung an der ersten TAE bildet den regulären Kundenanschluss ab. Bei Abweichungen kann der Vergleich am APL Betreiberstrecke und gebäudeseitige Endleitung trennen.</p><h2>Nicht mit FTTH verwechseln</h2><p>Gf-AP, Gf-TA und ONT gehören zum Glasfaseranschluss. Für einen DSL-Termin sind APL, Kupfer-Endleitung und erste TAE maßgeblich.</p>' . $sources . '</article>',
            'warum-wird-an-der-ersten-tae-gemessen' => '<article class="gk-clean-article">' . self::photo('tae-dose.jpg', 'Weiße TAE-NFF-Anschlussdose mit drei Buchsen.', 'Erste TAE: regulärer Anschluss- und Messpunkt eines DSL-Anschlusses. Foto: Uwe Schwöbel, GNU FDL 1.2, via Wikimedia Commons.') . '<h2>Warum ist die erste TAE der erste Messpunkt?</h2><p>Die erste TAE ist der reguläre Übergabepunkt in den Kundenräumen, an dem der DSL-Router angeschlossen wird. Eine Messung dort erfasst die gesamte Strecke bis zum üblichen Routeranschluss – einschließlich der Endleitung ab APL.</p><h2>Was zeigt der Vergleich mit dem APL?</h2><table><thead><tr><th>Messbild</th><th>Einordnung</th></tr></thead><tbody><tr><td>Werte an APL und erster TAE ähnlich</td><td>Endleitung verursacht wahrscheinlich keinen großen zusätzlichen Verlust.</td></tr><tr><td>Werte an erster TAE deutlich schlechter</td><td>Endleitung, Abzweigung, Klemmstelle oder TAE prüfen.</td></tr><tr><td>Bereits am APL auffällig</td><td>Betreiber-Kupfernetz oder Port weiter eingrenzen.</td></tr></tbody></table><h2>Vorbereitung</h2><p>Erste TAE freiräumen, Router und DSL-Kabel bereithalten und weitere Dosen oder Abzweigungen nennen. Feste Leitungen und APL nicht selbst bearbeiten.</p>' . $sources . '</article>',
        ];
    }

    public static function start_buffer(): void {
        if (is_admin() || wp_doing_ajax() || wp_is_json_request()) { return; }
        $request_path = trim((string) parse_url((string) ($_SERVER['REQUEST_URI'] ?? ''), PHP_URL_PATH), '/');
        self::$is_legal = is_page(['impressum-2', 'datenschutz-2', 'kontakt-2']) || in_array($request_path, ['impressum-2', 'datenschutz-2', 'kontakt-2'], true);
        self::$is_front = is_front_page();
        self::$slug = is_singular() ? (string) get_post_field('post_name', get_queried_object_id()) : '';
        ob_start([self::class, 'clean_html']);
    }

    public static function legal_visibility_guard(): void {
        $request_path = trim((string) parse_url((string) ($_SERVER['REQUEST_URI'] ?? ''), PHP_URL_PATH), '/');
        if (!in_array($request_path, ['impressum-2', 'datenschutz-2', 'kontakt-2'], true)) { return; }
        echo '<style id="gk-final-legal-guard">.gk9-tarifcheck,.gkpr-affiliate,.gk9-authorbox,.gkpr-author{display:none!important}</style>';
    }

    public static function author_name($name): string {
        $name = trim(wp_strip_all_tags((string) $name));
        return $name !== '' ? $name : self::AUTHOR_NAME;
    }

    public static function author_link($url): string {
        return self::AUTHOR_URL;
    }

    public static function footer($text): string {
        return 'Copyright © ' . wp_date('Y') . ' Glasfaser-Kompass';
    }

    public static function social_image($url): string {
        if (is_singular()) {
            $slug = self::$slug !== '' ? self::$slug : (string) get_post_field('post_name', get_queried_object_id());
            if (str_contains($slug, 'apl') || str_contains($slug, 'tae') || str_contains($slug, 'dsl')) {
                return home_url('/wp-content/plugins/gk-render-guard/assets/apl.png');
            }
            if (preg_match('/router|wlan|mesh|repeater|fritzbox|speedport/', $slug)) {
                return home_url('/wp-content/plugins/gk-render-guard/assets/wlan-heimnetz.png');
            }
            if (str_contains($slug, 'gf-ap') || str_contains($slug, 'glasfaser') || str_contains($slug, 'ftth')) {
                return home_url('/wp-content/plugins/gk-render-guard/assets/gf-ap.png');
            }
            if (str_contains($slug, 'ont')) {
                return home_url('/wp-content/plugins/gk-render-guard/assets/ont.png');
            }
        }
        return (string) $url;
    }

    private static function strip_dynamic_sections(string $html): string {
        $classes = '(?:gk9-tarifcheck|gk9-authorbox|gkpr-affiliate|gkpr-author)';
        $pattern = '~<section\b[^>]*class=(["\'])[^"\']*' . $classes . '[^"\']*\1[^>]*>.*?</section>~is';
        return (string) preg_replace($pattern, '', $html);
    }

    public static function clean_html(string $html): string {
        $html = str_replace(
            [
                '/dsl-stoerungen-verstehen-und-beheben/',
                '/glasfaseranschluss-einfach-erklaert-der-grosse-ratgeber/',
                'https://glasfaser-kompass.de/author/',
                'Präsentiert von Astra-WordPress-Theme',
                'Proudly powered by Astra WordPress Theme',
            ],
            [
                '/dsl-stoerungen-verstehen/',
                '/glasfaseranschluss-erklaert/',
                self::AUTHOR_URL,
                '',
                '',
            ],
            $html
        );

        if (self::$is_legal) {
            $html = self::strip_dynamic_sections($html);
        }

        if (self::$slug === 'dslam-erklaert') {
            /* Ein älterer Renderer hängt diesen unvollständigen Block nach dem
               reparierten Artikel an und überspringt darin den KVz. */
            $html = (string) preg_replace(
                '~<h2\b[^>]*>\s*Technischer Signalweg bei VDSL\s*</h2>.*?Bei reinen FTTH-Glasfaseranschlüssen.*?</p>~is',
                '',
                $html,
                1
            );
        }

        if (in_array(self::$slug, ['gf-ap-erklaert', 'gf-ta-erklaert', 'ont-erklaert', 'router-im-keller', 'routerstandort-optimieren', 'ont-und-router-unterschied-premium', 'access-point-oder-repeater', 'mesh-wlan-erklaert', 'repeater-erklaert', '2-4-ghz-5-ghz-oder-6-ghz', 'wlan-kanal-wechseln', 'wifi-7-erklaert', 'repeater-richtig-platzieren', 'dsl-stoerung-systematisch-eingrenzen', 'dsl-synchronisiert-nicht', 'dsl-ausfall-bei-regen-die-haeufigsten-ursachen', 'endleitung-dsl-probleme', 'crc-fehler-erklaert-was-sie-ueber-eine-dsl-leitung-aussagen', 'fec-fehler-richtig-interpretieren', 'snr-stoerabstandsmarge-erklaert', 'was-prueft-ein-techniker-bei-einer-entstoerung', 'technikertermin-dsl-vorbereiten', 'warum-wird-an-der-ersten-tae-gemessen'], true)) {
            /* Diese Beiträge zeigen das kuratierte Bauteilbild bereits im
               Fachartikel. Das Theme-Featured-Image wäre exakt dieselbe Datei. */
            $html = (string) preg_replace(
                '~<div\b[^>]*class=(["\'])[^"\']*ast-single-post-featured-section[^"\']*\1[^>]*>.*?</div>~is',
                '',
                $html,
                1
            );
        }

        if (self::$is_front) {
            $html = (string) preg_replace(
                '~(<h1\b[^>]*>)\s*Startseite\s*(</h1>)~iu',
                '$1' . self::HOME_TITLE . '$2',
                $html,
                1
            );
            $html = str_replace(
                ['<title>Startseite - glasfaser-kompass.de</title>', '<title>Startseite – glasfaser-kompass.de</title>'],
                '<title>' . self::HOME_TITLE . ' – Glasfaser-Kompass</title>',
                $html
            );
        }

        $html = (string) preg_replace(
            "~<div class=([\\\"'])ast-footer-copyright\\1><p>.*?</p>\\s*</div>~is",
            '<div class="ast-footer-copyright"><p>Copyright © ' . wp_date('Y') . ' Glasfaser-Kompass</p></div>',
            $html,
            1
        );

        $social = self::social_image('');
        if ($social !== '') {
            $escaped = esc_url($social);
            $html = (string) preg_replace("~<meta\\b[^>]*(?:property|name)=([\\\"'])(?:og:image|twitter:image)\\1[^>]*>\\s*~is", '', $html);
            $html = str_replace('</head>', '<meta property="og:image" content="' . $escaped . '"><meta name="twitter:image" content="' . $escaped . '"></head>', $html);
        }
        $html = (string) preg_replace("~<meta\\b[^>]*name=([\\\"'])twitter:card\\1[^>]*>\\s*~is", '', $html);
        $html = str_replace('</head>', '<meta name="twitter:card" content="summary_large_image"></head>', $html);

        return $html;
    }
}

GK_Final_Frontend_Guard::boot();
