<?php
/**
 * Plugin Name: GK Final Frontend Guard
 * Description: Bereinigt dynamische Altlinks, Rechtsseiten-Blöcke, Autorenanzeige und Theme-Reste nach dem Rendern.
 * Version: 1.1.3
 * Author: IT Solutions – Kolja Seebauer
 * Requires at least: 6.4
 * Requires PHP: 8.0
 */
if (!defined('ABSPATH')) { exit; }

final class GK_Final_Frontend_Guard {
    private static bool $is_legal = false;
    private static bool $is_front = false;
    private static string $slug = '';
    private const AUTHOR_NAME = 'Kolja Seebauer';
    private const AUTHOR_URL  = 'https://glasfaser-kompass.de/ueber-den-autor/';
    private const HOME_TITLE  = 'Glasfaser, DSL, Router und WLAN aus der Praxis';

    public static function boot(): void {
        add_action('template_redirect', [self::class, 'start_buffer'], PHP_INT_MIN);
        add_filter('the_author', [self::class, 'author_name'], PHP_INT_MAX);
        add_filter('get_the_author_display_name', [self::class, 'author_name'], PHP_INT_MAX);
        add_filter('author_link', [self::class, 'author_link'], PHP_INT_MAX);
        add_filter('astra_footer_copyright', [self::class, 'footer'], PHP_INT_MAX);
        add_filter('rank_math/opengraph/facebook/image', [self::class, 'social_image'], PHP_INT_MAX);
        add_filter('rank_math/opengraph/twitter/image', [self::class, 'social_image'], PHP_INT_MAX);
        add_filter('rank_math/opengraph/twitter/card_type', static fn() => 'summary_large_image', PHP_INT_MAX);
        add_action('wp_head', [self::class, 'legal_visibility_guard'], PHP_INT_MAX);
        add_action('wp', [self::class, 'install_content_repairs'], PHP_INT_MAX);
    }

    public static function install_content_repairs(): void {
        if (is_admin() || wp_doing_ajax() || wp_is_json_request() || !is_singular()) { return; }
        /* Registered on wp, after normal plugin bootstrap. This makes the repair
           filter run after GK Render Guard even when both use PHP_INT_MAX. */
        add_filter('the_content', [self::class, 'repair_content'], PHP_INT_MAX);
    }

    private static function photo(string $file, string $alt, string $caption): string {
        $url = home_url('/wp-content/plugins/gk-render-guard/assets/' . $file);
        return '<figure class="gk-topic-photo"><img src="' . esc_url($url) . '" alt="' . esc_attr($alt) . '" loading="lazy"><figcaption>' . esc_html($caption) . '</figcaption></figure>';
    }

    private static function sources(): string {
        return '<h2>Offizielle Quellen</h2><ul><li><a href="https://www.bundesnetzagentur.de/DE/Vportal/TK/InternetTelefon/Internetgeschwindigkeit/start.html">Bundesnetzagentur: Internetzugang und Geschwindigkeit</a></li><li><a href="https://www.telekom.de/hilfe/internet-telefonie/internet">Deutsche Telekom: Hilfe zu Internet und Anschluss</a></li></ul>';
    }

    private static function fiber_sources(): string {
        return '<h2>Offizielle Quellen</h2><ul><li><a href="https://www.telekom.de/hilfe/internet-telefonie/internet/glasfaser">Deutsche Telekom: Hilfe zum Glasfaseranschluss</a></li><li><a href="https://www.bundesnetzagentur.de/DE/Vportal/TK/InternetTelefon/Internetgeschwindigkeit/start.html">Bundesnetzagentur: Internetzugang und Geschwindigkeit</a></li></ul>';
    }

    private static function router_sources(): string {
        return '<h2>Offizielle Quellen</h2><ul><li><a href="https://www.telekom.de/hilfe/geraete/router">Deutsche Telekom: Router und Gerätehilfe</a></li><li><a href="https://www.bundesnetzagentur.de/DE/Vportal/TK/InternetTelefon/Internetgeschwindigkeit/start.html">Bundesnetzagentur: Internetzugang und Geschwindigkeit</a></li></ul>';
    }

    public static function repair_content(string $content): string {
        if (!is_singular() || !in_the_loop() || !is_main_query()) { return $content; }
        $slug = (string) get_post_field('post_name', get_queried_object_id());
        $articles = self::repair_articles();
        return isset($articles[$slug]) ? $articles[$slug] : $content;
    }

    private static function repair_articles(): array {
        $sources = self::sources();
        $fiber_sources = self::fiber_sources();
        $router_sources = self::router_sources();
        return [
            'dsl-bauteile-im-haus' => '<article class="gk-clean-article"><h2>DSL-Bauteile im Haus eindeutig erkennen</h2>'
                . self::photo('apl.png', 'Geöffneter Kupfer-APL mit Mehraderkabel und Anschlussklemmen.', 'APL: passiver Abschluss des Betreiber-Kupfernetzes am Gebäude.')
                . self::photo('tae-dose.jpg', 'Weiße TAE-NFF-Anschlussdose mit drei Buchsen.', 'Erste TAE: Anschluss- und Messpunkt in den Kundenräumen. Foto: Uwe Schwöbel, GNU FDL 1.2, via Wikimedia Commons.')
                . '<h2>Der korrekte Signalweg</h2><p><strong>MFG mit DSLAM/MSAN → KVz → Kupfer-Zugangsnetz → APL → Endleitung → erste TAE → DSL-Router</strong></p><h3>APL</h3><p>Der APL beendet das öffentliche Kupfer-Zugangsnetz am Gebäude. Mehraderkabel, Doppeladern und Anschlussklemmen unterscheiden ihn von einem Glasfaser-Gf-AP und einem Koax-HÜP.</p><h3>Endleitung</h3><p>Die Endleitung ist das Kupfer-Adernpaar zwischen APL und erster TAE. Abzweigungen, lose Klemmstellen und parallel geschaltete Dosen können DSL-Werte verschlechtern.</p><h3>Erste TAE und Router</h3><p>Die erste TAE ist der reguläre Anschluss- und Messpunkt. Das DSL-Modem im Router synchronisiert sich mit dem DSLAM/MSAN. Erst danach werden LAN und WLAN getrennt beurteilt.</p><h2>Vor einem Technikertermin</h2><ul><li>APL und erste TAE zugänglich machen.</li><li>Router, Netzteil und DSL-Kabel bereithalten.</li><li>Weitere Dosen und Abzweigungen nennen.</li><li>APL nicht selbst öffnen oder umklemmen.</li></ul>' . $sources . '</article>',
            'dslam-erklaert' => '<article class="gk-clean-article">' . self::photo('mfg.png', 'Graues Multifunktionsgehäuse am Straßenrand.', 'Bei FTTC/VDSL befindet sich die aktive DSLAM-/MSAN-Technik typischerweise im grauen MFG.') . '<h2>Was macht ein DSLAM oder MSAN?</h2><p>Der DSLAM stellt DSL-Verbindungen für viele Teilnehmer bereit. Bei FTTC/VDSL sitzt diese aktive Technik typischerweise <strong>im Multifunktionsgehäuse</strong>. Das MFG ist das Gehäuse und keine zusätzliche Signalstufe.</p><h2>Der korrekte FTTC-/VDSL-Signalweg</h2><p><strong>Glasfaserzuführung → MFG mit DSLAM/MSAN → KVz → Kupfer-Zugangsnetz → APL → Endleitung → erste TAE → DSL-Router</strong></p><p>Der KVz ist ein eigener passiver Kabelverzweiger. MFG und KVz sind üblicherweise graue Straßengehäuse.</p><h2>Abgrenzung zu FTTH</h2><p>Bei FTTH gibt es auf der Teilnehmerstrecke keinen DSLAM. Dort sind OLT, passives Glasfasernetz, Gf-AP, Gf-TA und gegebenenfalls ONT relevant.</p>' . $sources . '</article>',
            'dsl-stoerungen-verstehen' => '<article class="gk-clean-article">' . self::photo('apl.png', 'Geöffneter Kupfer-APL mit Mehraderkabel und Anschlussklemmen.', 'Bei DSL führt die Gebäudediagnose vom Kupfer-APL über Endleitung und erste TAE zum Router.') . '<h2>DSL-Störungen systematisch eingrenzen</h2><ol><li><strong>Synchronisation prüfen:</strong> Ohne DSL-Synchronisation liegt der Fehler vor der Internet-Einwahl.</li><li><strong>Routerwerte sichern:</strong> Datenrate, Störabstand, Dämpfung und Fehlerzähler notieren.</li><li><strong>APL und erste TAE vergleichen:</strong> Schlechtere Werte an der TAE sprechen häufig für Endleitung, Klemmstelle oder Dose.</li><li><strong>LAN vor WLAN testen:</strong> Das Heimnetz erst nach stabiler DSL-Verbindung beurteilen.</li></ol><h2>Typische Einordnung</h2><table><thead><tr><th>Beobachtung</th><th>Zu prüfender Bereich</th></tr></thead><tbody><tr><td>Keine Synchronisation</td><td>Port, Kupfernetz, APL, Endleitung, TAE oder DSL-Kabel</td></tr><tr><td>Abbrüche bei Regen</td><td>Feuchtigkeit an Muffe, Kabel, APL oder Klemmstelle</td></tr><tr><td>Am APL gut, an der TAE schlecht</td><td>Endleitung, Abzweigung oder TAE</td></tr><tr><td>LAN stabil, WLAN langsam</td><td>Routerstandort, Funkkanal und Heimnetz</td></tr></tbody></table><p>Ein Speedtest allein trennt Anschlussfehler nicht von WLAN-, LAN- oder Endgeräteproblemen.</p>' . $sources . '</article>',
            'tae-erklaert' => '<article class="gk-clean-article">' . self::photo('tae-dose.jpg', 'Weiße TAE-NFF-Anschlussdose mit drei Buchsen.', 'TAE-Dose: Anschluss- und Messpunkt eines kupferbasierten Telefon- oder DSL-Anschlusses. Foto: Uwe Schwöbel, GNU FDL 1.2, via Wikimedia Commons.') . '<h2>Was ist eine TAE?</h2><p>Die Telekommunikations-Anschluss-Einheit ist eine Anschlussdose für kupferbasierte Telefon- und DSL-Anschlüsse. Die erste TAE liegt hinter APL und Endleitung. Gf-AP, Gf-TA und ONT gehören dagegen zu Glasfaseranschlüssen.</p><h2>Warum ist die erste TAE wichtig?</h2><p>Der Vergleich einer Messung am APL mit der Messung an der ersten TAE zeigt, ob Endleitung oder Dose die DSL-Verbindung verschlechtern.</p><h2>Typische Fehler</h2><ul><li>lose oder korrodierte Kontakte</li><li>parallel angeschlossene weitere Dosen</li><li>unnötige Verlängerungen und Abzweigungen</li><li>beschädigte Anschlussleitung zum Router</li></ul><p>Dose freiräumen, DSL-Kabel kontrollieren und Routerwerte dokumentieren. Feste Leitungen nicht eigenmächtig umklemmen.</p>' . $sources . '</article>',
            'warum-misst-der-techniker-am-apl' => '<article class="gk-clean-article">' . self::photo('apl.png', 'Geöffneter Kupfer-APL mit Mehraderkabel und Anschlussklemmen.', 'APL: Messpunkt zur Trennung von Betreiber-Kupfernetz und gebäudeseitiger Endleitung.') . '<h2>Warum wird am APL gemessen?</h2><p>Die Messung am APL trennt das Betreiber-Kupfernetz von der gebäudeseitigen Endleitung. Sie zeigt, ob das DSL-Signal bereits am Hausanschluss fehlerhaft ankommt oder erst zwischen APL und erster TAE schlechter wird.</p><h2>Messvergleich in der Praxis</h2><table><thead><tr><th>Ergebnis</th><th>Einordnung</th></tr></thead><tbody><tr><td>APL und erste TAE ähnlich</td><td>Endleitung verursacht wahrscheinlich keinen großen zusätzlichen Verlust.</td></tr><tr><td>APL deutlich besser als erste TAE</td><td>Endleitung, Klemmstelle, Abzweigung oder TAE prüfen.</td></tr><tr><td>Bereits am APL auffällig</td><td>Fehler im Betreiber-Kupfernetz oder am Port weiter eingrenzen.</td></tr></tbody></table><p>Ein WLAN-Speedtest ersetzt diesen Messvergleich nicht. APL und erste TAE sollten vor dem Termin zugänglich sein; den APL nicht selbst öffnen.</p>' . $sources . '</article>',
            'ftth-anschlussarten-erklaert' => '<article class="gk-clean-article">' . self::photo('glasfaser.png', 'Aufgebautes Glasfaserkabel mit Außenmantel, Zugentlastung und einzelner Faser.', 'Glasfaserkabel transportieren Daten optisch; entscheidend ist, wie weit die Faser bis zum Nutzer geführt wird.') . '<h2>FTTH, FTTB und FTTC eindeutig unterscheiden</h2><table><thead><tr><th>Ausbauart</th><th>Glasfaser endet</th><th>Letzter Abschnitt</th></tr></thead><tbody><tr><td>FTTH</td><td>im Haus oder in der Wohnung</td><td>Glasfaser bis Gf-TA beziehungsweise ONT</td></tr><tr><td>FTTB</td><td>im Gebäude</td><td>gebäudeinterne Weiterführung nach Ausbaukonzept</td></tr><tr><td>FTTC</td><td>am Straßenverteiler</td><td>Kupfer vom MFG/KVz bis APL und TAE</td></tr></tbody></table><h2>Warum die Unterscheidung wichtig ist</h2><p>Nur bei FTTH reicht die Glasfaser bis in den Teilnehmerbereich. Ein Koaxialkabel ist weder eine DSL-Endleitung noch ein FTTH-Glasfaserkabel. Bei FTTC bleiben APL, Endleitung und TAE relevant; bei FTTH dagegen Gf-AP, Gf-TA und gegebenenfalls ONT.</p><h2>Praxisprüfung</h2><ul><li>Vertragliche Ausbauart nicht mit der beworbenen Tarifgeschwindigkeit verwechseln.</li><li>Ankommende Leitung und Netzabschluss identifizieren.</li><li>Routeranschluss prüfen: DSL-Port, Ethernet-WAN hinter ONT oder direkter Glasfaserport.</li></ul>' . $sources . '</article>',
            'gf-ap-erklaert' => '<article class="gk-clean-article">' . self::photo('gf-ap.png', 'Geöffneter Gf-AP mit Faserführung und Spleißablage.', 'Gf-AP: passiver Gebäudeabschluss des Glasfasernetzes.') . '<h2>Was ist ein Gf-AP?</h2><p>Der Glasfaser-Abschlusspunkt ist der passive Abschluss der ankommenden Glasfaser am Gebäude. Er enthält Faserführung, Spleißablage und je nach Ausbau Kupplungen oder vorbereitete Abgänge. Er ist kein Router und benötigt für seine passive Funktion keinen Strom.</p><h2>So lässt er sich einordnen</h2><ul><li><strong>Gf-AP:</strong> Gebäudeabschluss der Glasfaser.</li><li><strong>Gf-TA:</strong> optische Teilnehmeranschlussdose in Haus oder Wohnung.</li><li><strong>ONT:</strong> aktives Gerät zur Umsetzung des optischen Signals auf Ethernet.</li><li><strong>APL:</strong> Gebäudeabschluss des Kupfernetzes für Telefonie und DSL.</li></ul><h2>Montage und Zugang</h2><p>Der Gf-AP liegt häufig im Hausanschluss- oder Technikraum nahe der Gebäudeeinführung. Leitungsweg, Biegeradien und Zugang müssen vor der Montage geklärt sein. Das Gehäuse nicht eigenmächtig öffnen oder Fasern bewegen.</p>' . $sources . '</article>',
            'gf-ta-erklaert' => '<article class="gk-clean-article">' . self::photo('gf-ta.png', 'Glasfaser-Teilnehmeranschlussdose mit optischer Buchse.', 'Gf-TA: passiver optischer Anschluss in Haus oder Wohnung.') . '<h2>Was ist eine Gf-TA?</h2><p>Die Glasfaser-Teilnehmeranschlussdose stellt den passiven optischen Anschluss im Nutzungsbereich bereit. Sie liegt im Signalweg hinter dem Gf-AP und vor ONT oder Glasfaserrouter. Sie ist keine TAE-Dose und wandelt das Signal nicht elektrisch um.</p><h2>Typischer Signalweg</h2><p><strong>Gf-AP → gebäudeinterne Glasfaser → Gf-TA → optisches Patchkabel → ONT oder Glasfaserrouter</strong></p><h2>Praxis</h2><ul><li>Stecker und Buchse müssen zum Anschlusskonzept passen.</li><li>Schutzkappen erst unmittelbar vor dem Verbinden entfernen.</li><li>Faser nicht knicken, quetschen oder an verschmutzten Steckflächen berühren.</li><li>Standort so wählen, dass ONT, Router und Stromversorgung sinnvoll erreichbar sind.</li></ul>' . $sources . '</article>',
            'glasfaser-bauteile-im-haus' => '<article class="gk-clean-article"><h2>Glasfaser-Bauteile im Haus erkennen</h2><div class="gk-compare-photos">' . self::photo('gf-ap.png', 'Geöffneter Gf-AP mit Faserführung und Spleißablage.', 'Gf-AP: passiver Gebäudeabschluss.') . self::photo('gf-ta.png', 'Glasfaser-Teilnehmeranschlussdose mit optischer Buchse.', 'Gf-TA: optischer Anschluss im Nutzungsbereich.') . self::photo('ont.png', 'ONT mit optischem Eingang, Ethernet-Ausgang und Stromversorgung.', 'ONT: aktiver Übergang von Glasfaser zu Ethernet.') . '</div><h2>Der typische FTTH-Signalweg im Haus</h2><p><strong>Gf-AP → gebäudeinterne Glasfaser → Gf-TA → ONT oder Glasfaserrouter → LAN/WLAN</strong></p><h2>Aufgaben klar trennen</h2><p>Gf-AP und Gf-TA sind passive optische Abschlusspunkte. Ein ONT benötigt Strom und stellt Ethernet bereit. Der Router baut die Internetverbindung nach Anbietervorgabe auf und verteilt sie im Heimnetz.</p><h2>Häufige Verwechslungen</h2><ul><li>Ein Kupfer-APL besitzt Doppeladern und Klemmen, keine Glasfaser-Spleißablage.</li><li>Ein Koax-HÜP besitzt Koaxialkabel mit Innenleiter und Schirmung.</li><li>Der ONT ist nicht automatisch der WLAN-Router.</li></ul>' . $sources . '</article>',
            'speedpipe-erklaert' => '<article class="gk-clean-article">' . self::photo('speedpipe.png', 'Verband aus farbigen Mikrorohren für Glasfaserkabel.', 'Speedpipes sind Schutz- und Führungsrohre; sie übertragen selbst kein Signal.') . '<h2>Was ist eine Speedpipe?</h2><p>Speedpipe ist eine gebräuchliche Bezeichnung für ein Mikrorohr, in das ein dafür vorgesehenes Glasfaserkabel eingeblasen wird. Das Rohr schützt und führt das Kabel, enthält aber nicht automatisch bereits eine Faser.</p><h2>Vom Rohr zur nutzbaren Verbindung</h2><ol><li>Mikrorohrverband verlegen und dokumentieren.</li><li>Durchgängigkeit und Dichtheit prüfen.</li><li>Einblaskabel mit geeigneter Technik einbringen.</li><li>Fasern an Muffe, NVT oder Gf-AP spleißen und messen.</li></ol><h2>Typische Fehler</h2><ul><li>zu enge Biegeradien oder gequetschte Rohre</li><li>undichte Kupplungen und eindringende Feuchtigkeit</li><li>verschmutzte oder nicht verschlossene Rohrenden</li><li>nicht dokumentierte Rohrbelegung</li></ul>' . $sources . '</article>',
            'ont-erklaert' => '<article class="gk-clean-article">' . self::photo('ont.png', 'ONT mit optischem Eingang, Ethernet-Ausgang und Stromversorgung.', 'ONT: aktiver Netzabschluss zwischen optischem Anschluss und Ethernet.') . '<h2>Was macht ein ONT?</h2><p>Das Optical Network Terminal beendet die optische Teilnehmerverbindung und stellt auf der Kundenseite Ethernet bereit. Es benötigt Strom. Der ONT ist nicht automatisch ein Router und erzeugt nicht zwingend WLAN.</p><h2>Typischer Anschluss</h2><p><strong>Gf-TA → optisches Patchkabel → ONT → Ethernetkabel → WAN-Port des Routers</strong></p><p>Das Ethernetkabel gehört an den vom Hersteller vorgesehenen WAN-Port, nicht an einen DSL-Port. Anbieter können Registrierung, VLAN oder Zugangsdaten vorgeben.</p><h2>Status und Fehlersuche</h2><ul><li>Stromversorgung und Statusanzeigen prüfen.</li><li>Optisches Patchkabel nicht knicken und Steckflächen nicht berühren.</li><li>Ethernet-Link zwischen ONT und Router kontrollieren.</li><li>LAN-Test durchführen, bevor WLAN bewertet wird.</li></ul>' . $sources . '</article>',
            'ont-erklaert-einfach-erklaert' => '<article class="gk-clean-article">' . self::photo('ont.png', 'ONT mit optischem Eingang, Ethernet-Ausgang und Stromversorgung.', 'ONT: wandelt den optischen Teilnehmeranschluss in eine Ethernet-Schnittstelle für den Router um.') . '<h2>ONT kurz erklärt</h2><p>Ein ONT ist das aktive Abschlussgerät einer FTTH-Verbindung. Es setzt die optische Verbindung auf eine Ethernet-Schnittstelle um. Die Formulierung „wandelt Licht in Internet“ ist verkürzt: Zugangsdaten, Routerfunktion und Heimnetz bleiben eigenständige Aufgaben.</p><h2>ONT und Router unterscheiden</h2><table><thead><tr><th>Gerät</th><th>Aufgabe</th></tr></thead><tbody><tr><td>ONT</td><td>optische Teilnehmerverbindung abschließen und Ethernet bereitstellen</td></tr><tr><td>Router</td><td>Internetverbindung aufbauen, routen, Firewall sowie LAN/WLAN bereitstellen</td></tr></tbody></table><h2>Richtig verbinden</h2><p><strong>Gf-TA → ONT → WAN-Port des Routers.</strong> Das DSL-Modem eines Kombirouters wird hinter dem ONT nicht verwendet. Maßgeblich bleiben die Vorgaben des Anbieters.</p>' . $sources . '</article>',
            'glasfaser-spleissen-erklaert' => '<article class="gk-clean-article">' . self::photo('spleissstelle.png', 'Geschützte Glasfaser-Spleißstelle in einer Spleißkassette.', 'Fusionsspleiß: dauerhaft verbundene Fasern mit Spleißschutz in geordneter Ablage.') . '<h2>Was bedeutet Spleißen?</h2><p>Beim Fusionsspleißen werden zwei vorbereitete Glasfasern präzise ausgerichtet und mit einem Lichtbogen dauerhaft verbunden. Danach schützt eine Spleißschutzhülse die Verbindungsstelle.</p><h2>Arbeitsablauf</h2><ol><li>Faser absetzen und Beschichtung entfernen.</li><li>Faser reinigen und mit einem Cleaver rechtwinklig brechen.</li><li>Fasern im Spleißgerät ausrichten und verbinden.</li><li>Dämpfung beziehungsweise Spleißqualität bewerten.</li><li>Spleiß schützen und ohne enge Biegung in der Kassette ablegen.</li></ol><h2>Warum Fachpersonal nötig ist</h2><p>Verschmutzung, schlechter Faserbruch, ungeeignete Parameter oder falsche Ablage erhöhen die Dämpfung und können spätere Ausfälle verursachen. Offene Fasern und Laserstrahlung erfordern geeignete Arbeits- und Schutzregeln.</p>' . $sources . '</article>',
            'lc-stecker-erklaert' => '<article class="gk-clean-article">' . self::photo('steckverbinder.png', 'LC/UPC- und SC/APC-Glasfasersteckverbinder im Vergleich.', 'LC ist eine kompakte Steckverbinderbauform; Schliffart und Kupplung müssen zum Anschluss passen.') . '<h2>Was ist ein LC-Stecker?</h2><p>LC ist eine kompakte Glasfaser-Steckverbinderbauform mit 1,25-Millimeter-Ferrule und Rastmechanik. Die Bauform allein sagt noch nichts über Faserart oder Schliff aus.</p><h2>UPC und APC nicht verwechseln</h2><p>UPC- und APC-Schliffe besitzen unterschiedliche Stirnflächen. APC ist schräg geschliffen und häufig grün gekennzeichnet. Unpassende Schliffe dürfen nicht miteinander verbunden werden, auch wenn mechanisch ähnliche Adapter vorhanden sind.</p><h2>Praxisregeln</h2><ul><li>Stecker nur an gereinigte und passende Kupplungen anschließen.</li><li>Schutzkappen sauber halten.</li><li>Steckfläche vor dem Verbinden prüfen und fachgerecht reinigen.</li><li>Patchkabel nicht knicken, ziehen oder unter Spannung verlegen.</li></ul>' . $sources . '</article>',
            'router-im-keller' => '<article class="gk-clean-article">' . self::photo('wlan-heimnetz.png', 'Haus mit Router, LAN-Verbindungen und WLAN-Versorgung.', 'Ein zentraler Router oder kabelgebundener Access Point versorgt Wohnbereiche zuverlässiger als ein Router im Keller.') . '<h2>Warum der Keller für WLAN ungünstig ist</h2><p>Kellerdecken, Stahlbeton, Metall, Leitungen und große Wasserflächen schwächen das Funksignal. Das Problem entsteht nicht durch den APL oder die Kupferleitung, sondern durch den Funkweg zwischen Router und Endgerät.</p><h2>Die technisch saubere Lösung</h2><ol><li>Internetanschluss per LAN direkt am Router prüfen.</li><li>Netzwerkkabel vom Keller in einen zentralen Wohnbereich führen.</li><li>Dort Access Point oder Mesh-Knoten mit LAN-Backhaul betreiben.</li><li>Erst danach zusätzliche Funkknoten planen.</li></ol><h2>Wenn kein LAN-Kabel vorhanden ist</h2><p>Ein Repeater muss noch ein gutes Signal vom Router empfangen. Er gehört nicht in das Funkloch. Eine Platzierung im Treppenhaus oder auf halber Strecke ist meist besser.</p>' . $sources . '</article>',
            'routerstandort-optimieren' => '<article class="gk-clean-article">' . self::photo('wlan-heimnetz.png', 'Zentral platzierter Router mit kabelgebundenen und drahtlosen Endgeräten.', 'Router frei, erhöht und möglichst zentral aufstellen.') . '<h2>Der beste Routerstandort</h2><p>Der Router sollte frei, erhöht und möglichst zentral zu den genutzten Räumen stehen. Schränke, Heizungsräume, Metallflächen, Aquarien und massive Decken verschlechtern die Funkabdeckung.</p><h2>Standort systematisch prüfen</h2><ul><li>LAN-Messung direkt am Router als Referenz durchführen.</li><li>Signal und Datenrate an typischen Nutzungsorten messen.</li><li>Router versuchsweise höher und freier positionieren.</li><li>2,4 und 5 GHz getrennt bewerten.</li><li>Für weitere Etagen LAN-Backhaul bevorzugen.</li></ul><h2>Anschlussart und Standort trennen</h2><p>Bei DSL begrenzt die erste TAE den möglichen Routerstandort; bei FTTH häufig Gf-TA oder ONT. Ein längeres geeignetes Anschluss- oder Netzwerkkabel kann sinnvoller sein als ein Funk-Repeater.</p>' . $sources . '</article>',
            'ont-und-router-unterschied-premium' => '<article class="gk-clean-article">' . self::photo('ont.png', 'ONT mit optischem Eingang, Ethernet-Ausgang und Stromversorgung.', 'Der ONT beendet die optische Verbindung; der Router übernimmt Internetzugang und Heimnetz.') . '<h2>ONT und Router haben verschiedene Aufgaben</h2><table><thead><tr><th>Gerät</th><th>Aufgabe</th></tr></thead><tbody><tr><td>ONT</td><td>optische Teilnehmerverbindung abschließen und Ethernet bereitstellen</td></tr><tr><td>Router</td><td>Internetverbindung, Routing, Firewall, LAN und WLAN bereitstellen</td></tr></tbody></table><h2>Richtig anschließen</h2><p><strong>Gf-TA → optisches Patchkabel → ONT → Ethernetkabel → WAN-Port des Routers.</strong> Der DSL-Port eines Kombirouters bleibt hinter dem ONT unbenutzt.</p><h2>Fehler getrennt eingrenzen</h2><ul><li>Optischen Status und Stromversorgung des ONT prüfen.</li><li>Ethernet-Link zwischen ONT und Router kontrollieren.</li><li>Internetzugang per LAN am Router testen.</li><li>WLAN erst danach beurteilen.</li></ul>' . $sources . '</article>',
            'access-point-oder-repeater' => '<article class="gk-clean-article">' . self::photo('mesh.png', 'Router und zusätzliche WLAN-Zugangspunkte in einem Haus.', 'Kabelgebundener Access Point und Funk-Repeater erfüllen unterschiedliche Aufgaben.') . '<h2>Der entscheidende Unterschied</h2><table><thead><tr><th>Lösung</th><th>Uplink</th><th>Typische Stärke</th></tr></thead><tbody><tr><td>Access Point</td><td>LAN-Kabel</td><td>stabile Datenrate und geringe Latenz</td></tr><tr><td>Repeater</td><td>WLAN</td><td>schnelle Nachrüstung ohne Kabel</td></tr><tr><td>Mesh-Knoten</td><td>WLAN oder LAN</td><td>gemeinsame Steuerung und Roaming-Funktionen</td></tr></tbody></table><h2>Wann welche Lösung?</h2><p>Ist ein Netzwerkkabel vorhanden, ist ein Access Point meist die belastbarere Lösung. Ein Repeater eignet sich für einzelne Funklöcher, sofern er am Montageort noch ein starkes Signal empfängt. Für mehrere Etagen ist ein Mesh mit LAN-Backhaul vorzuziehen.</p><h2>Vor dem Kauf</h2><p>Vorhandene Verkabelung, benötigte LAN-Ports, Stromversorgung, Herstellerkompatibilität und gewünschte WLAN-Standards prüfen.</p>' . $sources . '</article>',
            'mesh-wlan-erklaert' => '<article class="gk-clean-article">' . self::photo('mesh.png', 'Mesh-System mit Router und mehreren Zugangspunkten.', 'Mesh koordiniert mehrere WLAN-Zugangspunkte; ein guter Uplink bleibt entscheidend.') . '<h2>Was bedeutet Mesh-WLAN?</h2><p>Ein Mesh-System verwaltet mehrere Zugangspunkte gemeinsam. Einheitliche Konfiguration, Bandsteuerung und Roaming-Hilfen können Endgeräte beim Wechsel unterstützen. Mesh ersetzt jedoch keinen leistungsfähigen Uplink.</p><h2>Funk- oder LAN-Backhaul</h2><p>Bei Funk-Backhaul teilen sich Nutzdaten und Verbindung der Knoten die verfügbare Funkkapazität. LAN-Backhaul verbindet die Knoten kabelgebunden und ist meist stabiler.</p><h2>Richtig planen</h2><ul><li>Knoten nicht im Funkloch aufstellen.</li><li>Pro Etage zuerst einen geeigneten Standort testen.</li><li>LAN-Backhaul nutzen, wo Kabel vorhanden sind.</li><li>Nach Änderungen Roaming und Durchsatz an realen Endgeräten prüfen.</li></ul>' . $sources . '</article>',
            'repeater-erklaert' => '<article class="gk-clean-article">' . self::photo('mesh.png', 'WLAN-Router und zusätzlicher Funkknoten.', 'Ein Repeater erweitert ein vorhandenes WLAN nur dort sinnvoll, wo er selbst guten Empfang hat.') . '<h2>Was macht ein WLAN-Repeater?</h2><p>Ein Repeater empfängt ein vorhandenes WLAN und sendet es weiter. Er repariert keine langsame Internetleitung und kann nur die Funkverbindung erweitern, die an seinem Standort ankommt.</p><h2>Grenzen</h2><p>Bei ungünstigem Funk-Uplink sinken nutzbare Datenrate und Stabilität. Wände und Decken wirken auf die Verbindung Router–Repeater ebenso wie auf die Verbindung Repeater–Endgerät.</p><h2>Alternativen</h2><p>Ein kabelgebundener Access Point oder ein Mesh-Knoten mit LAN-Backhaul ist für Homeoffice, mehrere Etagen und hohe konstante Datenraten meist besser geeignet.</p>' . $sources . '</article>',
            '2-4-ghz-5-ghz-oder-6-ghz' => '<article class="gk-clean-article">' . self::photo('wlan-heimnetz.png', 'Heimnetz mit WLAN-Geräten in unterschiedlichen Entfernungen.', 'Das passende Frequenzband hängt von Entfernung, Wänden und Endgeräteunterstützung ab.') . '<h2>Die drei WLAN-Bänder im Vergleich</h2><table><thead><tr><th>Band</th><th>Stärke</th><th>Grenze</th></tr></thead><tbody><tr><td>2,4 GHz</td><td>größere Reichweite und breite Geräteunterstützung</td><td>wenige überlappungsfreie Kanäle und oft stark belegt</td></tr><tr><td>5 GHz</td><td>mehr Bandbreite und mehr Kanäle</td><td>geringere Reichweite durch Bauteile</td></tr><tr><td>6 GHz</td><td>zusätzliches Spektrum für kompatible Geräte</td><td>kurze Reichweite und neue Hardware erforderlich</td></tr></tbody></table><h2>Praxisempfehlung</h2><p>2,4 GHz eignet sich häufig für entfernte oder einfache Geräte. 5 GHz ist in Routernähe meist die beste Kombination aus Tempo und Reichweite. 6 GHz lohnt sich für kompatible Geräte bei kurzem Funkweg. Automatische Bandsteuerung kann sinnvoll sein, muss aber mit den realen Endgeräten geprüft werden.</p>' . $sources . '</article>',
            'wlan-kanal-wechseln' => '<article class="gk-clean-article">' . self::photo('wlan-heimnetz.png', 'WLAN-Router und Endgeräte im Heimnetz.', 'Ein Kanalwechsel hilft nur, wenn tatsächlich Kanalbelegung oder Störungen die Ursache sind.') . '<h2>Wann ein Kanalwechsel sinnvoll ist</h2><p>Ein manueller Kanalwechsel kann helfen, wenn mehrere benachbarte WLANs denselben oder überlappende Kanäle stark nutzen. Er hilft nicht gegen einen schlechten Routerstandort, massive Wände oder einen Repeater im Funkloch.</p><h2>Vorgehen</h2><ol><li>LAN-Verbindung als Referenz prüfen.</li><li>Belegung am betroffenen Ort zu mehreren Zeiten messen.</li><li>Automatische Kanalwahl dokumentieren.</li><li>Nur bei nachvollziehbarer Belegung einen geeigneten Kanal testen.</li><li>Durchsatz und Stabilität danach erneut messen.</li></ol><h2>2,4 GHz besonders beachten</h2><p>Bei 20-MHz-Kanalbreite werden in Europa häufig 1, 5, 9 und 13 als überlappungsarme Planung verwendet; verbreitet ist auch die 1/6/11-Planung. Entscheidend ist die lokale Belegung und Gerätekompatibilität, nicht eine pauschale Kanalnummer.</p>' . $sources . '</article>',
            'wifi-7-erklaert' => '<article class="gk-clean-article">' . self::photo('wlan-heimnetz.png', 'Modernes Heimnetz mit WLAN- und LAN-Geräten.', 'Wi-Fi 7 verbessert Funkkapazität und Latenz, ersetzt aber keine gute Netzplanung.') . '<h2>Was bringt Wi-Fi 7?</h2><p>Wi-Fi 7 basiert auf IEEE 802.11be. Zu den Neuerungen gehören breitere Kanäle im 6-GHz-Band, 4096-QAM und Multi-Link Operation. Welche Funktionen nutzbar sind, hängt von Router, Endgerät, Region und Funkumgebung ab.</p><h2>Wann lohnt sich der Umstieg?</h2><p>Ein Umstieg lohnt sich vor allem bei kompatiblen Endgeräten, hoher lokaler Datenlast, schnellen NAS-Verbindungen oder wenn ohnehin neue Hardware benötigt wird. Ein stabiles Wi-Fi-6-Netz muss nicht allein wegen der höheren theoretischen Datenrate ersetzt werden.</p><h2>Realistische Grenzen</h2><ul><li>Wände, Entfernung und Störungen bleiben wirksam.</li><li>Internettempo ist durch Tarif und Anschluss begrenzt.</li><li>Für konstante niedrige Latenz bleibt LAN die Referenz.</li></ul>' . $sources . '</article>',
            'repeater-richtig-platzieren' => '<article class="gk-clean-article">' . self::photo('mesh.png', 'Router und zusätzlicher WLAN-Knoten auf halber Strecke zum Zielbereich.', 'Der Repeater gehört in den Bereich mit noch gutem Router-Signal, nicht in das Funkloch.') . '<h2>Die wichtigste Platzierungsregel</h2><p>Der Repeater muss den Router noch zuverlässig empfangen. Ein Standort direkt im schlecht versorgten Raum wiederholt nur eine bereits schwache Verbindung.</p><h2>Schrittweise platzieren</h2><ol><li>Zielbereich ohne Repeater messen.</li><li>Repeater zunächst ungefähr auf halber Strecke aufstellen.</li><li>Signalqualität des Uplinks kontrollieren.</li><li>Durchsatz und Stabilität im Zielraum testen.</li><li>Standort in kleinen Schritten optimieren.</li></ol><h2>Typische Hindernisse</h2><p>Stahlbetondecken, Metall, Fußbodenheizung, Spiegel und Wasserflächen können den Funkweg stark beeinträchtigen. Bei mehreren Etagen ist LAN-Backhaul oder ein kabelgebundener Access Point häufig die bessere Lösung.</p>' . $sources . '</article>',
            'dsl-stoerung-systematisch-eingrenzen' => '<article class="gk-clean-article">' . self::photo('apl.png', 'Geöffneter Kupfer-APL mit Mehraderkabel und Anschlussklemmen.', 'Bei einer DSL-Störung werden Betreiberstrecke, Endleitung und Heimnetz getrennt geprüft.') . '<h2>DSL-Störung in der richtigen Reihenfolge prüfen</h2><ol><li><strong>Synchronisation:</strong> Zeigt der Router eine DSL-Verbindung zum DSLAM/MSAN?</li><li><strong>Leitungswerte:</strong> Datenrate, Störabstand, Dämpfung sowie CRC- und FEC-Zähler dokumentieren.</li><li><strong>Messpunkte:</strong> Werte an erster TAE und bei Bedarf am APL vergleichen.</li><li><strong>Internetzugang:</strong> Erst nach stabiler Synchronisation Einwahl und Anbieterzugang prüfen.</li><li><strong>Heimnetz:</strong> LAN als Referenz testen und WLAN anschließend getrennt bewerten.</li></ol><h2>Beobachtung richtig zuordnen</h2><table><thead><tr><th>Beobachtung</th><th>Zu prüfender Bereich</th></tr></thead><tbody><tr><td>Keine DSL-Synchronisation</td><td>Port, Kupfer-Zugangsnetz, APL, Endleitung, TAE oder DSL-Kabel</td></tr><tr><td>APL gut, erste TAE schlechter</td><td>Endleitung, Abzweigung, Klemmstelle oder TAE</td></tr><tr><td>DSL stabil, LAN langsam</td><td>Einwahl, Tarif, Router, Ethernet oder Endgerät</td></tr><tr><td>LAN gut, WLAN langsam</td><td>Funkkanal, Standort, Reichweite oder Endgerät</td></tr></tbody></table><p>Router-Neustarts können Zähler und Verlauf löschen. Vorher Screenshots und Uhrzeiten der Abbrüche sichern.</p>' . $sources . '</article>',
            'dsl-synchronisiert-nicht' => '<article class="gk-clean-article">' . self::photo('tae-dose.jpg', 'Weiße TAE-NFF-Anschlussdose mit drei Buchsen.', 'Erste TAE: regulärer Anschluss- und Messpunkt des DSL-Routers. Foto: Uwe Schwöbel, GNU FDL 1.2, via Wikimedia Commons.') . '<h2>Was bedeutet fehlende Synchronisation?</h2><p>Ohne DSL-Synchronisation besteht keine physikalische DSL-Verbindung zwischen dem Modem im Router und dem DSLAM/MSAN. Das ist von einer fehlgeschlagenen Internet-Einwahl trotz bestehender Synchronisation zu unterscheiden.</p><h2>Sichere Erstprüfung</h2><ol><li>Statusanzeige und Ereignisprotokoll des Routers prüfen.</li><li>DSL-Kabel direkt an der ersten TAE anschließen; unnötige Verlängerungen entfernen.</li><li>Stecker, Netzteil und Routerneustart einmal kontrolliert testen.</li><li>Beginn, Dauer und Wetterbezug der Störung dokumentieren.</li><li>Bei weiter fehlender Synchronisation eine Leitungsprüfung veranlassen.</li></ol><h2>Mögliche Fehlerstellen</h2><p>Infrage kommen Port oder Rangierung, Kupfer-Zugangsnetz, Muffe, APL, Endleitung, erste TAE, DSL-Kabel oder Modem. Der Ort lässt sich erst durch Messungen und Vergleiche eingrenzen.</p><p>APL und feste Leitungen nicht selbst öffnen oder umklemmen.</p>' . $sources . '</article>',
            'dsl-ausfall-bei-regen-die-haeufigsten-ursachen' => '<article class="gk-clean-article">' . self::photo('apl.png', 'Geöffneter Kupfer-APL mit Mehraderkabel und Anschlussklemmen.', 'Wetterabhängige DSL-Fehler werden entlang der Kupferstrecke und an Verbindungsstellen gesucht.') . '<h2>Warum Regen DSL-Störungen sichtbar machen kann</h2><p>Wenn Abbrüche reproduzierbar bei Regen oder hoher Feuchtigkeit auftreten, ist eine beeinträchtigte Kabel- oder Verbindungsstelle wahrscheinlich. Wasser muss dabei nicht im Hausanschluss stehen: Auch Muffen, Kabelschäden und Anschlusspunkte im Zugangsnetz kommen infrage.</p><h2>Typische Anzeichen</h2><ul><li>sinkende Störabstandsmarge vor dem Abbruch</li><li>stark ansteigende CRC-Fehler</li><li>wiederholte Resynchronisationen</li><li>normale Werte nach längerer Trockenphase</li></ul><h2>So wird der Fehler belegbar</h2><ol><li>Datum, Uhrzeit und Wetterlage notieren.</li><li>Routerwerte und Ereignisprotokoll vor und während der Störung sichern.</li><li>DSL an der ersten TAE ohne Verlängerung betreiben.</li><li>Störung mit Hinweis „wetterabhängig“ melden.</li></ol><p>Eine Sichtprüfung ersetzt keine Messung. APL, Muffen und Netzbetreiberkabel dürfen nur durch berechtigtes Fachpersonal geöffnet oder bearbeitet werden.</p>' . $sources . '</article>',
            'endleitung-dsl-probleme' => '<article class="gk-clean-article">' . self::photo('tal.png', 'Mehraderiges Kupferkabel mit ausgewählter Doppelader.', 'Die Endleitung führt als Kupfer-Doppelader vom APL zur ersten TAE.') . '<h2>Was ist die DSL-Endleitung?</h2><p>Die Endleitung ist die gebäudeseitige Kupferverbindung zwischen APL und erster TAE. Sie gehört weder zum WLAN noch zur Glasfaserstrecke. Schlechte Kontakte, ungeeignete Leitungen und Abzweigungen können DSL-Datenrate und Stabilität verschlechtern.</p><h2>Typische Fehlerquellen</h2><ul><li>lose, korrodierte oder mehrfach belegte Klemmstellen</li><li>parallel geschaltete TAE-Dosen und ungenutzte Abzweige</li><li>alte Flach-, Klingel- oder flexible Verlängerungsleitungen</li><li>Quetschungen, Feuchtigkeit oder beschädigte Adern</li></ul><h2>Messvergleich</h2><p>Sind die Werte am APL deutlich besser als an der ersten TAE, liegt die zusätzliche Beeinträchtigung wahrscheinlich in Endleitung, Klemmstellen oder Dose. Ähnliche Werte sprechen gegen einen großen zusätzlichen Verlust im Gebäude.</p><h2>Wann erneuern?</h2><p>Eine Erneuerung ist sinnvoll, wenn der Fehler messtechnisch der Endleitung zugeordnet wurde oder die vorhandene Leitung ungeeignet beziehungsweise beschädigt ist. Die Ausführung und Zuständigkeit müssen vorab geklärt werden.</p>' . $sources . '</article>',
            'crc-fehler-erklaert-was-sie-ueber-eine-dsl-leitung-aussagen' => '<article class="gk-clean-article">' . self::photo('tae-dose.jpg', 'Weiße TAE-NFF-Anschlussdose mit drei Buchsen.', 'CRC-Fehler werden auf der DSL-Verbindung bewertet; erste TAE und Endleitung sind mögliche, aber nicht die einzigen Fehlerstellen. Foto: Uwe Schwöbel, GNU FDL 1.2, via Wikimedia Commons.') . '<h2>Was sind CRC-Fehler?</h2><p>CRC-Fehler zeigen Datenblöcke, die trotz Übertragungsschutz nicht korrekt empfangen wurden. Sie können Wiederholungen, geringeren nutzbaren Durchsatz und bei starker Häufung eine instabile Verbindung begleiten.</p><h2>Die Anzahl allein reicht nicht</h2><p>Entscheidend sind Zeitraum, Datenverkehr und gleichzeitiges Fehlerbild. Einige Fehler über lange Laufzeit sind anders zu bewerten als ein schneller Anstieg innerhalb weniger Minuten mit Abbrüchen.</p><h2>Praxisbewertung</h2><ul><li>Zählerstand und Routerlaufzeit gemeinsam notieren.</li><li>Fehlerzuwachs pro Stunde statt bloßen Gesamtwert vergleichen.</li><li>Störabstandsmarge und Resynchronisationen parallel beobachten.</li><li>DSL-Verbindung von LAN- und WLAN-Problemen trennen.</li><li>Bei auffälligem Zuwachs Messung an erster TAE und APL vergleichen lassen.</li></ul><p>CRC-Fehler beweisen nicht automatisch einen defekten Router oder eine bestimmte Kabelstelle; sie sind ein Symptom für die weitere Eingrenzung.</p>' . $sources . '</article>',
            'fec-fehler-richtig-interpretieren' => '<article class="gk-clean-article">' . self::photo('tae-dose.jpg', 'Weiße TAE-NFF-Anschlussdose mit drei Buchsen.', 'FEC-Zähler gehören zur Bewertung der DSL-Übertragung und müssen zusammen mit Laufzeit und CRC-Fehlern betrachtet werden. Foto: Uwe Schwöbel, GNU FDL 1.2, via Wikimedia Commons.') . '<h2>Was bedeuten FEC-Fehler?</h2><p>FEC steht für Forward Error Correction. Der Zähler zeigt Übertragungsfehler, die durch die Fehlerkorrektur erkannt und korrigiert werden konnten. Deshalb bedeutet ein steigender FEC-Zähler nicht automatisch einen spürbaren Ausfall.</p><h2>Richtig bewerten</h2><ul><li>Routerlaufzeit und Beobachtungszeitraum berücksichtigen.</li><li>Zuwachs pro Zeiteinheit statt Gesamtstand vergleichen.</li><li>CRC-Fehler, Störabstandsmarge und Resynchronisationen mitprüfen.</li><li>Änderungen unter Last und zu verschiedenen Tageszeiten dokumentieren.</li></ul><h2>Wann genauer prüfen?</h2><p>Wenn FEC-Werte plötzlich stark ansteigen und gleichzeitig CRC-Fehler, Paketverluste, sinkende Datenrate oder Abbrüche auftreten, sollte die DSL-Strecke systematisch geprüft werden. Ein hoher Gesamtwert nach langer Laufzeit ist ohne diesen Kontext nicht aussagekräftig.</p>' . $sources . '</article>',
            'snr-stoerabstandsmarge-erklaert' => '<article class="gk-clean-article">' . self::photo('tal.png', 'Mehraderiges Kupferkabel mit ausgewählter DSL-Doppelader.', 'Die Störabstandsmarge beschreibt die Reserve zwischen nutzbarem DSL-Signal und Störpegel.') . '<h2>Störabstandsmarge verständlich erklärt</h2><p>Die Störabstandsmarge – häufig als SNR Margin bezeichnet – ist die verbleibende Reserve gegenüber Störungen. Sie ist nicht identisch mit dem absoluten Signal-Rausch-Abstand und wird meist getrennt für Downstream und Upstream angezeigt.</p><h2>Warum ein Einzelwert nicht genügt</h2><p>Der Wert hängt unter anderem von Profil, Datenrate, Frequenzbelegung und aktuellen Störungen ab. Ein niedriger oder schwankender Wert ist vor allem dann auffällig, wenn gleichzeitig CRC-Fehler oder Resynchronisationen auftreten.</p><h2>Praxisprüfung</h2><ol><li>Werte nach stabiler Synchronisation notieren.</li><li>Verlauf zu Störungszeiten und bei normalem Betrieb vergleichen.</li><li>CRC-/FEC-Zähler sowie Datenrate parallel sichern.</li><li>Bei Abweichungen Messpunkte an erster TAE und APL vergleichen lassen.</li></ol><p>Pauschale Grenzwerte ohne Kenntnis des DSL-Profils sind keine sichere Diagnose.</p>' . $sources . '</article>',
            'was-prueft-ein-techniker-bei-einer-entstoerung' => '<article class="gk-clean-article">' . self::photo('techniker-werkzeuge.png', 'Messgerät, Reinigungs- und Montagewerkzeuge für die Telekommunikationspraxis.', 'Prüfschritte richten sich nach Anschlussart und Fehlerbild; DSL und Glasfaser benötigen unterschiedliche Messmittel.') . '<h2>Die Entstörung beginnt mit dem Fehlerbild</h2><p>Der Techniker prüft nicht automatisch jeden Punkt, sondern folgt Messwerten und Beobachtungen. Zuerst werden Anschlussart, Störungszeitraum und betroffene Dienste geklärt.</p><h2>Bei DSL</h2><ol><li>Synchronisation, Datenrate, Störabstand und Fehlerzähler prüfen.</li><li>Messung an erster TAE und bei Bedarf am APL vergleichen.</li><li>Endleitung, Klemmstellen und Anschlusskabel eingrenzen.</li><li>Betreiberstrecke beziehungsweise Port prüfen lassen, wenn der Fehler bereits am APL besteht.</li></ol><h2>Bei FTTH</h2><ol><li>Status von ONT oder Glasfaserrouter prüfen.</li><li>Steckverbindungen, Biegeradien und sichtbare Beschädigungen kontrollieren.</li><li>Optischen Pegel oder Streckenereignisse mit geeignetem Messgerät bewerten.</li><li>Ethernet- und Routerverbindung anschließend getrennt testen.</li></ol><h2>Was vorbereitet sein sollte</h2><p>Zugang zu APL und erster TAE bei DSL beziehungsweise Gf-AP, Gf-TA und ONT bei FTTH; außerdem Router, Netzteil, Anschlusskabel und dokumentierte Störungszeiten.</p>' . $sources . '</article>',
            'technikertermin-dsl-vorbereiten' => '<article class="gk-clean-article">' . self::photo('apl.png', 'Geöffneter Kupfer-APL mit Mehraderkabel und Anschlussklemmen.', 'Für einen DSL-Termin müssen APL und erste TAE erreichbar sein; den APL öffnet nur berechtigtes Fachpersonal.') . '<h2>Vor dem DSL-Technikertermin</h2><ul><li>Termin, Ansprechpartner und erreichbare Telefonnummer bestätigen.</li><li>Keller, Hausanschlussraum und Wohnung zugänglich machen.</li><li>Hausmeister oder Vermieter rechtzeitig informieren, wenn Schlüssel nötig sind.</li><li>APL und erste TAE freiräumen, aber nicht selbst öffnen oder umklemmen.</li><li>Router, Netzteil und DSL-Anschlusskabel bereithalten.</li></ul><h2>Störung dokumentieren</h2><p>Beginn, Häufigkeit, Wetterbezug, Router-Ereignisse und Leitungswerte notieren. Bei zeitweiligen Fehlern sind genaue Uhrzeiten besonders hilfreich.</p><h2>Was der Techniker vergleichen kann</h2><p>Die Messung an der ersten TAE bildet den regulären Kundenanschluss ab. Bei Abweichungen kann der Vergleich am APL Betreiberstrecke und gebäudeseitige Endleitung trennen.</p><h2>Nicht mit FTTH verwechseln</h2><p>Gf-AP, Gf-TA und ONT gehören zum Glasfaseranschluss. Für einen DSL-Termin sind APL, Kupfer-Endleitung und erste TAE maßgeblich.</p>' . $sources . '</article>',
            'warum-wird-an-der-ersten-tae-gemessen' => '<article class="gk-clean-article">' . self::photo('tae-dose.jpg', 'Weiße TAE-NFF-Anschlussdose mit drei Buchsen.', 'Erste TAE: regulärer Anschluss- und Messpunkt eines DSL-Anschlusses. Foto: Uwe Schwöbel, GNU FDL 1.2, via Wikimedia Commons.') . '<h2>Warum ist die erste TAE der erste Messpunkt?</h2><p>Die erste TAE ist der reguläre Übergabepunkt in den Kundenräumen, an dem der DSL-Router angeschlossen wird. Eine Messung dort erfasst die gesamte Strecke bis zum üblichen Routeranschluss – einschließlich der Endleitung ab APL.</p><h2>Was zeigt der Vergleich mit dem APL?</h2><table><thead><tr><th>Messbild</th><th>Einordnung</th></tr></thead><tbody><tr><td>Werte an APL und erster TAE ähnlich</td><td>Endleitung verursacht wahrscheinlich keinen großen zusätzlichen Verlust.</td></tr><tr><td>Werte an erster TAE deutlich schlechter</td><td>Endleitung, Abzweigung, Klemmstelle oder TAE prüfen.</td></tr><tr><td>Bereits am APL auffällig</td><td>Betreiber-Kupfernetz oder Port weiter eingrenzen.</td></tr></tbody></table><h2>Vorbereitung</h2><p>Erste TAE freiräumen, Router und DSL-Kabel bereithalten und weitere Dosen oder Abzweigungen nennen. Feste Leitungen und APL nicht selbst bearbeiten.</p>' . $sources . '</article>',
            'fehler-beim-glasfaseranschluss' => '<article class="gk-clean-article">' . self::photo('ftth-signalweg.png', 'FTTH-Signalweg vom passiven Glasfasernetz über Gf-AP und Gf-TA bis ONT und Router.', 'FTTH-Komponenten müssen in der richtigen Reihenfolge geplant, montiert und geprüft werden.') . '<h2>Die häufigsten Fehler entstehen an Übergängen</h2><p>Die Glasfaser selbst ist nur ein Teil des Anschlusses. In der Praxis verursachen ungeklärte Leitungswege, verschmutzte Steckflächen, enge Biegeradien, fehlende Stromversorgung und eine falsche Routerverbindung viele vermeidbare Probleme.</p><h2>Vor und während der Montage</h2><ul><li>Gebäudeeinführung, Gf-AP, Gf-TA, ONT und Routerstandort vorab festlegen.</li><li>Leitungsweg zugänglich halten und zulässige Biegeradien einhalten.</li><li>Optische Steckflächen nicht berühren und Schutzkappen sauber halten.</li><li>ONT mit Strom versorgen und Router am vorgesehenen WAN-Port anschließen.</li><li>Komponenten und Fasern eindeutig dokumentieren.</li></ul><h2>Bei einer Störung</h2><p>Zuerst optischen Status, anschließend Ethernet-Verbindung und danach Router sowie WLAN getrennt prüfen. Ein langsames WLAN beweist keinen Fehler der Glasfaserstrecke.</p><p>Optische Anschlüsse nicht eigenmächtig öffnen, reinigen oder mit ungeeigneten Mitteln bearbeiten.</p>' . $fiber_sources . '</article>',
            'haeufige-fehler-beim-ftth-anschluss' => '<article class="gk-clean-article">' . self::photo('gf-ta.png', 'Glasfaser-Teilnehmeranschlussdose mit optischer Buchse.', 'Gf-TA und optisches Patchkabel bilden den passiven Anschluss vor ONT oder Glasfaserrouter.') . '<h2>FTTH-Fehler nach Bereichen einordnen</h2><table><thead><tr><th>Bereich</th><th>Typischer Fehler</th></tr></thead><tbody><tr><td>Leitungsweg</td><td>Quetschung, zu enger Bogen oder ungeschützter Verlauf</td></tr><tr><td>Steckverbindung</td><td>Verschmutzung, falscher Steckertyp oder nicht vollständig gesteckt</td></tr><tr><td>ONT</td><td>fehlende Stromversorgung, optischer Alarm oder kein Ethernet-Link</td></tr><tr><td>Router</td><td>falscher Port, fehlende Anbieterparameter oder ungeeignetes Kabel</td></tr><tr><td>Heimnetz</td><td>schlechter Routerstandort, langsames WLAN oder begrenztes Endgerät</td></tr></tbody></table><h2>Saubere Prüfreihenfolge</h2><ol><li>Status von ONT beziehungsweise Glasfaserrouter ablesen.</li><li>Patchkabel nur äußerlich auf Knick oder Zug prüfen.</li><li>Ethernet-Link zum WAN-Port kontrollieren.</li><li>Internetzugang per LAN testen.</li><li>WLAN erst danach messen.</li></ol><p>Warnanzeigen und Messwerte müssen nach Anbieter- und Gerätevorgaben bewertet werden.</p>' . $fiber_sources . '</article>',
            'glasfaser-pegelmessung-verstehen' => '<article class="gk-clean-article">' . self::photo('techniker-werkzeuge.png', 'Mess- und Reinigungswerkzeuge für Arbeiten an Glasfaseranschlüssen.', 'Optische Pegel werden mit geeignetem, zur Wellenlänge und Messaufgabe passendem Gerät ermittelt.') . '<h2>Was zeigt eine optische Pegelmessung?</h2><p>Sie misst die am Messpunkt anliegende optische Leistung, üblicherweise in dBm. Der Wert wird mit den Vorgaben des jeweiligen Netz- und Gerätekonzepts verglichen. Ein Einzelwert ohne Wellenlänge, Messpunkt und Sollbereich ist nicht belastbar.</p><h2>dBm und dB unterscheiden</h2><ul><li><strong>dBm:</strong> absolute optische Leistung am Messpunkt.</li><li><strong>dB:</strong> Differenz beziehungsweise Verlust zwischen zwei Werten.</li></ul><h2>Bei auffälligem Pegel</h2><p>Mögliche Ursachen sind verschmutzte oder beschädigte Steckflächen, ein ungeeignetes Patchkabel, zu enge Biegung, schlechter Spleiß, fehlerhafte passive Verteilung oder ein Problem der vorgelagerten Strecke.</p><h2>Sicher arbeiten</h2><p>Nicht in Faserenden schauen. Steckflächen nur mit geeigneten Verfahren prüfen und reinigen. Die Messung gehört in die Hände geschulter Personen, die Anschlussklasse und Sollwerte kennen.</p>' . $fiber_sources . '</article>',
            'pegelmessung-erklaert' => '<article class="gk-clean-article">' . self::photo('techniker-werkzeuge.png', 'Optisches Messgerät und Werkzeuge für die Glasfaserprüfung.', 'Eine Pegelmessung bewertet die optische Leistung an einem definierten Punkt der FTTH-Strecke.') . '<h2>Pegelmessung kurz erklärt</h2><p>Bei einer Glasfaser-Pegelmessung wird die optische Empfangsleistung an einem definierten Messpunkt geprüft. Das Ergebnis wird in dBm angegeben und muss zum Netzdesign, zur Wellenlänge und zum eingesetzten Gerät passen.</p><h2>Was die Messung kann – und was nicht</h2><p>Sie zeigt, ob ausreichend optische Leistung ankommt. Sie lokalisiert jedoch nicht automatisch die genaue Fehlerstelle. Dafür können Vergleichsmessungen oder eine OTDR-Messung erforderlich sein.</p><h2>Messwert richtig dokumentieren</h2><ul><li>Messpunkt und Faserkennzeichnung</li><li>Wellenlänge und Messgerät</li><li>gemessener dBm-Wert</li><li>vorgegebener Soll- oder Toleranzbereich</li><li>Zustand und Reinigung der Steckverbindung</li></ul><p>Pauschale „gute“ dBm-Grenzen ohne Kenntnis des Anschlusskonzepts sind unseriös.</p>' . $fiber_sources . '</article>',
            'daempfung-im-glasfasernetz' => '<article class="gk-clean-article">' . self::photo('spleissstelle.png', 'Geschützte Fusionsspleißstelle in einer Spleißkassette.', 'Faser, Spleiße, Steckverbinder und passive Verteiler tragen zur gesamten optischen Dämpfung bei.') . '<h2>Was bedeutet Dämpfung?</h2><p>Dämpfung ist der Verlust optischer Leistung auf dem Übertragungsweg und wird in dB angegeben. Sie entsteht unter anderem in der Faser, an Spleißen, Steckverbindungen, Kopplungen und passiven Splittern.</p><h2>Einflussfaktoren</h2><ul><li>Streckenlänge und verwendete Wellenlänge</li><li>Anzahl und Qualität der Spleiße</li><li>Sauberkeit und Zustand der Steckflächen</li><li>Biegeradius und mechanische Belastung</li><li>Verteilungsverhältnis passiver Splitter</li></ul><h2>Dämpfungsbudget statt Pauschalwert</h2><p>Ob eine Strecke zulässig ist, entscheidet das geplante Dämpfungsbudget des Netzes. Gemessene optische Leistung, Sender- und Empfängergrenzen sowie alle vorgesehenen Komponenten müssen zusammenpassen.</p><p>Eine erhöhte Dämpfung wird nicht durch einen schnelleren Router behoben.</p>' . $fiber_sources . '</article>',
            'los-rot-glasfaser' => '<article class="gk-clean-article">' . self::photo('ont.png', 'ONT mit optischem Eingang, Ethernet-Ausgang, Stromversorgung und Statusanzeigen.', 'Eine rote LOS-Anzeige weist bei vielen ONTs auf ein fehlendes oder zu schwaches optisches Empfangssignal hin.') . '<h2>Was bedeutet „LOS“?</h2><p>LOS steht für „Loss of Signal“. Leuchtet die Anzeige rot, erkennt der ONT bei vielen Geräten kein ausreichendes optisches Signal. Die genaue Bedeutung und Blinkfolge muss im Handbuch des konkreten Modells geprüft werden.</p><h2>Sichere Erstprüfung</h2><ol><li>ONT nicht vom Strom trennen, bevor Status und Zeitpunkt dokumentiert sind.</li><li>Prüfen, ob das optische Patchkabel sichtbar geknickt oder herausgezogen ist.</li><li>Stecker nicht öffnen, berühren oder ohne Reinigungsmittel und Schulung bearbeiten.</li><li>Störung mit Anzeigen, Uhrzeit und eventuellen Bauarbeiten melden.</li></ol><h2>Mögliche Ursachen</h2><p>Infrage kommen Patchkabel oder Steckverbindung, Gf-TA, gebäudeinterne Faser, Gf-AP, passive Verteilung oder die vorgelagerte Netzstrecke. WLAN-Einstellungen verursachen keine rote optische LOS-Anzeige.</p>' . $fiber_sources . '</article>',
            'technikertermin-glasfaser-vorbereiten' => '<article class="gk-clean-article">' . self::photo('gf-ap.png', 'Geöffneter Gf-AP mit Faserführung und Spleißablage.', 'Gf-AP, geplanter Leitungsweg, Gf-TA, ONT und Routerstandort müssen für den Termin erreichbar sein.') . '<h2>Vor dem Glasfaser-Technikertermin</h2><ul><li>Termin, Ansprechpartner und Telefonnummer bestätigen.</li><li>Hausanschlussraum, Gebäudeeinführung und vereinbarten Leitungsweg zugänglich machen.</li><li>Montageorte für Gf-AP, Gf-TA, ONT und Router abstimmen.</li><li>Genehmigungen von Eigentümer oder Hausverwaltung klären.</li><li>Stromversorgung für ONT oder aktives Endgerät sicherstellen.</li></ul><h2>Leitungsweg vorbereiten</h2><p>Möbel und Verkleidungen entfernen, vorhandene Leerrohre benennen und problematische Brandschutz- oder Wanddurchführungen vorab klären. Fasern benötigen einen geeigneten Verlauf ohne Quetschung und enge Bögen.</p><h2>Bei einer Entstörung</h2><p>Statusanzeigen, Ausfallzeit, betroffene Dienste und vorhandene Änderungen dokumentieren. Optische Steckverbindungen nicht vorsorglich trennen.</p>' . $fiber_sources . '</article>',
            'internet-langsam-trotz-glasfaser-woran-kann-das-liegen' => '<article class="gk-clean-article">' . self::photo('wlan-heimnetz.png', 'Heimnetz mit Router, LAN-Verbindungen und WLAN-Endgeräten.', 'Die FTTH-Strecke, der Router und das Heimnetz werden getrennt gemessen.') . '<h2>Langsame Verbindung systematisch eingrenzen</h2><ol><li><strong>Tarif und Anschlussstatus:</strong> gebuchte Datenrate und mögliche Anbieterhinweise prüfen.</li><li><strong>LAN-Referenz:</strong> geeignetes Endgerät direkt per Gigabit- oder schnellerem Ethernet am Router testen.</li><li><strong>Router und ONT:</strong> Linkgeschwindigkeit, WAN-Port und Kabel kontrollieren.</li><li><strong>WLAN getrennt messen:</strong> Standort, Frequenzband und Endgerät berücksichtigen.</li><li><strong>Gegenprobe:</strong> mehrere Messungen zu verschiedenen Zeiten durchführen.</li></ol><h2>Typische Begrenzungen</h2><table><thead><tr><th>Ergebnis</th><th>Wahrscheinlicher Bereich</th></tr></thead><tbody><tr><td>LAN und WLAN langsam</td><td>Anschluss, Anbieter, WAN-Link, Router oder Endgerät</td></tr><tr><td>LAN schnell, WLAN langsam</td><td>Funkumgebung, Routerstandort oder WLAN-Gerät</td></tr><tr><td>Nur ein Gerät langsam</td><td>Endgerät, Treiber, Port oder Verbindung</td></tr></tbody></table><p>Ein WLAN-Speedtest allein bewertet nicht die Leistungsfähigkeit des Glasfaseranschlusses.</p>' . $fiber_sources . '</article>',
            'ont-standort-worauf-achten' => '<article class="gk-clean-article">' . self::photo('ont.png', 'ONT mit optischem Eingang, Ethernet-Ausgang und Stromversorgung.', 'Der ONT benötigt einen geschützten, belüfteten Standort nahe Gf-TA und Stromversorgung.') . '<h2>Anforderungen an den ONT-Standort</h2><ul><li>trockener, sauberer und ausreichend belüfteter Bereich</li><li>passende Netzsteckdose ohne Zug am Kabel</li><li>kurzer, geschützter optischer Weg von der Gf-TA</li><li>geeignete Ethernetverbindung zum WAN-Port des Routers</li><li>Zugang zu Statusanzeigen und Anschlüssen</li></ul><h2>ONT und Router müssen nicht nebeneinander stehen</h2><p>Zwischen ONT und Router kann ein geeignetes Ethernetkabel eingesetzt werden. Dadurch lässt sich der Router oft zentraler für gutes WLAN positionieren, während das optische Patchkabel kurz und geschützt bleibt.</p><h2>Vermeiden</h2><p>Feuchte Räume, Wärmestau, direkte Sonneneinstrahlung, mechanische Belastung, enge Biegungen und frei zugängliche Stecker. Montagevorgaben des Anbieters und Herstellers haben Vorrang.</p>' . $fiber_sources . '</article>',
            'gf-ap-montageort-planen' => '<article class="gk-clean-article">' . self::photo('gf-ap.png', 'Geöffneter Gf-AP mit Faserführung und Spleißablage.', 'Der Gf-AP liegt üblicherweise nahe der Gebäudeeinführung an einem trockenen und zugänglichen Montageort.') . '<h2>Geeigneter Montageort für den Gf-AP</h2><p>Der Gf-AP sollte möglichst nahe der Gebäudeeinführung an einer tragfähigen Fläche montiert werden. Der Ort muss trocken, dauerhaft zugänglich und vor mechanischer Beschädigung geschützt sein.</p><h2>Vor der Festlegung prüfen</h2><ul><li>Position der Hauseinführung und vorhandene Leerrohre</li><li>zulässiger Leitungsweg und Biegeradien</li><li>Zugang für Spleiß-, Mess- und Wartungsarbeiten</li><li>Brandschutz und Gebäudedurchführungen</li><li>Weiterführung zur Gf-TA in Haus oder Wohnung</li></ul><h2>Abgrenzung</h2><p>Der Gf-AP ist ein passiver Gebäudeabschluss und benötigt selbst keine Steckdose. Strom wird erst für ONT oder aktiven Router benötigt. In Mehrfamilienhäusern hängt die Weiterführung vom Ausbaukonzept und den Netzebenen im Gebäude ab.</p>' . $fiber_sources . '</article>',
            'glasfaser-hausanschluss-erklaert' => '<article class="gk-clean-article">' . self::photo('gf-ap.png', 'Geöffneter Gf-AP mit Faserführung und Spleißablage.', 'Der Gf-AP bildet den passiven Abschluss der ankommenden Glasfaser am Gebäude.') . '<h2>Vom Grundstück bis zum Router</h2><ol><li>Hauszuführung vom öffentlichen Glasfasernetz herstellen.</li><li>Gebäudeeinführung fachgerecht abdichten.</li><li>Glasfaser am Gf-AP abschließen und dokumentieren.</li><li>Gebäudeinterne Faser zur Gf-TA führen.</li><li>ONT oder Glasfaserrouter anschließen und messen.</li></ol><h2>Die Bauteile eindeutig trennen</h2><p>Der Gf-AP ist passiv und liegt meist nahe der Hauseinführung. Die Gf-TA ist die optische Teilnehmeranschlussdose. Ein ONT benötigt Strom und stellt Ethernet bereit; der Router übernimmt Internetzugang und Heimnetz.</p><h2>Vor der Montage klären</h2><ul><li>Hauseinführung und Leitungsweg</li><li>Montageorte und Biegeradien</li><li>Wanddurchführungen und Brandschutz</li><li>Stromversorgung sowie Ethernetweg zum Router</li><li>Zugangs- und Eigentumsfragen</li></ul>' . $fiber_sources . '</article>',
            'glasfaser-hausanschluss-checkliste' => '<article class="gk-clean-article">' . self::photo('speedpipe.png', 'Verband aus farbigen Mikrorohren für Glasfaserkabel.', 'Leerrohr, Hauseinführung und gebäudeinterner Leitungsweg müssen vor dem Anschluss abgestimmt sein.') . '<h2>Checkliste vor der Hausbegehung</h2><ul><li>Eigentümer- und Kontaktdaten bereithalten.</li><li>Grundstücksweg und vorhandene Versorgungsleitungen kennen.</li><li>Hausanschlussraum und mögliche Gebäudeeinführung zugänglich machen.</li><li>Leitungsweg zu Gf-TA, ONT und Router planen.</li><li>Genehmigungen und Sondernutzungen frühzeitig klären.</li></ul><h2>Checkliste vor der Montage</h2><ul><li>Vereinbarte Flächen freiräumen.</li><li>Leerrohre und Durchführungen auf Nutzbarkeit prüfen lassen.</li><li>Strom für ONT oder aktives Endgerät bereitstellen.</li><li>Schlüssel, Hausmeister und Bewohner koordinieren.</li></ul><h2>Nach dem Termin</h2><ul><li>Bauteile und Leitungsweg fotografisch dokumentieren.</li><li>Mess- oder Übergabeprotokoll sichern.</li><li>Status von ONT und Router prüfen.</li><li>LAN testen, bevor WLAN bewertet wird.</li></ul>' . $fiber_sources . '</article>',
            'glasfaser-im-einfamilienhaus' => '<article class="gk-clean-article">' . self::photo('gf-ap.png', 'Geöffneter Gf-AP als passiver Glasfaser-Gebäudeabschluss.', 'Im Einfamilienhaus lässt sich der Weg von der Hauseinführung bis zum Router gemeinsam planen.') . '<h2>Planung im Einfamilienhaus</h2><p>Entscheidend ist nicht nur, wo die Faser ins Gebäude kommt. Gf-AP, Gf-TA, ONT und Router müssen als zusammenhängender Leitungsweg geplant werden.</p><h2>Bewährte Reihenfolge</h2><ol><li>Gebäudeeinführung nahe dem Hausanschlussbereich festlegen.</li><li>Gf-AP trocken und zugänglich montieren.</li><li>Geschützten Faserweg zur Gf-TA wählen.</li><li>Strom und Ethernetverbindung für den ONT vorsehen.</li><li>Router möglichst zentral für LAN und WLAN positionieren.</li></ol><h2>Keller und Wohnbereich verbinden</h2><p>Liegt der ONT im Keller, kann der Router über ein geeignetes Ethernetkabel im Wohnbereich stehen. Das ist für WLAN meist besser, als den Router direkt neben dem Hausanschluss zu belassen.</p>' . $fiber_sources . '</article>',
            'glasfaser-im-mehrfamilienhaus' => '<article class="gk-clean-article">' . self::photo('gf-ap.png', 'Geöffneter Gf-AP mit Faserführung und vorbereiteten Abgängen.', 'Im Mehrfamilienhaus folgt auf den Gebäudeabschluss die koordinierte Verteilung zu den Wohnungen.') . '<h2>Der Signalweg im Mehrfamilienhaus</h2><p><strong>Hauszuführung → Gf-AP beziehungsweise Gebäudeverteiler → gebäudeinterne Glasfaser → Gf-TA in der Wohnung → ONT oder Glasfaserrouter</strong></p><h2>Was zusätzlich geplant werden muss</h2><ul><li>Steigwege, Etagenbereiche und Wohnungszuführungen</li><li>Brandschutz bei Wand- und Deckendurchführungen</li><li>Zugangsregelung für Technikräume und Wohnungen</li><li>Faser- und Wohnungskennzeichnung</li><li>Eigentümerbeschlüsse und Terminabstimmung</li></ul><h2>Keine pauschale Gebäudelösung</h2><p>Verteilerkonzept, Netzebenen und Zuständigkeiten unterscheiden sich nach Netzbetreiber und Gebäude. Vor Baubeginn muss schriftlich feststehen, welche Strecke der Betreiber errichtet und welche Vorleistung das Gebäude erbringt.</p>' . $fiber_sources . '</article>',
            'glasfaser-fuer-mehrfamilienhaeuser' => '<article class="gk-clean-article">' . self::photo('nvt.png', 'Passiver Glasfaserverteiler mit geordneten Faserwegen und Kupplungen.', 'Eine eindeutige Faser- und Wohnungszuordnung ist im Mehrfamilienhaus unverzichtbar.') . '<h2>Mehrfamilienhäuser brauchen ein Gebäudekonzept</h2><p>Ein Hausanschluss allein versorgt noch keine Wohnung. Benötigt werden ein dokumentierter Gebäudeabschluss, geeignete Steigwege und ein klares Konzept für jede Wohnungszuführung.</p><h2>Planungspunkte für Eigentümer und Verwaltung</h2><ul><li>Betreiber, Ausbauumfang und Eigentumsgrenzen festhalten.</li><li>Technikraum und vertikale Leitungswege bestimmen.</li><li>Brandschutz und bauliche Freigaben klären.</li><li>Wohnungszugang und Terminserien organisieren.</li><li>Reservekapazität und dauerhafte Beschriftung vorsehen.</li></ul><h2>Abnahme</h2><p>Dokumentation, Faserzuordnung und Messnachweise müssen zum gebauten Zustand passen. Lose Beschriftungen oder unklare Wohnungsnummern führen später zu Fehlanschaltungen und vermeidbaren Terminen.</p>' . $fiber_sources . '</article>',
            'glasfaseranschluss-im-einfamilienhaus-erklaert' => '<article class="gk-clean-article">' . self::photo('ftth-signalweg.png', 'FTTH-Verbindung von der passiven Verteilung über Gf-AP und Gf-TA bis ONT und Router.', 'Im Einfamilienhaus werden Außen- und Innenweg als durchgängige FTTH-Strecke geplant.') . '<h2>So entsteht der Anschluss</h2><ol><li>Trasse vom öffentlichen Netz bis zum Grundstück herstellen.</li><li>Schutzrohr oder Glasfaserkabel zur Gebäudeeinführung führen.</li><li>Einführung abdichten und Gf-AP montieren.</li><li>Gebäudeinterne Glasfaser zur Gf-TA verlegen.</li><li>ONT beziehungsweise Glasfaserrouter anschließen und freischalten.</li></ol><h2>Standorte früh festlegen</h2><p>Ein kurzer Außenweg ist nicht automatisch die beste Gesamtlösung. Routerstandort, WLAN-Versorgung und vorhandene Netzwerkverkabelung müssen in die Planung einbezogen werden.</p><h2>Abnahmefragen</h2><ul><li>Sind Hauseinführung und Leitungsweg sauber verschlossen?</li><li>Sind Gf-AP, Gf-TA und Faser eindeutig beschriftet?</li><li>Liegt ein Mess- oder Übergabenachweis vor?</li><li>Funktioniert der Zugang per LAN am Router?</li></ul>' . $fiber_sources . '</article>',
            'glasfaseranschluss-im-mehrfamilienhaus-erklaert' => '<article class="gk-clean-article">' . self::photo('gf-ta.png', 'Glasfaser-Teilnehmeranschlussdose mit optischer Buchse.', 'Die Gf-TA bildet den passiven optischen Anschluss in der jeweiligen Wohnung.') . '<h2>Vom Keller bis in jede Wohnung</h2><p>Nach der Hauszuführung wird die Glasfaser über den Gebäudeabschluss und die gebäudeinterne Verteilung bis zur Gf-TA der einzelnen Wohnung geführt. ONT oder Glasfaserrouter folgen erst im Nutzungsbereich.</p><h2>Koordination ist Teil der Technik</h2><ul><li>Steigweg und Etagenverteilung planen.</li><li>Brandschutzanforderungen je Durchführung umsetzen.</li><li>Wohnungen, Fasern und Ports eindeutig kennzeichnen.</li><li>Zutritt zu Gemeinschafts- und Wohnungsbereichen organisieren.</li><li>Montage- und Messtermine gebündelt abstimmen.</li></ul><h2>Typische Fehler vermeiden</h2><p>Unklare Zuständigkeiten, fehlende Eigentümerfreigaben, ungeeignete Steigwege und falsche Wohnungszuordnung verzögern den Ausbau stärker als die eigentliche Faserverlegung.</p>' . $fiber_sources . '</article>',
            'hausbegehung-akp-glasfaser' => '<article class="gk-clean-article">' . self::photo('techniker-werkzeuge.png', 'Dokumentations- und Messwerkzeuge für Planung und Glasfasermontage.', 'Die Hausbegehung legt Trasse, Gebäudeeinführung, Montageorte und Verantwortlichkeiten verbindlich fest.') . '<h2>Was wird bei der Hausbegehung geklärt?</h2><ul><li>Trasse auf dem Grundstück und vorhandene Leitungen</li><li>Position und Art der Gebäudeeinführung</li><li>Montageort von Gf-AP oder Gebäudeverteiler</li><li>Innenweg zu Gf-TA, ONT und Router</li><li>Bohrungen, Brandschutz und Oberflächenwiederherstellung</li><li>Zugang, Ansprechpartner und Terminbedingungen</li></ul><h2>Was bedeutet AKP?</h2><p>Die Abkürzung wird von Anbietern nicht immer einheitlich verwendet und kann einen abgestimmten Anschluss- oder Kabelpunkt bezeichnen. Entscheidend ist deshalb die schriftliche Definition im Begehungsprotokoll – einschließlich Position, Ausführung und Zuständigkeit.</p><h2>Protokoll vor Unterschrift prüfen</h2><p>Skizze, Fotos, Maße, Sonderwünsche und bauseitige Leistungen müssen verständlich festgehalten sein. Mündliche Nebenabreden reichen für die spätere Montage nicht aus.</p>' . $fiber_sources . '</article>',
            'wie-kommt-glasfaser-ins-haus' => '<article class="gk-clean-article">' . self::photo('speedpipe.png', 'Mikrorohrverband zur geschützten Führung von Glasfaserkabeln.', 'Je nach Ausbau wird das Glasfaserkabel durch ein Schutz- oder Mikrorohr bis zur Gebäudeeinführung geführt.') . '<h2>Der Weg von der Straße ins Gebäude</h2><ol><li>Abzweig vom öffentlichen Verteilnetz herstellen.</li><li>Trasse zum Gebäude öffnen, bohren oder vorhandenes Rohr nutzen.</li><li>Schutzrohr beziehungsweise Kabel bis zur Hauseinführung führen.</li><li>Gebäudedurchführung wasser- und gasdicht nach Systemvorgabe herstellen.</li><li>Faser am Gf-AP abschließen, spleißen und messen.</li></ol><h2>Mögliche Bauverfahren</h2><p>Offener Graben, Erdrakete, Spülbohrung oder Nutzung vorhandener Leerrohre kommen je nach Boden, Trasse und Betreiberstandard infrage. Kein Verfahren ist für jedes Grundstück automatisch geeignet.</p><h2>Im Haus geht es weiter</h2><p>Vom Gf-AP führt eine gebäudeinterne Glasfaser zur Gf-TA und weiter zu ONT oder Glasfaserrouter. Der Routerstandort sollte nicht erst nach Abschluss der Tiefbauarbeiten bedacht werden.</p>' . $fiber_sources . '</article>',
            'netzebenen-im-glasfaserausbau' => '<article class="gk-clean-article">' . self::photo('nvt.png', 'Passiver Netzverteiler für Glasfaser mit geordneten Faserwegen.', 'Netzebenen trennen Zugangs-, Gebäude- und Teilnehmerbereiche; die konkrete Bezeichnung kann je Betreiber abweichen.') . '<h2>Netzebenen verständlich einordnen</h2><table><thead><tr><th>Bereich</th><th>Typischer Inhalt</th></tr></thead><tbody><tr><td>Zugangsnetz</td><td>PoP/OLT, Haupt- und Verteilkabel, Splitter und NVT</td></tr><tr><td>Grundstück und Gebäudezuführung</td><td>Abzweig, Hauseinführung und Gf-AP beziehungsweise Gebäudeverteiler</td></tr><tr><td>Gebäudenetz</td><td>Steig- und Wohnungszuführungen bis zur Gf-TA</td></tr><tr><td>Teilnehmerbereich</td><td>ONT oder Glasfaserrouter sowie LAN und WLAN</td></tr></tbody></table><h2>Warum Begriffe variieren</h2><p>Bezeichnungen wie NE3, NE4 und NE5 werden im Markt verwendet, ihre genaue Abgrenzung und Verantwortung kann jedoch vom Ausbau- und Vertragsmodell abhängen. Maßgeblich sind Betreiberunterlagen und Eigentumsgrenzen des konkreten Projekts.</p><h2>Praxis</h2><p>Bei Störungen zuerst bestimmen, in welchem Bereich der Fehler liegt. So werden Tiefbau, Gebäudeverkabelung, optischer Netzabschluss und Heimnetz nicht miteinander vermischt.</p>' . $fiber_sources . '</article>',
            'router-kaufberatung' => '<article class="gk-clean-article">' . self::photo('wlan-heimnetz.png', 'Router mit LAN- und WLAN-Endgeräten in einem Heimnetz.', 'Der passende Router wird nach Anschlussart, Portgeschwindigkeit, Telefonie und Wohnsituation ausgewählt.') . '<h2>Routerwahl beginnt mit der Anschlussart</h2><table><thead><tr><th>Anschluss</th><th>Benötigte Schnittstelle</th></tr></thead><tbody><tr><td>DSL</td><td>passendes integriertes DSL-Modem</td></tr><tr><td>FTTH mit ONT</td><td>Ethernet-WAN-Port</td></tr><tr><td>FTTH direkt</td><td>kompatibler optischer Port und Anbieterfreigabe</td></tr></tbody></table><h2>Die wichtigsten Auswahlkriterien</h2><ul><li>WAN- und LAN-Ports passend zur gebuchten Datenrate</li><li>WLAN-Standard und räumliche Versorgung</li><li>Telefonie, DECT und vorhandene Endgeräte</li><li>Updateversorgung und Supportzeitraum</li><li>Mesh-, VPN- und Gastnetzfunktionen nach Bedarf</li></ul><h2>Praxisregel</h2><p>Ein teurer Router verbessert keine fehlerhafte Anschlussleitung und überwindet keine ungünstige Gebäudestruktur. Erst Anschlussart, Standort und Verkabelung klären; danach das Gerät auswählen.</p>' . $router_sources . '</article>',
            'router-kaufen-oder-mieten-vergleich' => '<article class="gk-clean-article">' . self::photo('wlan-heimnetz.png', 'Router als zentrale Verbindung zwischen Internetanschluss, LAN und WLAN.', 'Kauf und Miete unterscheiden sich vor allem bei Kosten, Support, Austausch und Gerätefreiheit.') . '<h2>Kaufen oder mieten: der sachliche Vergleich</h2><table><thead><tr><th>Kriterium</th><th>Mietrouter</th><th>Kaufrouter</th></tr></thead><tbody><tr><td>Kosten</td><td>laufend über die Vertragszeit</td><td>einmalig, gegebenenfalls längere Nutzung</td></tr><tr><td>Defekt</td><td>Austausch nach Vertragsbedingungen</td><td>Garantie, Gewährleistung oder eigener Ersatz</td></tr><tr><td>Support</td><td>meist eng mit Anbieterprozess verbunden</td><td>Hersteller und Händler</td></tr><tr><td>Auswahl</td><td>begrenztes Anbieterangebot</td><td>größere Modellfreiheit</td></tr></tbody></table><h2>Vor der Entscheidung rechnen</h2><p>Monatspreis mit realistischer Nutzungsdauer multiplizieren und Versand-, Bereitstellungs- sowie Rückgabebedingungen einbeziehen. Bei Anbieterwechsel prüfen, ob das Kaufgerät am neuen Anschluss technisch nutzbar ist.</p><h2>Technik bleibt entscheidend</h2><p>DSL-Modem, WAN-Port, Telefonie und Anbieterparameter müssen unabhängig vom Eigentumsmodell passen.</p>' . $router_sources . '</article>',
            'router-mieten-oder-kaufen' => '<article class="gk-clean-article">' . self::photo('wlan-heimnetz.png', 'Router mit kabelgebundenen und drahtlosen Endgeräten.', 'Die Entscheidung zwischen Miete und Kauf hängt vom Supportbedarf und der geplanten Nutzungsdauer ab.') . '<h2>Wann ein Mietrouter sinnvoll ist</h2><ul><li>ein zentraler Ansprechpartner für Anschluss und Gerät gewünscht ist</li><li>vertraglicher Austausch im Defektfall wichtig ist</li><li>keine eigene Modellauswahl und Einrichtung gewünscht ist</li></ul><h2>Wann ein Kaufrouter sinnvoll ist</h2><ul><li>ein bestimmtes Funktions- oder Anschlussprofil benötigt wird</li><li>das Gerät über längere Zeit genutzt werden soll</li><li>mehr Kontrolle über Updates, Konfiguration und Heimnetz gewünscht ist</li></ul><h2>Vorher verbindlich prüfen</h2><p>Anschlussart, Anbieterparameter, Telefonie, WAN-Geschwindigkeit und Rückgabepflichten des bisherigen Geräts klären. „Routerfreiheit“ bedeutet nicht, dass jedes beliebige Gerät technisch zu jedem Anschluss passt.</p>' . $router_sources . '</article>',
            'die-besten-router-fuer-glasfaseranschluesse-worauf-sollte-man-achten' => '<article class="gk-clean-article">' . self::photo('ont.png', 'ONT mit Ethernet-Ausgang für den WAN-Port eines Routers.', 'Hinter einem ONT benötigt der Router einen ausreichend schnellen Ethernet-WAN-Port.') . '<h2>Den „besten“ Glasfaserrouter gibt es nicht pauschal</h2><p>Entscheidend sind Anschlusskonzept, Tarifgeschwindigkeit, Wohnfläche, Telefonie und vorhandene Netzwerktechnik. Ein Modellvergleich ohne diese Angaben ist wenig belastbar.</p><h2>Mindestanforderungen festlegen</h2><ul><li>kompatibler Anschluss: Ethernet-WAN hinter ONT oder direkter Glasfaserport</li><li>WAN- und LAN-Geschwindigkeit ohne Flaschenhals</li><li>benötigte Telefonie- und DECT-Funktionen</li><li>WLAN-Abdeckung, Frequenzbänder und Mesh-Konzept</li><li>regelmäßige Sicherheitsupdates</li></ul><h2>Mehr als 1 Gbit/s</h2><p>Für Tarife oberhalb von 1 Gbit/s müssen WAN-Port, mindestens ein LAN-Port, Kabel und Endgerät die höhere Geschwindigkeit unterstützen. Sonst bleibt die Übertragung an einem langsameren Glied der Kette begrenzt.</p>' . $router_sources . '</article>',
            'router-fuer-glasfaser' => '<article class="gk-clean-article">' . self::photo('ont.png', 'ONT mit optischem Eingang und Ethernet-Ausgang.', 'Bei FTTH mit ONT wird der Router über Ethernet am WAN-Port angeschlossen.') . '<h2>Zwei technische Anschlussvarianten</h2><table><thead><tr><th>Variante</th><th>Verbindung</th></tr></thead><tbody><tr><td>ONT plus Router</td><td>Gf-TA → ONT → Ethernet-WAN des Routers</td></tr><tr><td>Glasfaserrouter</td><td>Gf-TA → kompatibles optisches Patchkabel beziehungsweise Modul → Router</td></tr></tbody></table><h2>Kompatibilität vor dem Kauf</h2><p>Bei direktem Glasfaseranschluss müssen Netzstandard, Wellenlänge, Steckertyp, Modul und Registrierungsverfahren zum Anbieter passen. Ein optischer Anschluss am Router allein garantiert keine Nutzbarkeit.</p><h2>Heimnetz passend dimensionieren</h2><p>WAN-, LAN- und WLAN-Leistung müssen zur Tarifrate und zu den Endgeräten passen. Für stationäre Arbeitsplätze, NAS und Access Points ist strukturierte Ethernetverkabelung die verlässlichste Basis.</p>' . $router_sources . '</article>',
            'router-glasfaser-kriterien' => '<article class="gk-clean-article">' . self::photo('wlan-heimnetz.png', 'Router mit WAN-, LAN- und WLAN-Verbindungen.', 'Bei der Auswahl zählen WAN-Port, lokale Schnittstellen, Funkversorgung und Anbieterkompatibilität.') . '<h2>Checkliste für einen Glasfaserrouter</h2><ul><li><strong>Anschluss:</strong> ONT per Ethernet oder direkte kompatible Glasfaser?</li><li><strong>WAN:</strong> Geschwindigkeit mindestens passend zum Tarif.</li><li><strong>LAN:</strong> Anzahl und Tempo der benötigten Ports.</li><li><strong>WLAN:</strong> Frequenzbänder, räumliche Versorgung und Client-Unterstützung.</li><li><strong>Telefonie:</strong> DECT, analoge Ports und Anbieteranforderungen.</li><li><strong>Betrieb:</strong> Updateversorgung, Support und Stromverbrauch.</li></ul><h2>Flaschenhälse vermeiden</h2><p>Ein 2,5-Gbit/s-Tarif bringt an einem 1-Gbit/s-WAN-Port nicht die volle Datenrate. Ebenso begrenzen langsame LAN-Ports, Kabel, Switches oder Endgeräte den Durchsatz.</p><h2>Standort mitplanen</h2><p>ONT und Router müssen nicht nebeneinander stehen. Ein Ethernetweg erlaubt häufig einen besseren Routerstandort im Wohnbereich.</p>' . $router_sources . '</article>',
            'glasfaserrouter-oder-ont' => '<article class="gk-clean-article">' . self::photo('ont.png', 'ONT mit optischem Eingang, Ethernet-Ausgang und Stromversorgung.', 'Beim getrennten Aufbau beendet der ONT die optische Verbindung und der Router übernimmt das Heimnetz.') . '<h2>Getrenntes oder kombiniertes Gerät?</h2><table><thead><tr><th>Aufbau</th><th>Vorteil</th><th>Zu beachten</th></tr></thead><tbody><tr><td>ONT plus Router</td><td>freie Routerplatzierung über Ethernet und einfacher Routerwechsel</td><td>zwei Geräte und zwei Stromversorgungen</td></tr><tr><td>Glasfaserrouter</td><td>weniger Geräte und direkte optische Verbindung</td><td>optische Anbieterkompatibilität und Standortbindung</td></tr></tbody></table><h2>Keine pauschale Qualitätsfrage</h2><p>Beide Varianten können technisch sauber arbeiten. Maßgeblich sind Betreiberfreigabe, optischer Standard, benötigte Schnittstellen und der sinnvolle Routerstandort.</p><h2>Vor dem Wechsel</h2><p>Registrierung, Zugangsdaten, Telefonie und Rückgabe eines Betreiber-ONT klären. Optische Stecker nicht ohne geeignete Prüfung und Reinigung umstecken.</p>' . $fiber_sources . '</article>',
            'ont-oder-glasfaserrouter' => '<article class="gk-clean-article">' . self::photo('ont.png', 'ONT mit optischem Eingang, Ethernet-Ausgang und Statusanzeigen.', 'ONT und Router erfüllen getrennte Aufgaben; ein Glasfaserrouter kombiniert sie in einem Gerät.') . '<h2>Die Aufgaben sauber trennen</h2><ul><li><strong>ONT:</strong> beendet die optische Teilnehmerverbindung und stellt Ethernet bereit.</li><li><strong>Router:</strong> baut den Internetzugang auf und versorgt LAN, WLAN und Telefonie.</li><li><strong>Glasfaserrouter:</strong> vereint optischen Abschluss und Routerfunktion.</li></ul><h2>Entscheidungskriterien</h2><p>ONT plus Router ist flexibel, wenn der Router zentral im Wohnbereich stehen soll. Ein direkt angeschlossener Glasfaserrouter reduziert Geräte, muss aber optisch und logisch zum Anbieteranschluss passen.</p><h2>Wichtig beim Anbieterwechsel</h2><p>Vorhandener ONT, Gerätekennung, Zugangsdaten, VLAN und Telefonie können anbieterabhängig sein. Vor einer Umstellung die schriftlichen Anschlussdaten des neuen Anbieters abwarten.</p>' . $fiber_sources . '</article>',
            'welche-fritzbox-fuer-glasfaser' => '<article class="gk-clean-article">' . self::photo('ont.png', 'ONT als Übergang von Glasfaser zu Ethernet.', 'Viele Router lassen sich hinter einem ONT über ihren Ethernet-WAN-Port nutzen; direkte Glasfasermodelle benötigen Netzkompatibilität.') . '<h2>Erst die Anschlussvariante bestimmen</h2><p>Hinter einem ONT kommt eine FRITZ!Box mit ausreichend schnellem Ethernet-WAN-Port infrage. Für den direkten optischen Anschluss wird ein dafür ausgelegtes Modell benötigt, das zum Netz des Anbieters passt.</p><h2>Danach Funktionen auswählen</h2><ul><li>WAN- und LAN-Geschwindigkeit</li><li>Wi-Fi-Generation und Wohnungsgröße</li><li>DECT, analoge Telefonanschlüsse und Telefonanlage</li><li>Mesh- und VPN-Funktionen</li><li>Updateversorgung und benötigte USB-/NAS-Funktionen</li></ul><h2>Modellnamen allein reichen nicht</h2><p>Hardwarevarianten und Anbieteranforderungen können sich ändern. Vor dem Kauf aktuelle Herstellerdaten und die Kompatibilitätsangaben des Anschlussanbieters prüfen.</p>' . $router_sources . '</article>',
            'welcher-router-fuer-glasfaser' => '<article class="gk-clean-article">' . self::photo('wlan-heimnetz.png', 'Router als Zentrale für Ethernet, WLAN und Heimnetzgeräte.', 'Der passende Glasfaserrouter ergibt sich aus Anschlussart, Geschwindigkeit und Heimnetzbedarf.') . '<h2>Entscheidung in vier Schritten</h2><ol><li>ONT oder direkter optischer Anschluss feststellen.</li><li>WAN- und LAN-Geschwindigkeit zum Tarif passend wählen.</li><li>Telefonie, Ports und Sonderfunktionen festlegen.</li><li>WLAN nach Gebäude und Endgeräten planen.</li></ol><h2>Typische Fehlkäufe</h2><ul><li>DSL-Router ohne nutzbaren Ethernet-WAN-Port hinter einem ONT</li><li>direkter Glasfaserrouter ohne Anbieterkompatibilität</li><li>1-Gbit/s-Port bei schnellerem Tarif</li><li>teures Spitzenmodell trotz ungeeignetem Kellerstandort</li></ul><h2>Anbieterwechsel vorbereiten</h2><p>Zugangsdaten, Telefonieparameter, VLAN, ONT-Nutzung und Freischaltverfahren vorab klären. Das alte Gerät erst nach erfolgreicher Inbetriebnahme und entsprechend den Rückgabefristen zurückgeben.</p>' . $router_sources . '</article>',
            'fritzbox-5690-pro-erklaert' => '<article class="gk-clean-article">' . self::photo('wlan-heimnetz.png', 'Modernes Heimnetz mit Router, Ethernet und mehreren WLAN-Frequenzbändern.', 'Die FRITZ!Box 5690 Pro kombiniert DSL, GPON/AON-Glasfaser, Wi-Fi 7 und 6-GHz-WLAN.') . '<h2>FRITZ!Box 5690 Pro richtig einordnen</h2><p>Das Modell ist für DSL und für kompatible GPON-/AON-Glasfaseranschlüsse ausgelegt. Zusätzlich kann der 2,5-Gbit/s-Port als WAN hinter einem externen ONT verwendet werden.</p><h2>Wichtige Merkmale</h2><ul><li>Wi-Fi 7 auf 2,4, 5 und 6 GHz</li><li>2,5-Gbit/s-WAN/LAN sowie vier Gigabit-LAN-Ports</li><li>Telefonanlage, DECT und Zigbee</li><li>direkter Glasfaserbetrieb nur bei Anbieter- und Netzkompatibilität</li></ul><h2>Für wen sinnvoll?</h2><p>Für Haushalte mit vielen modernen WLAN-Geräten, Bedarf am 6-GHz-Band oder geplantem Wechsel zwischen DSL und kompatibler Glasfaser. Ohne passende Endgeräte und guten Standort bleibt ein Teil der Leistung ungenutzt.</p><p><a href="https://fritz.com/en/products/fritz-box-5690-pro-20003043">Herstellerangaben zur FRITZ!Box 5690 Pro</a></p>' . $router_sources . '</article>',
            'fritzbox-7590-ax-erklaert' => '<article class="gk-clean-article">' . self::photo('wlan-heimnetz.png', 'DSL-Router mit LAN-, WLAN- und Telefonie-Endgeräten.', 'Die FRITZ!Box 7590 AX ist ein Wi-Fi-6-DSL-Router und kann über Gigabit-WAN hinter einem ONT arbeiten.') . '<h2>FRITZ!Box 7590 AX im Überblick</h2><ul><li>integriertes ADSL2+/VDSL-Modem bis 300 Mbit/s einschließlich Supervectoring</li><li>Wi-Fi 6 auf 2,4 und 5 GHz</li><li>ein Gigabit-WAN/LAN-Port und vier Gigabit-LAN-Ports</li><li>DECT, Telefonanlage und analoge Anschlüsse</li></ul><h2>DSL oder Glasfaser?</h2><p>Am DSL-Anschluss wird der DSL-Port verwendet. Hinter einem Glasfaser-ONT arbeitet die Box über den Gigabit-WAN-Port; dadurch liegt die kabelgebundene Obergrenze dieser Verbindung bei Gigabit-Ethernet.</p><h2>Wann passt sie?</h2><p>Für DSL-Haushalte mit Wi-Fi-6-Geräten und Telefoniebedarf. Für Tarife oberhalb von 1 Gbit/s oder Wi-Fi 7 ist ein aktuelleres Port- und Funkprofil sinnvoll.</p><p><a href="https://fritz.com/en/products/fritz-box-7590-ax-20002998">Herstellerangaben zur FRITZ!Box 7590 AX</a></p>' . $router_sources . '</article>',
            'fritzbox-7590-erklaert' => '<article class="gk-clean-article">' . self::photo('wlan-heimnetz.png', 'Router mit kabelgebundenem Heimnetz und Dualband-WLAN.', 'Die FRITZ!Box 7590 ist ein Wi-Fi-5-DSL-Router mit Gigabit-Schnittstellen.') . '<h2>FRITZ!Box 7590 heute einordnen</h2><p>Die 7590 unterstützt ADSL2+/VDSL einschließlich Supervectoring und besitzt Gigabit-LAN sowie einen umschaltbaren WAN-Port. Ihr WLAN basiert auf Wi-Fi 5 im 5-GHz-Band und Wi-Fi 4 bei 2,4 GHz.</p><h2>Weiterverwenden oder ersetzen?</h2><p>Für einen stabilen DSL-Anschluss, Gigabit-LAN und vorhandene ältere WLAN-Geräte kann sie weiterhin ausreichen. Ein Wechsel ist sinnvoll, wenn Wi-Fi 6/7, Multi-Gigabit-Ports oder ein langfristig moderneres Funknetz benötigt werden.</p><h2>Vor einem Neukauf</h2><p>Erst prüfen, ob die Begrenzung tatsächlich vom Router kommt. Schlechter Standort, Repeater-Uplink oder Endgerät werden durch einen Modellwechsel allein nicht automatisch besser.</p>' . $router_sources . '</article>',
            'fritzbox-7490-was-kann-der-klassiker-heute-noch' => '<article class="gk-clean-article">' . self::photo('wlan-heimnetz.png', 'Heimnetz mit älterem Dualband-Router und Ethernetgeräten.', 'Die FRITZ!Box 7490 gehört zur Wi-Fi-5-Generation und sollte nach aktuellem Sicherheits- und Leistungsbedarf bewertet werden.') . '<h2>Was die FRITZ!Box 7490 noch leisten kann</h2><p>Sie bietet Gigabit-LAN, Dualband-WLAN der Wi-Fi-5-/Wi-Fi-4-Generation, DECT und Telefoniefunktionen. Für einfache Anschlüsse und wenige Geräte kann das weiterhin genügen.</p><h2>Wo die Grenzen liegen</h2><ul><li>kein Wi-Fi 6 oder Wi-Fi 7</li><li>keine Multi-Gigabit-Ports</li><li>geringere Effizienz bei vielen modernen WLAN-Geräten</li><li>Alter von Netzteil und Hardware berücksichtigen</li></ul><h2>Sicher weiterbetreiben</h2><p>Aktuell angebotene Firmware installieren, Administratorkennwort prüfen und Fernzugänge nur gezielt aktivieren. Wenn keine sicherheitsrelevanten Aktualisierungen mehr bereitstehen oder Anforderungen steigen, sollte ein Ersatz geplant werden.</p>' . $router_sources . '</article>',
            'fritzbox-7690-dsl' => '<article class="gk-clean-article">' . self::photo('wlan-heimnetz.png', 'Wi-Fi-7-Router mit schnellen WAN- und LAN-Verbindungen.', 'Die FRITZ!Box 7690 verbindet VDSL bis 300 Mbit/s mit Wi-Fi 7 und 2,5-Gigabit-Schnittstellen.') . '<h2>FRITZ!Box 7690 für DSL einordnen</h2><ul><li>ADSL2+/VDSL bis 300 Mbit/s einschließlich Supervectoring</li><li>Wi-Fi 7 auf 2,4 und 5 GHz</li><li>2,5-Gbit/s-WAN/LAN und zusätzlicher 2,5-Gbit/s-LAN-Port</li><li>DECT, Telefonie und Zigbee</li></ul><h2>Wann lohnt sie sich?</h2><p>Vor allem bei modernen WLAN-Clients, schnellem lokalen Netzwerk oder geplanter Nutzung hinter einem ONT. Die DSL-Leitung selbst wird durch Wi-Fi 7 nicht schneller als ihr synchronisiertes Profil.</p><h2>Wichtige Abgrenzung</h2><p>Die 7690 ist kein direkter Glasfaserrouter. Am FTTH-Anschluss wird sie per Ethernet hinter einem ONT betrieben.</p><p><a href="https://fritz.com/en/products/fritz-box-7690-20003057">Herstellerangaben zur FRITZ!Box 7690</a></p>' . $router_sources . '</article>',
            'speedport-smart-4-erklaert' => '<article class="gk-clean-article">' . self::photo('wlan-heimnetz.png', 'Router mit DSL-, WAN-, LAN- und WLAN-Verbindungen.', 'Der Speedport Smart 4 unterstützt DSL und den Betrieb über WAN hinter einem Glasfasermodem.') . '<h2>Speedport Smart 4 richtig anschließen</h2><p>Bei DSL wird der DSL-Port mit der ersten TAE verbunden. Bei FTTH mit externem Glasfasermodem beziehungsweise ONT führt ein Ethernetkabel vom Modem zum WAN-Port des Speedport.</p><h2>Wichtige Schnittstellen</h2><ul><li>Wi-Fi 6 auf 2,4 und 5 GHz</li><li>drei Gigabit-LAN-Ports</li><li>WAN-Port für externes Glasfasermodem</li><li>analoger Telefonanschluss und USB</li></ul><h2>Typische Fehler</h2><p>WAN und LAN verwechseln, Router im Keller ungünstig platzieren oder WLAN messen, bevor die kabelgebundene Verbindung funktioniert. Statusanzeige und Ereignisse zuerst dokumentieren.</p><p><a href="https://www.telekom.de/shop/wlan-und-router/telekom/speedport-smart-4/speedport">Telekom-Produktangaben zum Speedport Smart 4</a></p>' . $router_sources . '</article>',
            'speedport-smart-4-plus-erklaert' => '<article class="gk-clean-article">' . self::photo('ont.png', 'Optischer Netzabschluss mit Glasfaser- und Ethernetverbindung.', 'Der Speedport Smart 4 Plus besitzt ein integriertes GPON-Glasfasermodem und kann alternativ hinter einem externen Modem arbeiten.') . '<h2>Was unterscheidet den Smart 4 Plus?</h2><p>Der Smart 4 Plus kann an einem kompatiblen Telekom-GPON-Anschluss direkt optisch betrieben werden. Alternativ ist der Betrieb über ein vorhandenes externes Glasfasermodem vorgesehen.</p><h2>Vor dem Anschluss</h2><ul><li>prüfen, ob direkter GPON-Betrieb für den Anschluss vorgesehen ist</li><li>Modem-ID und Aktivierungsprozess beachten</li><li>passendes LC/APC-Patchkabel nach Anleitung verwenden</li><li>altes Gerät bis zur erfolgreichen Umstellung bereithalten</li></ul><h2>Nicht einfach umstecken</h2><p>Ein direkter Glasfaserrouter muss beim Anbieter dem Anschluss zugeordnet werden. Ohne passende Registrierung kann trotz physisch korrekter Verbindung kein Dienst entstehen.</p><p><a href="https://www.telekom.de/hilfe/downloads/bedienungsanleitung-speedport-smart-4-plus.pdf">Telekom-Bedienungsanleitung Speedport Smart 4 Plus</a></p>' . $fiber_sources . '</article>',
            'fritzbox-richtig-einrichten-schritt-fuer-schritt' => '<article class="gk-clean-article">' . self::photo('wlan-heimnetz.png', 'Router mit Internet-, LAN-, WLAN- und Telefonieverbindungen.', 'Die Einrichtung beginnt mit der richtigen Anschlussart und endet mit einem getrennten LAN- und WLAN-Test.') . '<h2>FRITZ!Box in sieben Schritten einrichten</h2><ol><li>DSL-Port, Ethernet-WAN oder direkten Glasfaseranschluss bestimmen.</li><li>Router mit passendem Kabel verbinden und vollständig starten lassen.</li><li>Per LAN oder Geräte-WLAN mit der Benutzeroberfläche verbinden.</li><li>Internetanbieter auswählen und erforderliche Zugangsdaten eintragen.</li><li>FRITZ!OS aktualisieren und Sicherung anlegen.</li><li>Telefonie, WLAN-Namen und sicheres Kennwort konfigurieren.</li><li>Internetzugang zuerst per LAN, danach WLAN an mehreren Orten testen.</li></ol><h2>Bei FTTH hinter ONT</h2><p>Das Ethernetkabel gehört vom ONT an den vorgesehenen WAN-Port. Der DSL-Port bleibt unbenutzt. Anbieterparameter wie VLAN oder Zugangsdaten müssen der Anschlussdokumentation entsprechen.</p><h2>Sicherheit</h2><p>Individuelles Administratorkennwort verwenden, ungenutzte Freigaben deaktivieren und automatische Updates nach Herstellerempfehlung konfigurieren.</p>' . $router_sources . '</article>',
            'fritzbox-richtig-einrichten-premium' => '<article class="gk-clean-article">' . self::photo('wlan-heimnetz.png', 'Strukturiertes Heimnetz mit Router, Switch, Access Point und Endgeräten.', 'Nach der Grundinstallation werden Sicherheit, Telefonie und Heimnetz gezielt eingerichtet.') . '<h2>Einrichtung mit sauberer Prüfreihenfolge</h2><ol><li><strong>Anschluss:</strong> DSL, ONT-WAN oder kompatible Direktfaser korrekt verbinden.</li><li><strong>Internetzugang:</strong> Anbieterprofil und Zugangsdaten prüfen.</li><li><strong>Update:</strong> aktuelle Firmware installieren.</li><li><strong>LAN:</strong> Portgeschwindigkeit und kabelgebundenen Durchsatz testen.</li><li><strong>WLAN:</strong> Standort, Frequenzbänder und Mesh planen.</li><li><strong>Telefonie:</strong> Rufnummern registrieren und ein-/ausgehende Gespräche testen.</li><li><strong>Sicherung:</strong> geprüfte Konfiguration exportieren.</li></ol><h2>Fehler nicht vermischen</h2><p>Fehlende DSL-Synchronisation, rote LOS-Anzeige, gescheiterte Einwahl und langsames WLAN sind unterschiedliche Fehlerklassen. Jede wird an ihrer eigenen Schnittstelle geprüft.</p><h2>Dokumentation</h2><p>Routermodell, Firmware, Anschlussart, Portbelegung und besondere Anbieterparameter festhalten. Das spart Zeit bei späteren Änderungen.</p>' . $router_sources . '</article>',
            'router-richtig-anschliessen' => '<article class="gk-clean-article">' . self::photo('wlan-heimnetz.png', 'Router als Übergang vom Anschluss zu LAN- und WLAN-Endgeräten.', 'DSL, FTTH mit ONT und direkter Glasfaseranschluss verwenden unterschiedliche Routerports.') . '<h2>Den richtigen Port verwenden</h2><table><thead><tr><th>Anschlussart</th><th>Verbindung</th></tr></thead><tbody><tr><td>DSL</td><td>erste TAE → DSL-Kabel → DSL-Port</td></tr><tr><td>FTTH mit ONT</td><td>Gf-TA → ONT → Ethernetkabel → WAN-Port</td></tr><tr><td>direkte Glasfaser</td><td>Gf-TA → passendes optisches Patchkabel/Modul → kompatibler Glasfaserrouter</td></tr></tbody></table><h2>Nach dem Verkabeln</h2><ol><li>Statusanzeigen vollständig abwarten.</li><li>Internetzugang per LAN prüfen.</li><li>Portgeschwindigkeit kontrollieren.</li><li>Erst danach WLAN und Mesh einrichten.</li></ol><h2>Häufige Fehler</h2><p>ONT am DSL-Port, WAN-Kabel an einem normalen LAN-Port, ungeeignetes optisches Patchkabel, geknickte Faser oder ein 1-Gbit/s-Port als Flaschenhals. Anschlussanleitung des konkreten Geräts hat Vorrang.</p>' . $router_sources . '</article>',
        ];
    }

    public static function start_buffer(): void {
        if (is_admin() || wp_doing_ajax() || wp_is_json_request()) { return; }
        $request_path = trim((string) parse_url((string) ($_SERVER['REQUEST_URI'] ?? ''), PHP_URL_PATH), '/');
        self::$is_legal = is_page(['impressum-2', 'datenschutz-2', 'kontakt-2']) || in_array($request_path, ['impressum-2', 'datenschutz-2', 'kontakt-2'], true);
        self::$is_front = is_front_page();
        self::$slug = is_singular() ? (string) get_post_field('post_name', get_queried_object_id()) : '';
        ob_start([self::class, 'clean_html']);
    }

    public static function legal_visibility_guard(): void {
        $request_path = trim((string) parse_url((string) ($_SERVER['REQUEST_URI'] ?? ''), PHP_URL_PATH), '/');
        if (!in_array($request_path, ['impressum-2', 'datenschutz-2', 'kontakt-2'], true)) { return; }
        echo '<style id="gk-final-legal-guard">.gk9-tarifcheck,.gkpr-affiliate,.gk9-authorbox,.gkpr-author{display:none!important}</style>';
    }

    public static function author_name($name): string {
        $name = trim(wp_strip_all_tags((string) $name));
        return $name !== '' ? $name : self::AUTHOR_NAME;
    }

    public static function author_link($url): string {
        return self::AUTHOR_URL;
    }

    public static function footer($text): string {
        return 'Copyright © ' . wp_date('Y') . ' Glasfaser-Kompass';
    }

    public static function social_image($url): string {
        if (is_singular()) {
            $slug = self::$slug !== '' ? self::$slug : (string) get_post_field('post_name', get_queried_object_id());
            if (str_contains($slug, 'apl') || str_contains($slug, 'tae') || str_contains($slug, 'dsl')) {
                return home_url('/wp-content/plugins/gk-render-guard/assets/apl.png');
            }
            if (preg_match('/router|wlan|mesh|repeater|fritzbox|speedport/', $slug)) {
                return home_url('/wp-content/plugins/gk-render-guard/assets/wlan-heimnetz.png');
            }
            if (str_contains($slug, 'gf-ap') || str_contains($slug, 'glasfaser') || str_contains($slug, 'ftth')) {
                return home_url('/wp-content/plugins/gk-render-guard/assets/gf-ap.png');
            }
            if (str_contains($slug, 'ont')) {
                return home_url('/wp-content/plugins/gk-render-guard/assets/ont.png');
            }
        }
        return (string) $url;
    }

    private static function strip_dynamic_sections(string $html): string {
        $classes = '(?:gk9-tarifcheck|gk9-authorbox|gkpr-affiliate|gkpr-author)';
        $pattern = '~<section\b[^>]*class=(["\'])[^"\']*' . $classes . '[^"\']*\1[^>]*>.*?</section>~is';
        return (string) preg_replace($pattern, '', $html);
    }

    public static function clean_html(string $html): string {
        $html = str_replace(
            [
                '/dsl-stoerungen-verstehen-und-beheben/',
                '/glasfaseranschluss-einfach-erklaert-der-grosse-ratgeber/',
                'https://glasfaser-kompass.de/author/',
                'Präsentiert von Astra-WordPress-Theme',
                'Proudly powered by Astra WordPress Theme',
            ],
            [
                '/dsl-stoerungen-verstehen/',
                '/glasfaseranschluss-erklaert/',
                self::AUTHOR_URL,
                '',
                '',
            ],
            $html
        );

        if (self::$is_legal) {
            $html = self::strip_dynamic_sections($html);
        }

        if (self::$slug === 'dslam-erklaert') {
            /* Ein älterer Renderer hängt diesen unvollständigen Block nach dem
               reparierten Artikel an und überspringt darin den KVz. */
            $html = (string) preg_replace(
                '~<h2\b[^>]*>\s*Technischer Signalweg bei VDSL\s*</h2>.*?Bei reinen FTTH-Glasfaseranschlüssen.*?</p>~is',
                '',
                $html,
                1
            );
        }

        if (in_array(self::$slug, ['gf-ap-erklaert', 'gf-ta-erklaert', 'ont-erklaert', 'router-im-keller', 'routerstandort-optimieren', 'ont-und-router-unterschied-premium', 'access-point-oder-repeater', 'mesh-wlan-erklaert', 'repeater-erklaert', '2-4-ghz-5-ghz-oder-6-ghz', 'wlan-kanal-wechseln', 'wifi-7-erklaert', 'repeater-richtig-platzieren', 'dsl-stoerung-systematisch-eingrenzen', 'dsl-synchronisiert-nicht', 'dsl-ausfall-bei-regen-die-haeufigsten-ursachen', 'endleitung-dsl-probleme', 'crc-fehler-erklaert-was-sie-ueber-eine-dsl-leitung-aussagen', 'fec-fehler-richtig-interpretieren', 'snr-stoerabstandsmarge-erklaert', 'was-prueft-ein-techniker-bei-einer-entstoerung', 'technikertermin-dsl-vorbereiten', 'warum-wird-an-der-ersten-tae-gemessen', 'fehler-beim-glasfaseranschluss', 'haeufige-fehler-beim-ftth-anschluss', 'glasfaser-pegelmessung-verstehen', 'pegelmessung-erklaert', 'daempfung-im-glasfasernetz', 'los-rot-glasfaser', 'technikertermin-glasfaser-vorbereiten', 'internet-langsam-trotz-glasfaser-woran-kann-das-liegen', 'ont-standort-worauf-achten', 'gf-ap-montageort-planen', 'glasfaser-hausanschluss-erklaert', 'glasfaser-hausanschluss-checkliste', 'glasfaser-im-einfamilienhaus', 'glasfaser-im-mehrfamilienhaus', 'glasfaser-fuer-mehrfamilienhaeuser', 'glasfaseranschluss-im-einfamilienhaus-erklaert', 'glasfaseranschluss-im-mehrfamilienhaus-erklaert', 'hausbegehung-akp-glasfaser', 'wie-kommt-glasfaser-ins-haus', 'netzebenen-im-glasfaserausbau', 'router-kaufberatung', 'router-kaufen-oder-mieten-vergleich', 'router-mieten-oder-kaufen', 'die-besten-router-fuer-glasfaseranschluesse-worauf-sollte-man-achten', 'router-fuer-glasfaser', 'router-glasfaser-kriterien', 'glasfaserrouter-oder-ont', 'ont-oder-glasfaserrouter', 'welche-fritzbox-fuer-glasfaser', 'welcher-router-fuer-glasfaser', 'fritzbox-5690-pro-erklaert', 'fritzbox-7590-ax-erklaert', 'fritzbox-7590-erklaert', 'fritzbox-7490-was-kann-der-klassiker-heute-noch', 'fritzbox-7690-dsl', 'speedport-smart-4-erklaert', 'speedport-smart-4-plus-erklaert', 'fritzbox-richtig-einrichten-schritt-fuer-schritt', 'fritzbox-richtig-einrichten-premium', 'router-richtig-anschliessen'], true)) {
            /* Diese Beiträge zeigen das kuratierte Bauteilbild bereits im
               Fachartikel. Das Theme-Featured-Image wäre exakt dieselbe Datei. */
            $html = (string) preg_replace(
                '~<div\b[^>]*class=(["\'])[^"\']*ast-single-post-featured-section[^"\']*\1[^>]*>.*?</div>~is',
                '',
                $html,
                1
            );
        }

        if (self::$is_front) {
            $html = (string) preg_replace(
                '~(<h1\b[^>]*>)\s*Startseite\s*(</h1>)~iu',
                '$1' . self::HOME_TITLE . '$2',
                $html,
                1
            );
            $html = str_replace(
                ['<title>Startseite - glasfaser-kompass.de</title>', '<title>Startseite – glasfaser-kompass.de</title>'],
                '<title>' . self::HOME_TITLE . ' – Glasfaser-Kompass</title>',
                $html
            );
        }

        $html = (string) preg_replace(
            "~<div class=([\\\"'])ast-footer-copyright\\1><p>.*?</p>\\s*</div>~is",
            '<div class="ast-footer-copyright"><p>Copyright © ' . wp_date('Y') . ' Glasfaser-Kompass</p></div>',
            $html,
            1
        );

        $social = self::social_image('');
        if ($social !== '') {
            $escaped = esc_url($social);
            $html = (string) preg_replace("~<meta\\b[^>]*(?:property|name)=([\\\"'])(?:og:image|twitter:image)\\1[^>]*>\\s*~is", '', $html);
            $html = str_replace('</head>', '<meta property="og:image" content="' . $escaped . '"><meta name="twitter:image" content="' . $escaped . '"></head>', $html);
        }
        $html = (string) preg_replace("~<meta\\b[^>]*name=([\\\"'])twitter:card\\1[^>]*>\\s*~is", '', $html);
        $html = str_replace('</head>', '<meta name="twitter:card" content="summary_large_image"></head>', $html);

        return $html;
    }
}

GK_Final_Frontend_Guard::boot();
