Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$snapshot=Get-Content (Join-Path $env:GITHUB_WORKSPACE 'bridge/gk-offline-snapshot.json') -Encoding UTF8 -Raw|ConvertFrom-Json
$all=@($snapshot.pages)+@($snapshot.posts)
function Get-Item([int]$Id){$x=@($all|Where-Object{[int]$_.id-eq$Id});if($x.Count-ne1){throw "Target $Id missing or ambiguous"};$x[0]}
function Plain-Words([string]$Html){$t=[Net.WebUtility]::HtmlDecode([regex]::Replace($Html,'<[^>]+>',' '));@([regex]::Matches($t,'\b[\p{L}\p{N}][\p{L}\p{N}\-]*\b')).Count}
function Simulate-Update($Source,[string]$Content,[Nullable[int]]$FeaturedMedia){
  $response=[ordered]@{id=[int]$Source.id;modified='SIMULATED';content=[ordered]@{raw=$Content};featured_media=if($null-ne$FeaturedMedia){[int]$FeaturedMedia}else{[int]$Source.featured_media}}
  if($response.id-ne[int]$Source.id){throw 'Simulated response mismatch'};$response
}
$routerFiber=@'
<article class="gk-clean-article" data-gk-revision="pilot-v1">
<header class="gk-design-hero"><p class="gk-design-kicker">Kaufberatung</p><p class="gk-design-lead">Ein Glasfaserrouter muss zuerst zur Anschlussart passen. Danach entscheiden WAN-Leistung, WLAN, Telefonie und Updateversorgung.</p></header>
<nav class="gk-design-toc" aria-label="Inhalt"><a href="#anschluss">Anschluss kl&auml;ren</a><a href="#auswahl">Auswahlkriterien</a><a href="#entscheidung">Entscheidung</a><a href="#faq">FAQ</a></nav>
<section id="anschluss"><h2>Erst ONT oder Direktanschluss kl&auml;ren</h2><p>Bei vielen FTTH-Anschl&uuml;ssen endet die Glasfaser an einem separaten ONT. Dieser wandelt das optische Signal in Ethernet um. In diesem Fall ben&ouml;tigen Sie keinen Router mit eingebautem Glasfasermodem, sondern einen Router mit ausreichend schnellem WAN-Port. Soll die Faser direkt in den Router f&uuml;hren, m&uuml;ssen Steckertyp, optisches Modul, Netztechnik und Freigabe des Anbieters zusammenpassen.</p><div class="gk-design-tip"><h3>Praxisregel</h3><p>Steckt bereits ein Netzwerkkabel zwischen ONT und Router, ist ein guter Ethernet-WAN-Router meist die flexibelste Wahl.</p></div></section>
<section id="auswahl"><h2>Die f&uuml;nf wichtigen Auswahlkriterien</h2><ol><li><strong>WAN-Durchsatz:</strong> Der Port muss den gebuchten Tarif ohne Engpass verarbeiten. F&uuml;r Tarife oberhalb von 1 Gbit/s ist ein Multi-Gigabit-WAN-Port erforderlich.</li><li><strong>WLAN-Abdeckung:</strong> Ein moderner WLAN-Standard hilft, ersetzt aber keinen guten Standort. In gro&szlig;en H&auml;usern sind Access Points oder Mesh mit Kabelanbindung oft sinnvoller als ein besonders teurer Einzelrouter.</li><li><strong>Telefonie:</strong> Pr&uuml;fen Sie vor dem Kauf, ob DECT, analoge Anschl&uuml;sse und die Zugangsdaten Ihres Anbieters unterst&uuml;tzt werden.</li><li><strong>Netzwerkanschl&uuml;sse:</strong> Anzahl und Geschwindigkeit der LAN-Ports m&uuml;ssen zu NAS, PC, Switch und Access Points passen.</li><li><strong>Updates:</strong> Regelm&auml;&szlig;ige Sicherheitsupdates und ein nachvollziehbarer Supportzeitraum sind wichtiger als selten genutzte Zusatzfunktionen.</li></ol></section>
<section><h2>ONT plus Router oder integriertes Glasfasermodem?</h2><table><thead><tr><th>Variante</th><th>Vorteil</th><th>Darauf achten</th></tr></thead><tbody><tr><td>Separater ONT</td><td>Gro&szlig;e Routerauswahl, einfacher Ger&auml;tewechsel</td><td>ONT braucht Strom; Router ben&ouml;tigt WAN-Port</td></tr><tr><td>Direkter Glasfaserrouter</td><td>Ein Ger&auml;t, weniger Kabel und Netzteile</td><td>Kompatibilit&auml;t muss vor dem Kauf best&auml;tigt sein</td></tr></tbody></table></section>
<section id="entscheidung"><h2>Empfehlung nach Wohnsituation</h2><ul><li><strong>Wohnung:</strong> Ein zentral platzierter Router mit Gigabit-WAN reicht h&auml;ufig aus.</li><li><strong>Einfamilienhaus:</strong> Planen Sie LAN-Leitungen und mindestens einen zus&auml;tzlichen Access Point ein.</li><li><strong>Homeoffice oder Gaming:</strong> Endger&auml;te nach M&ouml;glichkeit per LAN anschlie&szlig;en.</li><li><strong>Viele schnelle Ger&auml;te:</strong> Multi-Gigabit-Ports und eine passende Switch-Struktur ber&uuml;cksichtigen.</li></ul><p>Kaufen Sie nicht allein nach der h&ouml;chsten WLAN-Zahl auf der Verpackung. Entscheidend ist die langsamste Stelle zwischen Anschluss, Router, Verkabelung und Endger&auml;t.</p></section>
<section class="gk-related-box"><h2>Vor dem Kauf pr&uuml;fen</h2><ul><li>Ist ein ONT vorhanden oder wird die Faser direkt angeschlossen?</li><li>Welche Zugangsdaten und Telefoniefunktionen stellt der Anbieter bereit?</li><li>Wo kann der Router zentral und frei stehen?</li><li>Welche R&auml;ume ben&ouml;tigen LAN oder einen Access Point?</li></ul></section>
<section id="faq" class="gk-faq-box"><h2>H&auml;ufige Fragen</h2><h3>Brauche ich f&uuml;r Glasfaser zwingend einen speziellen Router?</h3><p>Nein. Hinter einem ONT gen&uuml;gt ein geeigneter Router mit Ethernet-WAN. Nur beim direkten Faseranschluss ist ein kompatibles Glasfasermodem erforderlich.</p><h3>Verbessert ein neuer Router automatisch das WLAN?</h3><p>Nicht unbedingt. Standort, W&auml;nde, Funkbelegung und die F&auml;higkeiten der Endger&auml;te beeinflussen das Ergebnis ebenso stark.</p></section>
</article>
'@
$routerPlace=@'
<article class="gk-clean-article" data-gk-revision="pilot-v1">
<header class="gk-design-hero"><p class="gk-design-kicker">WLAN-Praxis</p><p class="gk-design-lead">Der beste Router bringt wenig, wenn er im Keller, im Schrank oder hinter Metall steht. Mit sieben klaren Regeln verbessern Sie die Abdeckung ohne Fehlkauf.</p></header>
<nav class="gk-design-toc" aria-label="Inhalt"><a href="#tipps">7 Regeln</a><a href="#test">Richtig testen</a><a href="#erweitern">Netz erweitern</a><a href="#faq">FAQ</a></nav>
<section id="tipps"><h2>Sieben Regeln f&uuml;r einen guten Routerstandort</h2><ol><li><strong>M&ouml;glichst zentral:</strong> Stellen Sie den Router nahe der Mitte des versorgten Wohnbereichs auf. Ein Standort am &auml;u&szlig;eren Ende des Hauses verschenkt Reichweite.</li><li><strong>Nicht auf den Boden:</strong> Eine erh&ouml;hte, freie Position auf einem Regal oder an der Wand ist meist besser als der Platz unter dem Schreibtisch.</li><li><strong>Abstand zu Metall:</strong> Verteilerk&auml;sten, Heizk&ouml;rper, gro&szlig;e Elektroger&auml;te und metallbeschichtete Fl&auml;chen schw&auml;chen oder reflektieren Funksignale.</li><li><strong>Nicht im geschlossenen Schrank:</strong> M&ouml;bel d&auml;mpfen das Signal und k&ouml;nnen die W&auml;rmeabfuhr verschlechtern.</li><li><strong>St&ouml;rquellen vermeiden:</strong> Halten Sie Abstand zu Mikrowelle, Babyphone, Funkbasis und dicht gedr&auml;ngter Unterhaltungselektronik.</li><li><strong>Keller nicht mit Wohnraum verwechseln:</strong> ONT und Router m&uuml;ssen nicht nebeneinander stehen. Ein Netzwerkkabel kann den Router vom Hausanschluss zu einem besseren Standort f&uuml;hren.</li><li><strong>Antennen nicht verstecken:</strong> Lassen Sie um das Ger&auml;t Platz und beachten Sie die Aufstellungsempfehlung des Herstellers.</li></ol></section>
<section id="test"><h2>Verbesserungen sauber messen</h2><p>Pr&uuml;fen Sie zuerst per LAN, ob die gebuchte Anschlussleistung am Router ankommt. Testen Sie danach an denselben WLAN-Messpunkten und mit demselben Endger&auml;t. Notieren Sie Signal, Geschwindigkeit und Stabilit&auml;t, bevor Sie den Standort ver&auml;ndern. So erkennen Sie, ob die Ma&szlig;nahme wirklich hilft.</p><div class="gk-design-tip"><h3>Wichtig</h3><p>Ein einzelner Speedtest ist kein Beweis. Vergleichen Sie mehrere Messungen in unterschiedlichen R&auml;umen und zu unterschiedlichen Zeiten.</p></div></section>
<section><h2>2,4 GHz, 5 GHz und 6 GHz richtig nutzen</h2><table><thead><tr><th>Band</th><th>St&auml;rke</th><th>Typischer Einsatz</th></tr></thead><tbody><tr><td>2,4 GHz</td><td>Mehr Reichweite, weniger Tempo</td><td>Entfernte oder einfache Ger&auml;te</td></tr><tr><td>5 GHz</td><td>Gute Balance aus Tempo und Reichweite</td><td>Notebook, Smartphone, Streaming</td></tr><tr><td>6 GHz</td><td>Viel Kapazit&auml;t auf kurze Distanz</td><td>Moderne Ger&auml;te im selben oder benachbarten Raum</td></tr></tbody></table><p>Die B&auml;nder erg&auml;nzen sich. Erzwingen Sie nicht pauschal ein Band, sondern pr&uuml;fen Sie die tats&auml;chliche Verbindung am jeweiligen Standort.</p></section>
<section id="erweitern"><h2>Wenn ein besserer Standort nicht reicht</h2><p>Ein Repeater kann ein einzelnes Funkloch schlie&szlig;en, braucht aber selbst noch ein gutes Signal. F&uuml;r mehrere Etagen sind per Netzwerkkabel angebundene Access Points oder ein Mesh-System mit LAN-Backhaul meist stabiler. Powerline ist stark von der Elektroinstallation abh&auml;ngig und sollte nicht die erste Wahl sein.</p><ul><li><strong>Ein Raum betroffen:</strong> Standort optimieren oder Repeater sinnvoll zwischen Router und Zielraum platzieren.</li><li><strong>Mehrere Etagen:</strong> LAN-Verkabelung und Access Points planen.</li><li><strong>Neubau oder Sanierung:</strong> Netzwerkkabel zu zentralen Decken- oder Wandpunkten vorsehen.</li></ul></section>
<section id="faq" class="gk-faq-box"><h2>H&auml;ufige Fragen</h2><h3>Darf der Router neben dem ONT im Keller bleiben?</h3><p>Technisch ja, f&uuml;r die WLAN-Abdeckung ist das aber oft ung&uuml;nstig. Die Verbindung zwischen ONT und Router kann in der Regel &uuml;ber ein Netzwerkkabel verl&auml;ngert werden.</p><h3>Hilft ein st&auml;rkerer Router durch Stahlbetondecken?</h3><p>Nur begrenzt. Ein gut platzierter Access Point auf der anderen Etage ist meist zuverl&auml;ssiger.</p></section>
</article>
'@
$targets=@()
$dsl=Get-Item 21005;$dslRaw=[string]$dsl.content.raw;$media=@($snapshot.media|Where-Object{[int]$_.id-eq29398});if($media.Count-ne1){throw 'Media 29398 missing'}
$needle=[IO.Path]::GetFileName(([uri][string]$media[0].source_url).AbsolutePath)
$dslNew=[regex]::Replace($dslRaw,'(?is)<!--\s*wp:image\b.*?'+[regex]::Escape($needle)+'.*?<!--\s*\/wp:image\s*-->','')
$dslNew=[regex]::Replace($dslNew,'(?is)<figure\b[^>]*>.*?'+[regex]::Escape($needle)+'.*?</figure>','')
$dslFeatured=[int]$dsl.featured_media;if($dslFeatured-eq29398){$dslFeatured=0}
$encodingMatches=@([regex]::Matches($dslNew,'[\u00C2\u00C3\u00E2]'))
if($encodingMatches.Count-gt0){
  $contexts=@();foreach($m in $encodingMatches){$start=[Math]::Max(0,$m.Index-45);$length=[Math]::Min(100,$dslNew.Length-$start);$contexts+=[ordered]@{index=$m.Index;code_unit=[int][char]$m.Value;context=$dslNew.Substring($start,$length)}}
  $blocked=[ordered]@{generated_utc=(Get-Date).ToUniversalTime().ToString('o');source_snapshot_utc=[string]$snapshot.captured_utc;offline_only=$true;production_writes=0;target_count=0;blocked_target_id=21005;encoding_match_count=$encodingMatches.Count;encoding_contexts=$contexts;status='OFFLINE_PILOT_BLOCKED_EXISTING_ENCODING'}
  [IO.File]::WriteAllText((Join-Path $env:GITHUB_WORKSPACE 'bridge/gk-offline-pilot.json'),($blocked|ConvertTo-Json -Depth 20),(New-Object Text.UTF8Encoding($false)))
  Write-Host "Offline pilot blocked by existing DSL encoding: matches=$($encodingMatches.Count), writes=0"
  exit 0
}
if($dslNew-eq$dslRaw -and [int]$dsl.featured_media-ne29398){throw 'Wrong DSL image not found in inline or featured media'}
$targets+=[ordered]@{id=21005;action='remove_wrong_media_29398';source_modified=[string]$dsl.modified;content=$dslNew;featured_media=$dslFeatured;simulated_response=(Simulate-Update $dsl $dslNew $dslFeatured)}
foreach($spec in @(@{id=298;html=$routerFiber;action='replace_layered_router_guide'},@{id=163;html=$routerPlace;action='replace_layered_router_placement'})){
 $x=Get-Item $spec.id;$html=[string]$spec.html
 if((Plain-Words $html)-lt350){throw "Replacement $($spec.id) too thin"}
 if($html-match '(?i)<h1\b|<img\b|\.svg|gk-premium-article|gk-editorial-article|Expert Upgrade|Knowledge Upgrade|Dieser Abschnitt erweitert'){throw "Replacement $($spec.id) failed quality gate"}
 if(([regex]::Matches($html,'<article\b','IgnoreCase')).Count-ne1){throw "Replacement $($spec.id) wrapper gate"}
 $targets+=[ordered]@{id=[int]$spec.id;action=$spec.action;source_modified=[string]$x.modified;content=$html;featured_media=0;simulated_response=(Simulate-Update $x $html 0)}
}
$out=[ordered]@{generated_utc=(Get-Date).ToUniversalTime().ToString('o');source_snapshot_utc=[string]$snapshot.captured_utc;offline_only=$true;production_writes=0;target_count=$targets.Count;targets=$targets;status='OFFLINE_PILOT_FULL_SIMULATION_PASSED'}
[IO.File]::WriteAllText((Join-Path $env:GITHUB_WORKSPACE 'bridge/gk-offline-pilot.json'),($out|ConvertTo-Json -Depth 30),(New-Object Text.UTF8Encoding($false)))
Write-Host "Offline pilot built and simulated: targets=$($targets.Count), writes=0"

