param([switch]$Simulation)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
function Get-PlainSecret([string]$Path){$s=Get-Content $Path|ConvertTo-SecureString;$p=[Runtime.InteropServices.Marshal]::SecureStringToBSTR($s);try{[Runtime.InteropServices.Marshal]::PtrToStringBSTR($p)}finally{[Runtime.InteropServices.Marshal]::ZeroFreeBSTR($p)}}
function Parse-Utf8($Response){$text=[Text.Encoding]::UTF8.GetString($Response.RawContentStream.ToArray());if([string]::IsNullOrWhiteSpace($text)){return $null};ConvertFrom-Json $text}
function Invoke-Wp([string]$Method,[string]$Path,[hashtable]$Headers,[object]$Body=$null){$p=@{Uri=('https://glasfaser-kompass.de/wp-json'+$Path);Method=$Method;Headers=$Headers;UseBasicParsing=$true;TimeoutSec=180};if($null-ne$Body){$json=$Body|ConvertTo-Json -Depth 30 -Compress;$p.Body=[Text.Encoding]::UTF8.GetBytes($json);$p.ContentType='application/json; charset=utf-8'};Parse-Utf8 (Invoke-WebRequest @p)}
function Public-Probe([string]$Url,[int]$Id){$r=Invoke-WebRequest -Uri $Url -UseBasicParsing -TimeoutSec 120;$h=[Text.Encoding]::UTF8.GetString($r.RawContentStream.ToArray());$marker=if($Id-eq21005){$h.Contains('gk-direct-live-v1:dsl-kupfer')-and-not$h.Contains('glasfaser-spleissmuffe')}else{$h.Contains('data-gk-revision=')-and$h.Contains('pilot-v1')};[ordered]@{http=[int]$r.StatusCode;h1=([regex]::Matches($h,'<h1\b','IgnoreCase')).Count;marker=$marker;bad_encoding=([regex]::IsMatch($h,'[\u00C2\u00C3\u00E2]'))}}
function Find-Chrome(){$c=@("$env:ProgramFiles\Google\Chrome\Application\chrome.exe","$env:LOCALAPPDATA\Google\Chrome\Application\chrome.exe");foreach($x in $c){if($x-and(Test-Path $x)){return $x}};$null}
$workspace=$env:GITHUB_WORKSPACE;$pilot=Get-Content (Join-Path $workspace 'bridge/gk-offline-pilot.json') -Encoding UTF8 -Raw|ConvertFrom-Json
if($pilot.status-ne'OFFLINE_PILOT_FULL_SIMULATION_PASSED'-or[int]$pilot.target_count-ne3-or[int]$pilot.production_writes-ne0){throw 'Offline pilot gate failed'}
$routes=@{'21005'='/wp/v2/pages/21005';'298'='/wp/v2/posts/298';'163'='/wp/v2/posts/163'}
if($Simulation){foreach($t in $pilot.targets){if([int]$t.simulated_response.id-ne[int]$t.id){throw 'Simulation response mismatch'}};Write-Host 'LIVE WRAPPER SIMULATION PASSED';exit 0}
$secretDir=Join-Path $env:APPDATA 'GK-MCP-Tunnel';$user=(Get-Content(Join-Path $secretDir 'wp-user.txt')-Raw).Trim();$pass=Get-PlainSecret(Join-Path $secretDir 'wp-password.dat');try{$basic=[Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes($user+':'+$pass))}finally{Remove-Variable pass -ErrorAction SilentlyContinue};$headers=@{Authorization="Basic $basic";Accept='application/json'};Remove-Variable basic -ErrorAction SilentlyContinue
$backups=@();foreach($t in $pilot.targets){$route=$routes[[string]$t.id];if(-not$route){throw "Route missing $($t.id)"};$live=Invoke-Wp GET ($route+'?context=edit&_fields=id,modified,link,title,content,featured_media') $headers;if([string]$live.modified-ne[string]$t.source_modified){throw "SOURCE CHANGED $($t.id): expected=$($t.source_modified) actual=$($live.modified)"};$backups+=@([ordered]@{id=[int]$t.id;route=$route;link=[string]$live.link;modified=[string]$live.modified;content=[string]$live.content.raw;featured_media=[int]$live.featured_media})}
$backupPath=Join-Path $workspace 'bridge/gk-live-pilot-backup.json';[IO.File]::WriteAllText($backupPath,($backups|ConvertTo-Json -Depth 20),(New-Object Text.UTF8Encoding($false)));$safeDir='C:\GKBridge\backups';New-Item -ItemType Directory -Force -Path $safeDir|Out-Null;[IO.File]::WriteAllText((Join-Path $safeDir ('verified-live-pilot-'+(Get-Date -Format yyyyMMdd-HHmmss)+'.json')),($backups|ConvertTo-Json -Depth 20),(New-Object Text.UTF8Encoding($false)))
$written=@();$result=[ordered]@{started_utc=(Get-Date).ToUniversalTime().ToString('o');status='RUNNING';targets=@();screenshots=@();rollback=@();finished_utc=$null}
try{
 foreach($t in $pilot.targets){$route=$routes[[string]$t.id];$resp=Invoke-Wp POST $route $headers ([ordered]@{content=[string]$t.content;featured_media=[int]$t.featured_media});if([int]$resp.id-ne[int]$t.id){throw "Write response mismatch $($t.id)"};$written+=@([int]$t.id)}
 foreach($t in $pilot.targets){$route=$routes[[string]$t.id];$v=Invoke-Wp GET ($route+'?context=edit&_fields=id,link,content,featured_media') $headers;if([string]$v.content.raw-ne[string]$t.content-or[int]$v.featured_media-ne[int]$t.featured_media){throw "Edit verification failed $($t.id)"};try{Invoke-WebRequest -Uri ([string]$v.link) -Method PURGE -UseBasicParsing -TimeoutSec 60|Out-Null}catch{};$p=Public-Probe ([string]$v.link) ([int]$t.id);if($p.http-ne200-or$p.h1-ne1-or-not$p.marker-or$p.bad_encoding){throw "Public verification failed $($t.id)"};$result.targets+=@([ordered]@{id=[int]$t.id;url=[string]$v.link;action=[string]$t.action;public=$p;accepted=$true})}
 $chrome=Find-Chrome;if($null-eq$chrome){throw 'Chrome missing for mandatory screenshots'};foreach($x in $result.targets){foreach($view in @(@{n='desktop';s='1440,1200'},@{n='mobile';s='390,844'})){$path=Join-Path $workspace ("bridge/live-pilot-$($x.id)-$($view.n).png");&$chrome --headless=new --disable-gpu --hide-scrollbars --window-size=$view.s --screenshot=$path $x.url|Out-Null;if(-not(Test-Path $path)){throw "Screenshot missing $($x.id) $($view.n)"};$result.screenshots+=@([ordered]@{id=$x.id;viewport=$view.n;path=(Split-Path $path -Leaf)})}};$result.status='LIVE_PILOT_PUBLIC_AND_VISUAL_EVIDENCE_READY'
}catch{$failure=$_.Exception.Message;foreach($id in @($written|Select-Object -Unique)){$b=$backups|Where-Object{$_.id-eq$id};try{Invoke-Wp POST ([string]$b.route) $headers ([ordered]@{content=[string]$b.content;featured_media=[int]$b.featured_media})|Out-Null;$result.rollback+=@([ordered]@{id=$id;ok=$true})}catch{$result.rollback+=@([ordered]@{id=$id;ok=$false;error=$_.Exception.Message})}};$result.status='FAILED_AND_ROLLBACK_ATTEMPTED';$result.failure=$failure;$result.finished_utc=(Get-Date).ToUniversalTime().ToString('o');[IO.File]::WriteAllText((Join-Path $workspace 'bridge/gk-live-pilot-result.json'),($result|ConvertTo-Json -Depth 30),(New-Object Text.UTF8Encoding($false)));throw}
$result.finished_utc=(Get-Date).ToUniversalTime().ToString('o');[IO.File]::WriteAllText((Join-Path $workspace 'bridge/gk-live-pilot-result.json'),($result|ConvertTo-Json -Depth 30),(New-Object Text.UTF8Encoding($false)));Write-Host 'Verified live pilot completed: 3/3 public, 6 screenshots.'

