Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'

function Get-PlainSecret([string]$Path){$s=Get-Content $Path|ConvertTo-SecureString;$p=[Runtime.InteropServices.Marshal]::SecureStringToBSTR($s);try{[Runtime.InteropServices.Marshal]::PtrToStringBSTR($p)}finally{[Runtime.InteropServices.Marshal]::ZeroFreeBSTR($p)}}
function Invoke-WpJson([string]$Method,[string]$Path,[hashtable]$Headers,[object]$Body=$null){$url='https://glasfaser-kompass.de/wp-json'+$Path;$p=@{Uri=$url;Method=$Method;Headers=$Headers;UseBasicParsing=$true;TimeoutSec=180};if($null-ne$Body){$j=$Body|ConvertTo-Json -Depth 30 -Compress;$p.Body=[Text.Encoding]::UTF8.GetBytes($j);$p.ContentType='application/json; charset=utf-8'};$r=Invoke-WebRequest @p;if([string]::IsNullOrWhiteSpace([string]$r.Content)){return $null};return([string]$r.Content|ConvertFrom-Json)}
function Find-Media([string]$Title,[hashtable]$Headers){$q=[Uri]::EscapeDataString($Title);$arr=@(Invoke-WpJson 'GET' ("/wp/v2/media?context=edit&per_page=100&search=$q&_fields=id,title,source_url,alt_text,mime_type,caption") $Headers);return($arr|Where-Object{[string]$_.title.raw -eq $Title}|Select-Object -First 1)}
function Ensure-Media([hashtable]$Spec,[hashtable]$Headers){$hit=Find-Media $Spec.title $Headers;if($hit){return $hit};$tmp=Join-Path $env:TEMP $Spec.filename;Invoke-WebRequest -Uri $Spec.url -OutFile $tmp -UseBasicParsing -TimeoutSec 180;$bytes=[IO.File]::ReadAllBytes($tmp);$uh=@{};foreach($k in $Headers.Keys){$uh[$k]=$Headers[$k]};$uh['Content-Disposition']='attachment; filename="'+$Spec.filename+'"';$r=Invoke-WebRequest -Uri 'https://glasfaser-kompass.de/wp-json/wp/v2/media' -Method POST -Headers $uh -ContentType $Spec.mime -Body $bytes -UseBasicParsing -TimeoutSec 180;$m=[string]$r.Content|ConvertFrom-Json;Invoke-WpJson 'POST' ("/wp/v2/media/$($m.id)") $Headers ([ordered]@{title=$Spec.title;alt_text=$Spec.alt;caption=$Spec.caption;description=$Spec.description})|Out-Null;Remove-Item $tmp -Force -ErrorAction SilentlyContinue;return(Invoke-WpJson 'GET' ("/wp/v2/media/$($m.id)?context=edit&_fields=id,title,source_url,alt_text,mime_type,caption") $Headers)}
function Set-Featured([int]$PageId,[int]$MediaId,[string]$Label,[hashtable]$Headers,[ref]$Report){$before=Invoke-WpJson 'GET' ("/wp/v2/pages/$PageId?context=edit&_fields=id,modified,status,link,title,featured_media") $Headers;if(-not$before){return};if([int]$before.featured_media-eq$MediaId){$Report.Value+=@([ordered]@{page_id=$PageId;title=[string]$before.title.raw;url=[string]$before.link;old_featured_media=$MediaId;new_featured_media=$MediaId;media_label=$Label;verified=$true;unchanged=$true});return};$backupDir='C:\GKBridge\backups';New-Item -ItemType Directory -Force -Path $backupDir|Out-Null;$stamp=Get-Date -Format 'yyyyMMdd-HHmmss';$backup=Join-Path $backupDir("page-$PageId-$stamp-before-image.json");[IO.File]::WriteAllText($backup,($before|ConvertTo-Json -Depth 10),(New-Object Text.UTF8Encoding($false)));Invoke-WpJson 'POST' ("/wp/v2/pages/$PageId") $Headers ([ordered]@{featured_media=$MediaId})|Out-Null;$verify=Invoke-WpJson 'GET' ("/wp/v2/pages/$PageId?context=edit&_fields=id,modified,status,link,title,featured_media") $Headers;if([int]$verify.featured_media-ne$MediaId){throw"Featured-media verification failed on page $PageId"};$Report.Value+=@([ordered]@{page_id=$PageId;title=[string]$verify.title.raw;url=[string]$verify.link;old_featured_media=[int]$before.featured_media;new_featured_media=$MediaId;media_label=$Label;backup=$backup;verified=$true;unchanged=$false})}

$secretDir=Join-Path $env:APPDATA 'GK-MCP-Tunnel';$user=(Get-Content(Join-Path $secretDir 'wp-user.txt')-Raw).Trim();$pass=Get-PlainSecret(Join-Path $secretDir 'wp-password.dat');try{$basic=[Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes("$user`:$pass"))}finally{Remove-Variable pass -ErrorAction SilentlyContinue};$headers=@{Authorization="Basic $basic";Accept='application/json'};Remove-Variable basic -ErrorAction SilentlyContinue

$specs=@{
router=@{title='FRITZ!Box 7590 – reales Routerfoto';url='https://commons.wikimedia.org/wiki/Special:Redirect/file/FRITZ!Box_7590-Image29.jpg';filename='fritzbox-7590-reales-routerfoto.jpg';mime='image/jpeg';alt='Rückseite einer echten FRITZ!Box 7590 mit DSL-, WAN-, LAN- und USB-Anschlüssen';caption='Foto: Janus / Wikimedia Commons / CC BY-SA 3.0';description='Reales Produktfoto. Quelle: Wikimedia Commons, CC BY-SA 3.0.'}
ftth=@{title='FTTH-Abschluss – reales Foto';url='https://commons.wikimedia.org/wiki/Special:Redirect/file/Fiber_to_the_Home-aansluiting_van_E-fiber.jpg';filename='ftth-abschluss-reales-foto.jpg';mime='image/jpeg';alt='Realer FTTH-Glasfaserabschluss an einer Wand';caption='Foto: Maxmust / Wikimedia Commons / CC BY-SA 4.0';description='Reales FTTH-Foto. Quelle: Wikimedia Commons, CC BY-SA 4.0.'}
fiber=@{title='Glasfaser-Bündelrohre vor dem Einbau – reales Foto';url='https://commons.wikimedia.org/wiki/Special:Redirect/file/Fibre_To_The_Home_Sankt_Johann_in_Tirol.JPG';filename='glasfaser-buendelrohre-reales-foto.jpg';mime='image/jpeg';alt='Reale Glasfaser-Bündelrohre vor dem Einbau';caption='Foto: HellasX / Wikimedia Commons / Public Domain';description='Reales Ausbau-Foto. Quelle: Wikimedia Commons, Public Domain.'}
wifi=@{title='WLAN Access Point an der Wand – reales Foto';url='https://commons.wikimedia.org/wiki/Special:Redirect/file/Access-point-wireless.jpg';filename='wlan-access-point-reales-foto.jpg';mime='image/jpeg';alt='Realer WLAN Access Point an einer Wand';caption='Foto: Wikimedia Commons / Public Domain';description='Reales WLAN-Foto. Quelle: Wikimedia Commons, Public Domain.'}
}
$media=[ordered]@{};foreach($k in @('router','ftth','fiber','wifi')){$media[$k]=Ensure-Media $specs[$k] $headers}
$changes=@();
Set-Featured 21020 ([int]$media.router.id) 'real-router-photo' $headers ([ref]$changes);Set-Featured 21006 ([int]$media.router.id) 'real-router-photo' $headers ([ref]$changes);Set-Featured 21053 ([int]$media.router.id) 'real-router-photo' $headers ([ref]$changes);
Set-Featured 21003 ([int]$media.ftth.id) 'real-ftth-photo' $headers ([ref]$changes);Set-Featured 21004 ([int]$media.ftth.id) 'real-ftth-photo' $headers ([ref]$changes);Set-Featured 21022 ([int]$media.ftth.id) 'real-ftth-photo' $headers ([ref]$changes);Set-Featured 21967 ([int]$media.ftth.id) 'real-ftth-photo' $headers ([ref]$changes);
Set-Featured 21066 ([int]$media.fiber.id) 'real-fiber-installation-photo' $headers ([ref]$changes);
Set-Featured 21007 ([int]$media.wifi.id) 'real-wifi-photo' $headers ([ref]$changes);Set-Featured 21021 ([int]$media.wifi.id) 'real-wifi-photo' $headers ([ref]$changes);Set-Featured 21041 ([int]$media.wifi.id) 'real-wifi-photo' $headers ([ref]$changes);Set-Featured 21043 ([int]$media.wifi.id) 'real-wifi-photo' $headers ([ref]$changes);
$out=[ordered]@{generated_at_utc=(Get-Date).ToUniversalTime().ToString('o');success=$true;media=$media;changes=$changes};$path=Join-Path $env:GITHUB_WORKSPACE 'bridge/real-image-upgrade-result.json';[IO.File]::WriteAllText($path,($out|ConvertTo-Json -Depth 20),(New-Object Text.UTF8Encoding($false)));Write-Host"Real-image upgrade complete: $($changes.Count) verified page states"
