param([string]$EnvFile='.\.env')
$ErrorActionPreference='Stop';$v=@{};Get-Content $EnvFile|Where-Object{$_-match'^[^#].*='}|ForEach-Object{$p=$_-split'=',2;$v[$p[0].Trim()]=$p[1].Trim()};foreach($n in @('GK_SITE_URL','GK_CONTROL_TOKEN')){if([string]::IsNullOrWhiteSpace($v[$n])){throw "$n fehlt."}}
$site=$v.GK_SITE_URL.TrimEnd('/');$h=@{Authorization='Bearer '+$v.GK_CONTROL_TOKEN};$svg=@'
<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630" role="img" aria-labelledby="title desc">
<title id="title">PON-Netzstruktur vom OLT über den Splitter zu mehreren ONTs</title><desc id="desc">Technische Netzskizze eines passiven optischen Netzes.</desc>
<rect width="1200" height="630" fill="#f4f8fb"/><rect x="55" y="55" width="1090" height="520" rx="28" fill="#ffffff" stroke="#0b3558" stroke-width="4"/>
<text x="90" y="120" font-family="Arial,sans-serif" font-size="42" font-weight="700" fill="#0b3558">PON: ein Glasfaseranschluss, passiv verteilt</text>
<rect x="105" y="245" width="210" height="125" rx="18" fill="#0b3558"/><text x="210" y="300" text-anchor="middle" font-family="Arial,sans-serif" font-size="32" font-weight="700" fill="#ffffff">OLT</text><text x="210" y="340" text-anchor="middle" font-family="Arial,sans-serif" font-size="20" fill="#d9efff">Netzbetreiber</text>
<line x1="315" y1="307" x2="500" y2="307" stroke="#00a6c8" stroke-width="14"/><circle cx="520" cy="307" r="62" fill="#e8f7fb" stroke="#00a6c8" stroke-width="8"/><path d="M490 307h60M520 277v60" stroke="#0b3558" stroke-width="8"/><text x="520" y="405" text-anchor="middle" font-family="Arial,sans-serif" font-size="24" font-weight="700" fill="#0b3558">passiver Splitter</text>
<path d="M582 307H700V205H790M700 307H790M700 307V409H790" fill="none" stroke="#00a6c8" stroke-width="12"/>
<g fill="#ffffff" stroke="#0b3558" stroke-width="5"><rect x="790" y="150" width="245" height="110" rx="16"/><rect x="790" y="260" width="245" height="110" rx="16"/><rect x="790" y="370" width="245" height="110" rx="16"/></g>
<g font-family="Arial,sans-serif" fill="#0b3558" text-anchor="middle"><text x="912" y="198" font-size="28" font-weight="700">ONT 1</text><text x="912" y="230" font-size="19">Kundenanschluss</text><text x="912" y="308" font-size="28" font-weight="700">ONT 2</text><text x="912" y="340" font-size="19">Kundenanschluss</text><text x="912" y="418" font-size="28" font-weight="700">ONT 3</text><text x="912" y="450" font-size="19">Kundenanschluss</text></g>
<text x="90" y="535" font-family="Arial,sans-serif" font-size="24" fill="#34556f">Zwischen OLT und ONT verteilt der Splitter das optische Signal ohne aktive Stromversorgung.</text>
</svg>
'@;$existing=@(Invoke-RestMethod ($site+'/wp-json/wp/v2/media?search=PON-Netzstruktur&per_page=20&_fields=id,source_url,date') -TimeoutSec 30|Where-Object{$_.source_url-match'gk-pon-netzstruktur'}|Sort-Object date -Descending);if($existing.Count){$attachmentId=[long]$existing[0].id;Write-Host("WIEDERVERWENDET: Attachment=$attachmentId")}else{$payload=@{filename='gk-pon-netzstruktur.svg';title='PON-Netzstruktur';alt='Schematische PON-Netzstruktur: OLT, passiver Splitter und mehrere ONTs.';svg=$svg}|ConvertTo-Json -Compress;$upload=Invoke-RestMethod ($site+'/wp-json/gk-control/v1/media/upload-svg') -Method Post -Headers $h -ContentType 'application/json; charset=utf-8' -Body ([Text.Encoding]::UTF8.GetBytes($payload));Write-Host('UPLOAD: '+($upload|ConvertTo-Json -Compress));$attachmentId=[long]$(if($upload.attachment_id){$upload.attachment_id}elseif($upload.media_id){$upload.media_id}else{$upload.id})};if($attachmentId-le 0){throw 'Keine Attachment-ID verfügbar'};$setPayload=@{post_id=19003;attachment_id=$attachmentId}|ConvertTo-Json -Compress;$set=Invoke-RestMethod ($site+'/wp-json/gk-control/v1/media/set-featured') -Method Post -Headers $h -ContentType 'application/json; charset=utf-8' -Body ([Text.Encoding]::UTF8.GetBytes($setPayload));Write-Host('SET: '+($set|ConvertTo-Json -Compress));Start-Sleep -Seconds 2;$check=Invoke-RestMethod ($site+'/wp-json/wp/v2/posts/19003?_fields=id,featured_media') -TimeoutSec 30;if([long]$check.featured_media-ne$attachmentId){throw 'Beitragsbild-Zuweisung nicht verifiziert'};$media=Invoke-RestMethod ($site+"/wp-json/wp/v2/media/$attachmentId`?_fields=id,source_url,alt_text") -TimeoutSec 30;if([string]$media.alt_text-ne'Schematische PON-Netzstruktur: OLT, passiver Splitter und mehrere ONTs.'){throw 'Alt-Text nicht verifiziert'};Write-Host("FERTIG: Seite=19003 | Attachment=$attachmentId | Status=UPLOADED_ASSIGNED_VERIFIED | URL=$($media.source_url)")
