param([string]$EnvFile='.\.env')
$ErrorActionPreference='Stop'
$v=@{};Get-Content $EnvFile|Where-Object{$_-match'^[^#].*='}|ForEach-Object{$p=$_-split'=',2;$v[$p[0].Trim()]=$p[1].Trim()}
foreach($n in @('GK_SITE_URL','GK_SITE_AUDIT_TOKEN')){if([string]::IsNullOrWhiteSpace($v[$n])){throw "$n fehlt."}}
$site=$v.GK_SITE_URL.TrimEnd('/');$headers=@{Authorization='Bearer '+$v.GK_SITE_AUDIT_TOKEN};$mobile=@{'User-Agent'='Mozilla/5.0 (Linux; Android 14; Pixel 8) AppleWebKit/537.36 Chrome/126.0 Mobile Safari/537.36'}
$queue=@();$page=1;do{$batch=@(Invoke-RestMethod ($site+'/wp-json/gk-site-audit/v1/items?page='+$page+'&per_page=100') -Headers $headers -TimeoutSec 45);if($batch.Count-eq1-and$null-ne$batch[0].items){$batch=@($batch[0].items)};$queue+=$batch;$page++}while($batch.Count-eq100)
$ids=@($queue|Where-Object{$null-ne$_.id}|ForEach-Object{[long]$_.id}|Sort-Object -Unique);$rows=@();$cache=@{}
function Test-Asset([string]$url){if($cache.ContainsKey($url)){return $cache[$url]};try{$r=Invoke-WebRequest $url -UseBasicParsing -Headers $mobile -TimeoutSec 35;$x=@{http=[int]$r.StatusCode;type=[string]$r.Headers['Content-Type'];bytes=[long]$r.RawContentLength}}catch{$code=0;if($_.Exception.Response){$code=[int]$_.Exception.Response.StatusCode};$x=@{http=$code;type='';bytes=0}};$cache[$url]=$x;return $x}
foreach($id in $ids){$kind='posts';try{$meta=Invoke-RestMethod ($site+"/wp-json/wp/v2/posts/$id`?_fields=id,link,title") -TimeoutSec 30}catch{$kind='pages';$meta=Invoke-RestMethod ($site+"/wp-json/wp/v2/pages/$id`?_fields=id,link,title") -TimeoutSec 30};$title=[Net.WebUtility]::HtmlDecode([string]$meta.title.rendered);$pageResponse=Invoke-WebRequest ([string]$meta.link+'?_gkmobile=1') -UseBasicParsing -Headers $mobile -TimeoutSec 45;$html=[string]$pageResponse.Content;$scope=[regex]::Match($html,'(?is)<main\b.*?</main>');if(-not$scope.Success){$scope=[regex]::Match($html,'(?is)<article\b.*?</article>')};$body=if($scope.Success){$scope.Value}else{$html};$assets=@()
 foreach($m in [regex]::Matches($body,'(?is)<(?:img|source)\b(?<a>[^>]*)>')){$a=$m.Groups['a'].Value;$alt=[Net.WebUtility]::HtmlDecode([regex]::Match($a,'(?is)\balt=["''](?<v>[^"'']*)').Groups['v'].Value);$urls=@();foreach($attr in @('src','data-src','data-lazy-src','srcset','data-srcset')){$am=[regex]::Match($a,'(?is)\b'+[regex]::Escape($attr)+'=["''](?<v>[^"'']*)');if(-not$am.Success){continue};foreach($part in ($am.Groups['v'].Value-split',')){$u=($part.Trim()-split'\s+')[0];if($u){$urls+=$u}}};foreach($raw in ($urls|Select-Object -Unique)){$u=$raw;if($u.StartsWith('//')){$u='https:'+$u}elseif($u.StartsWith('/')){$u=$site+$u};$problem='OK';$check=@{http=0;type='';bytes=0};if($u-match'^data:image/(svg\+xml|gif);base64,'){$problem='INLINE_PLACEHOLDER'}elseif($u-match'(?i)(placeholder|dummy|fallback|default-image|no-image|spacer|blank)'){$problem='PLACEHOLDER_NAME'}elseif($u-match'^https?://'){$check=Test-Asset $u;if($check.http-ne200){$problem='BROKEN'}elseif($check.type-notmatch'^image/'){$problem='NOT_IMAGE'}elseif($check.bytes-lt300){$problem='EMPTY_IMAGE'};if($problem-eq'OK'){$path=try{([Uri]$u).AbsolutePath}catch{$u};if($title-match'(?i)\b(DSL|APL|TAE|TAL|KVz|HVt|Vectoring)\b'-and$path-match'(?i)(glasfaser|gf-ap|gf-ta|ont|wlan)'){$problem='TOPIC_MISMATCH_DSL'}elseif($title-match'(?i)\b(Glasfaser|FTTH|GPON|XGS.PON|Gf-AP|Gf-TA|ONT)\b'-and$path-match'(?i)(dsl|apl|tae|wlan)'){$problem='TOPIC_MISMATCH_FIBER'}elseif($title-match'(?i)\b(WLAN|Wi.Fi|Mesh|Repeater|Access Point)\b'-and$path-match'(?i)(dsl|apl|tae|glasfaser|gf-ap|gf-ta|ont)'){$problem='TOPIC_MISMATCH_WLAN'}}};$assets+=@{url=$u;alt=$alt;http=$check.http;type=$check.type;bytes=$check.bytes;problem=$problem}}
 }
 $bad=@($assets|Where-Object{$_.problem-ne'OK'});if($bad.Count){$row=[pscustomobject]@{id=$id;type=$kind;title=$title;url=[string]$meta.link;problems=$bad};$rows+=$row;Write-Host('MOBILE_VISUAL_PROBLEM '+($row|ConvertTo-Json -Compress -Depth 8))}
}
$root=Split-Path -Parent $PSScriptRoot;$out=Join-Path $root 'reports';New-Item $out -ItemType Directory -Force|Out-Null;$rows|ConvertTo-Json -Depth 8|Set-Content (Join-Path $out('mobile-image-audit-'+(Get-Date -Format yyyyMMdd-HHmmss)+'.json')) -Encoding UTF8;Write-Host("FERTIG: Mobile-Seiten=$($ids.Count) | Problemseiten=$($rows.Count)")
