param([string]$EnvFile='.\.env',[long[]]$Ids=@())
$ErrorActionPreference='Stop'
$v=@{};Get-Content $EnvFile|Where-Object{$_ -match '^[^#].*='}|ForEach-Object{$p=$_ -split '=',2;$v[$p[0].Trim()]=$p[1].Trim()}
if([string]::IsNullOrWhiteSpace($v['GK_SITE_URL'])){throw 'GK_SITE_URL fehlt.'}
$site=$v['GK_SITE_URL'].TrimEnd('/');$index=Invoke-RestMethod($site+'/wp-json/')-TimeoutSec 30;$routes=@($index.routes.PSObject.Properties.Name|Where-Object{$_-match'gk-unified-api|media|attachment|upload'}|Sort-Object);Write-Host('ROUTEN: '+($routes-join','));foreach($routeName in @('/gk-control/v1/media/set-featured','/gk-control/v1/media/upload-svg','/gk-unified-api/v1/apply-media-images','/gk-unified-api/v1/image-audit','/gk-unified-api/v1/image-summary','/gk-unified-api/v1/media-map-audit')){$route=$index.routes.PSObject.Properties[$routeName].Value;if($null-ne$route){Write-Host('ROUTE_SCHEMA '+$routeName+': '+($route|ConvertTo-Json -Depth 20 -Compress))}};if(-not[string]::IsNullOrWhiteSpace($v['GK_UNIFIED_API_TOKEN'])){$auditHeaders=@{Authorization='Bearer '+$v['GK_UNIFIED_API_TOKEN']};foreach($probe in @(@{path='image-summary';body=@{}},@{path='image-audit';body=@{id=19003;limit=5}},@{path='media-map-audit';body=@{id=19003;limit=5}})){try{$probeBytes=[Text.Encoding]::UTF8.GetBytes(($probe.body|ConvertTo-Json -Compress));$probeResult=Invoke-RestMethod($site+'/wp-json/gk-unified-api/v1/'+$probe.path) -Method Post -Headers $auditHeaders -ContentType 'application/json; charset=utf-8' -Body $probeBytes;$probeJson=$probeResult|ConvertTo-Json -Depth 20 -Compress;if($probeJson.Length-gt 12000){$probeJson=$probeJson.Substring(0,12000)};Write-Host('PROBE '+$probe.path+': '+$probeJson)}catch{Write-Host('PROBE_ERROR '+$probe.path+': '+$_.Exception.Message)}}};foreach($contractProbe in @(@{path='/wp-json/gk-control/v1/media/set-featured';body=@{}},@{path='/wp-json/gk-control/v1/media/upload-svg';body=@{}},@{path='/wp-json/gk-unified-api/v1/apply-media-images';body=@{dry_run=$true;ids=@(19003)}})){try{$contractBytes=[Text.Encoding]::UTF8.GetBytes(($contractProbe.body|ConvertTo-Json -Depth 10 -Compress));$contractResult=Invoke-WebRequest($site+$contractProbe.path) -Method Post -Headers $auditHeaders -ContentType 'application/json; charset=utf-8' -Body $contractBytes -UseBasicParsing;Write-Host('CONTRACT '+$contractProbe.path+': HTTP '+$contractResult.StatusCode+' '+$contractResult.Content)}catch{$response=$_.Exception.Response;if($null-ne$response){$reader=New-Object IO.StreamReader($response.GetResponseStream());try{$errorBody=$reader.ReadToEnd()}finally{$reader.Dispose()};Write-Host('CONTRACT '+$contractProbe.path+': HTTP '+[int]$response.StatusCode+' '+$errorBody)}else{Write-Host('CONTRACT_ERROR '+$contractProbe.path+': '+$_.Exception.Message)}}}};$root=if(Test-Path(Join-Path $PSScriptRoot '..\GkProductionWorker.sln')){Split-Path -Parent $PSScriptRoot}else{$PSScriptRoot};$out=Join-Path $root 'reports';New-Item $out -ItemType Directory -Force|Out-Null;$rows=@()
foreach($id in $Ids){$post=$null;$kind='post';try{$post=Invoke-RestMethod($site+"/wp-json/wp/v2/posts/$id`?_fields=id,link,title,featured_media")-TimeoutSec 30}catch{$kind='page';try{$post=Invoke-RestMethod($site+"/wp-json/wp/v2/pages/$id`?_fields=id,link,title,featured_media")-TimeoutSec 30}catch{$rows+=[pscustomobject]@{id=$id;type='unknown';title='';url='';media_id=0;media_url='';alt='';caption='';status='POST_NOT_PUBLIC'};Write-Host("MEDIUM: $id | POST_NOT_PUBLIC");continue}}
 $mediaId=[long]$post.featured_media;$mediaUrl='';$alt='';$caption='';$status=if($mediaId-gt 0){'ASSIGNED'}else{'MISSING'}
 if($mediaId-gt 0){try{$media=Invoke-RestMethod($site+"/wp-json/wp/v2/media/$mediaId`?_fields=id,source_url,alt_text,caption,media_details")-TimeoutSec 30;$mediaUrl=[string]$media.source_url;$alt=[string]$media.alt_text;$caption=[string]$media.caption.rendered}catch{$status='MEDIA_NOT_PUBLIC'}}
 $title=[Net.WebUtility]::HtmlDecode([string]$post.title.rendered);$rows+=[pscustomobject]@{id=$id;type=$kind;title=$title;url=[string]$post.link;media_id=$mediaId;media_url=$mediaUrl;alt=$alt;caption=([regex]::Replace($caption,'<[^>]+>',' ')).Trim();status=$status};Write-Host("MEDIUM: $id | $status | ID=$mediaId | $mediaUrl")
}
$path=Join-Path $out('featured-media-audit-'+(Get-Date -Format 'yyyyMMdd-HHmmss')+'.csv');$rows|Export-Csv $path -NoTypeInformation -Encoding UTF8;Write-Host('FERTIG: Geprüft='+$rows.Count+' | Zugeordnet='+@($rows|Where-Object{$_.status-eq'ASSIGNED'}).Count+' | Fehlend='+@($rows|Where-Object{$_.status-eq'MISSING'}).Count+' | Bericht='+$path)
