param([string]$EnvFile='.\.env')
$ErrorActionPreference='Stop'
$v=@{}; Get-Content $EnvFile | Where-Object {$_ -match '^[^#].*='} | ForEach-Object {$p=$_ -split '=',2;$v[$p[0].Trim()]=$p[1].Trim()}
foreach($n in @('GK_SITE_URL','GK_SITE_AUDIT_TOKEN','GK_UNIFIED_API_TOKEN')){if([string]::IsNullOrWhiteSpace($v[$n])){throw "$n fehlt."}}
$site=$v.GK_SITE_URL.TrimEnd('/'); $root=Split-Path -Parent $PSScriptRoot; $out=Join-Path $root 'reports'; New-Item $out -ItemType Directory -Force|Out-Null; $stamp=Get-Date -Format 'yyyyMMdd-HHmmss'
$auditHeaders=@{Authorization='Bearer '+$v.GK_SITE_AUDIT_TOKEN};$unifiedHeaders=@{Authorization='Bearer '+$v.GK_UNIFIED_API_TOKEN}
function Get-AllPages{$all=@();$page=1;do{$uri=$site+"/wp-json/wp/v2/pages?status=publish&per_page=100&page=$page&_fields=id,link,slug,title,featured_media,content";try{$batch=@(Invoke-RestMethod $uri -TimeoutSec 45)}catch{if($_.Exception.Response -and [int]$_.Exception.Response.StatusCode-eq400){$batch=@()}else{throw}};$all+=$batch;$page++}while($batch.Count-eq100);return $all}
$queue=@();$page=1;do{$batch=@(Invoke-RestMethod ($site+'/wp-json/gk-site-audit/v1/items?page='+$page+'&per_page=100') -Headers $auditHeaders -TimeoutSec 45);if($batch.Count-eq1-and$null-ne$batch[0].items){$batch=@($batch[0].items)};$queue+=$batch;$page++}while($batch.Count-eq100)
+$items=@();foreach($q in ($queue|ForEach-Object{$_}|Where-Object{$null-ne$_.id}|Sort-Object{[long]$_.id}-Unique)){$qid=[long]$q.id;$readBody=[Text.Encoding]::UTF8.GetBytes((@{id=$qid}|ConvertTo-Json -Compress));$full=Invoke-RestMethod ($site+'/wp-json/gk-unified-api/v1/read-post') -Method Post -Headers $unifiedHeaders -ContentType 'application/json; charset=utf-8' -Body $readBody;try{$meta=Invoke-RestMethod ($site+"/wp-json/wp/v2/posts/$qid"+'?_fields=id,link,slug,title,featured_media') -TimeoutSec 30}catch{$meta=Invoke-RestMethod ($site+"/wp-json/wp/v2/pages/$qid"+'?_fields=id,link,slug,title,featured_media') -TimeoutSec 30};$items+=[pscustomobject]@{id=$qid;link=[string]$meta.link;slug=[string]$meta.slug;title=[pscustomobject]@{rendered=[string]$full.title};featured_media=[long]$meta.featured_media;content=[pscustomobject]@{rendered=[string]$full.content}}}
+$items+=@(Get-AllPages);$items=@($items|ForEach-Object{$_}|Where-Object{$null-ne$_.id}|Sort-Object{[long]$_.id}-Unique);$idMap=@{};foreach($i in $items){$id=[long]$i.id;$idMap[$id]=[string]$i.link}
$urlCache=@{};function Test-Url([string]$url){if($urlCache.ContainsKey($url)){return $urlCache[$url]};try{$r=Invoke-WebRequest $url -UseBasicParsing -MaximumRedirection 8 -TimeoutSec 35;$x=[pscustomobject]@{http=[int]$r.StatusCode;final=[string]$r.BaseResponse.ResponseUri.AbsoluteUri;content_type=[string]$r.Headers['Content-Type'];bytes=[long]$r.RawContentLength}}catch{$code=0;if($_.Exception.Response){$code=[int]$_.Exception.Response.StatusCode};$x=[pscustomobject]@{http=$code;final='';content_type='';bytes=0}};$urlCache[$url]=$x;return $x}
$linkRows=@();$imageRows=@();$mediaRows=@()
foreach($i in $items){$id=[long]$i.id;$title=[Net.WebUtility]::HtmlDecode([string]$i.title.rendered);$html=[string]$i.content.rendered
 foreach($m in [regex]::Matches($html,'(?is)<a\b[^>]*href\s*=\s*["''](?<url>[^"'']+)["''][^>]*>(?<text>.*?)</a>')){$raw=[Net.WebUtility]::HtmlDecode($m.Groups['url'].Value);if($raw-match'^(mailto:|tel:|#|javascript:)'){continue};$u=$null;if([Uri]::TryCreate($raw,[UriKind]::Absolute,[ref]$u)){}elseif($raw.StartsWith('/')){$u=[Uri]($site+$raw)}else{continue};if($u.Host-ne([Uri]$site).Host){continue};$check=Test-Url $u.AbsoluteUri;$text=(([Net.WebUtility]::HtmlDecode([regex]::Replace($m.Groups['text'].Value,'<[^>]+>',' ')))-replace'\s+',' ').Trim();$targetId=0;if($u.Query-match'(?:^|[?&])p=(\d+)'){$targetId=[long]$Matches[1]};$canonical=if($targetId-and$idMap.ContainsKey($targetId)){$idMap[$targetId]}else{''};$problem=if($check.http-ne200){'BROKEN'}elseif($canonical-and$check.final-ne$canonical){'OBJECT_PATH'}elseif($check.final-and([Uri]$check.final).AbsolutePath-ne$u.AbsolutePath){'REDIRECT_PATH'}elseif([string]::IsNullOrWhiteSpace($text)){'EMPTY_LABEL'}else{'OK'};$linkRows+=[pscustomobject]@{source_id=$id;source_title=$title;anchor=$text;url=$u.AbsoluteUri;http=$check.http;final_url=$check.final;canonical_url=$canonical;problem=$problem}}
 foreach($m in [regex]::Matches($html,'(?is)<img\b(?<attrs>[^>]*)>')){$attrs=$m.Groups['attrs'].Value;$sm=[regex]::Match($attrs,'(?is)\bsrc\s*=\s*["''](?<url>[^"'']+)["'']');if(-not$sm.Success){continue};$raw=[Net.WebUtility]::HtmlDecode($sm.Groups['url'].Value);$u=$null;if([Uri]::TryCreate($raw,[UriKind]::Absolute,[ref]$u)){}elseif($raw.StartsWith('/')){$u=[Uri]($site+$raw)}else{continue};$check=Test-Url $u.AbsoluteUri;$alt=[regex]::Match($attrs,'(?is)\balt\s*=\s*["''](?<v>[^"'']*)["'']').Groups['v'].Value;$imageRows+=[pscustomobject]@{source_id=$id;source_title=$title;url=$u.AbsoluteUri;http=$check.http;content_type=$check.content_type;bytes=$check.bytes;alt=$alt;problem=if($check.http-ne200){'BROKEN'}elseif($check.content_type-notmatch'^image/'){'NOT_IMAGE'}elseif([string]::IsNullOrWhiteSpace($alt)){'MISSING_ALT'}else{'OK'}}}
 $mid=[long]$i.featured_media;if($mid-le0){$mediaRows+=[pscustomobject]@{source_id=$id;source_title=$title;media_id=0;url='';width=0;height=0;ratio=0;orientation='missing';alt='';problem='MISSING';intentional=($id-in@(1011,1012,21003,21004,21005,21006,21007,21008,21009,20824,21966,21967,21968))};continue};try{$media=Invoke-RestMethod($site+"/wp-json/wp/v2/media/$mid`?_fields=id,source_url,alt_text,media_details")-TimeoutSec 35;$w=[int]$media.media_details.width;$h=[int]$media.media_details.height;$ratio=if($h){[math]::Round($w/$h,2)}else{0};$orientation=if($ratio-ge1.35){'landscape'}elseif($ratio-le0.8){'portrait'}else{'square'};$mediaRows+=[pscustomobject]@{source_id=$id;source_title=$title;media_id=$mid;url=[string]$media.source_url;width=$w;height=$h;ratio=$ratio;orientation=$orientation;alt=[string]$media.alt_text;problem=if($w-lt600-or$h-lt315){'TOO_SMALL'}elseif($orientation-ne'landscape'){'WRONG_ORIENTATION'}elseif([string]::IsNullOrWhiteSpace([string]$media.alt_text)){'MISSING_ALT'}else{'OK'};intentional=$false}}catch{$mediaRows+=[pscustomobject]@{source_id=$id;source_title=$title;media_id=$mid;url='';width=0;height=0;ratio=0;orientation='unknown';alt='';problem='MEDIA_UNAVAILABLE';intentional=$false}}
}
$linkRows|Export-Csv(Join-Path $out("object-paths-$stamp.csv")) -NoTypeInformation -Encoding UTF8;$imageRows|Export-Csv(Join-Path $out("content-images-$stamp.csv")) -NoTypeInformation -Encoding UTF8;$mediaRows|Export-Csv(Join-Path $out("featured-visuals-$stamp.csv")) -NoTypeInformation -Encoding UTF8
$summary=[ordered]@{pages=$items.Count;internal_links=$linkRows.Count;link_problems=@($linkRows|Where-Object problem-ne'OK').Count;content_images=$imageRows.Count;content_image_problems=@($imageRows|Where-Object problem-ne'OK').Count;featured_missing=@($mediaRows|Where-Object{$_.problem-eq'MISSING'-and-not$_.intentional}).Count;featured_orientation=@($mediaRows|Where-Object problem-eq'WRONG_ORIENTATION').Count;featured_small=@($mediaRows|Where-Object problem-eq'TOO_SMALL').Count;featured_missing_alt=@($mediaRows|Where-Object problem-eq'MISSING_ALT').Count};$summary|ConvertTo-Json|Set-Content(Join-Path $out("object-visual-summary-$stamp.json")) -Encoding UTF8;Write-Host($summary|ConvertTo-Json -Compress)
