param([string]$EnvFile='.\.env')
$ErrorActionPreference='Stop'
$v=@{};Get-Content $EnvFile|Where-Object{$_-match'^[^#].*='}|ForEach-Object{$p=$_-split'=',2;$v[$p[0].Trim()]=$p[1].Trim()}
foreach($n in @('GK_SITE_URL','GK_SITE_AUDIT_TOKEN','GK_UNIFIED_API_TOKEN','GK_CONTROL_TOKEN')){if([string]::IsNullOrWhiteSpace($v[$n])){throw "$n fehlt."}}
$site=$v.GK_SITE_URL.TrimEnd('/');$ah=@{Authorization='Bearer '+$v.GK_SITE_AUDIT_TOKEN};$uh=@{Authorization='Bearer '+$v.GK_UNIFIED_API_TOKEN};$ch=@{Authorization='Bearer '+$v.GK_CONTROL_TOKEN}
function Upload-Svg([string]$filename,[string]$title,[string]$alt,[string]$svg){$found=@(Invoke-RestMethod ($site+'/wp-json/wp/v2/media?search='+[uri]::EscapeDataString(($filename-replace'\.svg$',''))+'&per_page=20&_fields=id,source_url,date') -TimeoutSec 30|Where-Object{$_.source_url-match[regex]::Escape($filename)}|Sort-Object date -Descending);if($found.Count){return [long]$found[0].id};$payload=@{filename=$filename;title=$title;alt=$alt;svg=$svg}|ConvertTo-Json -Compress;$u=Invoke-RestMethod ($site+'/wp-json/gk-control/v1/media/upload-svg') -Method Post -Headers $ch -ContentType 'application/json; charset=utf-8' -Body ([Text.Encoding]::UTF8.GetBytes($payload));return [long]$(if($u.attachment_id){$u.attachment_id}elseif($u.media_id){$u.media_id}else{$u.id})}
$signalAlt='Korrekter DSL-Signalweg: DSLAM oder MSAN, Kupfer-Zugangsnetz, APL, Endleitung, erste TAE-Dose, DSL-Kabel und Router.'
$signalSvg=@'
<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630" role="img" aria-labelledby="t d"><title id="t">DSL-Signalweg vom Netz bis zum Router</title><desc id="d">DSLAM oder MSAN, Kupfer-Zugangsnetz, APL, Endleitung, erste TAE, DSL-Kabel und Router in fachlich korrekter Reihenfolge.</desc><rect width="1200" height="630" fill="#f4f8fb"/><text x="60" y="70" font-family="Arial" font-size="38" font-weight="700" fill="#0b3558">DSL-Signalweg: Netz bis Router</text><text x="60" y="108" font-family="Arial" font-size="21" fill="#34556f">VDSL: DSLAM/MSAN meist im MFG; ADSL kann aus der Vermittlungsstelle kommen.</text><g font-family="Arial" text-anchor="middle"><g fill="#e8f7fb" stroke="#0b3558" stroke-width="5"><rect x="35" y="190" width="145" height="150" rx="16"/><rect x="205" y="190" width="180" height="150" rx="16"/><rect x="410" y="190" width="130" height="150" rx="16"/><rect x="565" y="190" width="145" height="150" rx="16"/><rect x="735" y="190" width="135" height="150" rx="16"/><rect x="895" y="190" width="120" height="150" rx="16"/><rect x="1040" y="190" width="125" height="150" rx="16"/></g><g fill="#0b3558" font-size="21" font-weight="700"><text x="108" y="245">DSLAM/</text><text x="108" y="273">MSAN</text><text x="295" y="235">Kupfer-</text><text x="295" y="263">Zugangsnetz</text><text x="295" y="291" font-size="16">KVz, Kabel,</text><text x="295" y="314" font-size="16">Muffen</text><text x="475" y="265">APL</text><text x="637" y="247">Endleitung</text><text x="637" y="280" font-size="16">im Geb&#228;ude</text><text x="802" y="247">erste</text><text x="802" y="278">TAE</text><text x="955" y="247">DSL-</text><text x="955" y="278">Kabel</text><text x="1102" y="265">Router</text></g><g stroke="#c87818" stroke-width="8" fill="none"><path d="M180 265h25"/><path d="M385 265h25"/><path d="M540 265h25"/><path d="M710 265h25"/><path d="M870 265h25"/><path d="M1015 265h25"/></g><g fill="#c87818"><path d="M205 265l-16-11v22z"/><path d="M410 265l-16-11v22z"/><path d="M565 265l-16-11v22z"/><path d="M735 265l-16-11v22z"/><path d="M895 265l-16-11v22z"/><path d="M1040 265l-16-11v22z"/></g></g><g font-family="Arial" fill="#0b3558"><text x="60" y="410" font-size="24" font-weight="700">Wichtige Trennstelle</text><text x="60" y="448" font-size="21">Am APL endet das Betreiber-Zugangsnetz. Dahinter folgen Endleitung und erste TAE.</text><text x="60" y="486" font-size="21">Muffen und Stra&#223;enkabel liegen netzseitig vor dem APL, nicht zwischen APL und TAE.</text><text x="60" y="540" font-size="18" fill="#34556f">Keine Glasfaserbauteile: Gf-AP, Gf-TA und ONT geh&#246;ren nicht in diesen DSL-Kupfer-Signalweg.</text></g></svg>
'@
$aplAlt='Schematischer DSL-APL mit ankommendem Betreiberkabel, Anschlussklemmen und abgehender Endleitung zur ersten TAE.'
$aplSvg=@'
<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630" role="img" aria-labelledby="t d"><title id="t">APL fachlich korrekt dargestellt</title><desc id="d">Ankommendes Kupferkabel des Netzbetreibers, passive Anschlussklemmen im APL und abgehende Endleitung zur ersten TAE.</desc><rect width="1200" height="630" fill="#f4f8fb"/><text x="60" y="72" font-family="Arial" font-size="38" font-weight="700" fill="#0b3558">APL: &#220;bergang zur Hausverkabelung</text><path d="M60 315H360" stroke="#0b3558" stroke-width="26"/><text x="70" y="270" font-family="Arial" font-size="22" fill="#0b3558">Betreiberkabel (Kupfer)</text><rect x="360" y="150" width="430" height="330" rx="25" fill="#fff" stroke="#0b3558" stroke-width="9"/><text x="575" y="205" text-anchor="middle" font-family="Arial" font-size="29" font-weight="700" fill="#0b3558">APL</text><g fill="#e8f7fb" stroke="#0b3558" stroke-width="4"><rect x="430" y="245" width="110" height="80" rx="10"/><rect x="610" y="245" width="110" height="80" rx="10"/><rect x="430" y="355" width="110" height="80" rx="10"/><rect x="610" y="355" width="110" height="80" rx="10"/></g><g stroke="#c87818" stroke-width="7"><path d="M360 315H430"/><path d="M540 285H610"/><path d="M720 285H790"/></g><path d="M790 285H1130" stroke="#c87818" stroke-width="16"/><text x="850" y="245" font-family="Arial" font-size="22" fill="#0b3558">Endleitung zur ersten TAE</text><text x="575" y="525" text-anchor="middle" font-family="Arial" font-size="21" fill="#34556f">Passiver Abschlusspunkt: kein Router, kein ONT, keine Stromversorgung</text></svg>
'@
$signalId=0;$aplId=0
try{$known=Invoke-RestMethod ($site+'/wp-json/wp/v2/media/28085?_fields=id,source_url') -TimeoutSec 30;if([string]$known.source_url-match'gk-dsl-signalweg-korrekt\.svg'){$signalId=28085}}catch{}
try{$known=Invoke-RestMethod ($site+'/wp-json/wp/v2/media/28086?_fields=id,source_url') -TimeoutSec 30;if([string]$known.source_url-match'gk-apl-korrekt\.svg'){$aplId=28086}}catch{}
if($signalId-le0){$signalId=Upload-Svg 'gk-dsl-signalweg-korrekt.svg' 'DSL-Signalweg korrekt' $signalAlt $signalSvg};if($aplId-le0){$aplId=Upload-Svg 'gk-apl-korrekt.svg' 'APL korrekt' $aplAlt $aplSvg}
if($signalId-le0-or$aplId-le0){throw 'SVG-Upload ohne Medien-ID.'};$signalMedia=Invoke-RestMethod ($site+"/wp-json/wp/v2/media/$signalId`?_fields=id,source_url") -TimeoutSec 30;$aplMedia=Invoke-RestMethod ($site+"/wp-json/wp/v2/media/$aplId`?_fields=id,source_url") -TimeoutSec 30;$signalUrl=[string]$signalMedia.source_url;$aplUrl=[string]$aplMedia.source_url
$queue=@();$page=1;do{$b=@(Invoke-RestMethod ($site+'/wp-json/gk-site-audit/v1/items?page='+$page+'&per_page=100') -Headers $ah -TimeoutSec 45);if($b.Count-eq1-and$null-ne$b[0].items){$b=@($b[0].items)};$queue+=$b;$page++}while($b.Count-eq100)
$root=Split-Path -Parent $PSScriptRoot;$backup=Join-Path $root('backups\dsl-signal-fix-'+(Get-Date -Format yyyyMMdd-HHmmss));New-Item $backup -ItemType Directory -Force|Out-Null;$changed=0;$assigned=0;$targetIds=@(75,191,21096,21100,26229)
foreach($q in($queue|Where-Object{$null-ne$_.id-and([long]$_.id-in$targetIds)}|Sort-Object{[long]$_.id}-Unique)){$id=[long]$q.id;$rb=[Text.Encoding]::UTF8.GetBytes((@{id=$id}|ConvertTo-Json -Compress));$p=Invoke-RestMethod ($site+'/wp-json/gk-unified-api/v1/read-post') -Method Post -Headers $uh -ContentType 'application/json; charset=utf-8' -Body $rb;$title=[string]$p.title;$old=[string]$p.content;$new=$old
 $new=$new.Replace('Bei DSL/VDSL kommt das Signal &#252;ber die Kupferleitung bis zur TAE-Dose beziehungsweise zum APL im Geb&#228;ude.','Bei DSL/VDSL verl&#228;uft das Signal aus dem DSLAM/MSAN &#252;ber das Kupfer-Zugangsnetz zum APL. Vom APL f&#252;hrt die Endleitung zur ersten TAE-Dose und von dort das DSL-Kabel zum Router.')
 $new=$new.Replace('DSL nutzt Kupferleitungen bis zum APL oder zur TAE-Dose. FTTH f&#252;hrt die Glasfaser direkt bis zur Glasfaserabschlussdose (ONT) oder zum Glasfaserrouter.','DSL verl&#228;uft aus dem Zugangsnetz zum APL, danach &#252;ber die Endleitung zur ersten TAE und weiter zum DSL-Router. Bei FTTH endet die Faser in der Wohnung an der Gf-TA; je nach Anschluss folgt ein ONT oder ein Glasfaserrouter.')
 $new=$new.Replace('DSL nutzt Kupferleitungen vom APL &#252;ber Muffen, TAE-Dosen und die Hausverkabelung bis zum Router. Die Verbindung beginnt am APL und verl&#228;uft &#252;ber Verbindungsstellen zum Router.','Der DSL-Signalweg verl&#228;uft aus dem DSLAM/MSAN &#252;ber das Kupfer-Zugangsnetz mit Kabeln und Muffen zum APL. Hinter dem APL folgen Endleitung, erste TAE-Dose, DSL-Kabel und Router. Muffen des Zugangsnetzes liegen vor dem APL, nicht zwischen APL und TAE.')
 $new=[regex]::Replace($new,'(?is)Bei DSL/VDSL kommt das Signal .*?bis zur TAE-Dose beziehungsweise zum APL im Geb&#228;ude\.','Bei DSL/VDSL verl&#228;uft das Signal aus dem DSLAM/MSAN &#252;ber das Kupfer-Zugangsnetz zum APL. Vom APL f&#252;hrt die Endleitung zur ersten TAE-Dose und von dort das DSL-Kabel zum Router.')
 $new=[regex]::Replace($new,'(?is)DSL nutzt Kupferleitungen bis zum APL oder zur TAE-Dose\..*?Glasfaserrouter\.','DSL verl&#228;uft aus dem Zugangsnetz zum APL, danach &#252;ber die Endleitung zur ersten TAE und weiter zum DSL-Router. Bei FTTH endet die Faser in der Wohnung an der Gf-TA; je nach Anschluss folgt ein ONT oder ein Glasfaserrouter.')
 $new=[regex]::Replace($new,'(?is)DSL nutzt Kupferleitungen vom APL .*?Die Verbindung beginnt am APL .*?zum Router\.','Der DSL-Signalweg verl&#228;uft aus dem DSLAM/MSAN &#252;ber das Kupfer-Zugangsnetz mit Kabeln und Muffen zum APL. Hinter dem APL folgen Endleitung, erste TAE-Dose, DSL-Kabel und Router. Muffen des Zugangsnetzes liegen vor dem APL, nicht zwischen APL und TAE.')
 if($id-eq191){$new=[regex]::Replace($new,'(?is)Bei DSL/VDSL kommt das Signal .*?bis zur TAE-Dose beziehungsweise zum APL im Geb(?:&#228;|ä)ude\.','Bei DSL/VDSL verl&#228;uft das Signal aus dem DSLAM/MSAN &#252;ber das Kupfer-Zugangsnetz zum APL. Vom APL f&#252;hrt die Endleitung zur ersten TAE-Dose und von dort das DSL-Kabel zum Router.')}
 if($id-eq21096){$new=[regex]::Replace($new,'(?is)DSL nutzt Kupferleitungen bis zum APL oder zur TAE-Dose\..*?Glasfaserrouter\.','DSL verl&#228;uft aus dem Zugangsnetz zum APL, danach &#252;ber die Endleitung zur ersten TAE und weiter zum DSL-Router. Bei FTTH endet die Faser in der Wohnung an der Gf-TA; je nach Anschluss folgt ein ONT oder ein Glasfaserrouter.')}
 if($id-eq21100){$new=[regex]::Replace($new,'(?is)DSL nutzt Kupferleitungen vom APL .*?Die Verbindung beginnt am APL .*?zum Router\.','Der DSL-Signalweg verl&#228;uft aus dem DSLAM/MSAN &#252;ber das Kupfer-Zugangsnetz mit Kabeln und Muffen zum APL. Hinter dem APL folgen Endleitung, erste TAE-Dose, DSL-Kabel und Router. Muffen des Zugangsnetzes liegen vor dem APL, nicht zwischen APL und TAE.')}
 if($id-eq75){$new=$new-replace'(?is)<img\b[^>]*(?:apl-varianten\.png)[^>]*>',('<img src="'+$aplUrl+'" alt="'+$aplAlt+'" width="1200" height="630">');$new=$new-replace'(?is)<img\b[^>]*(?:apl-signalweg\.png)[^>]*>',('<img src="'+$signalUrl+'" alt="'+$signalAlt+'" width="1200" height="630">')}
 if($title-match'(?i)Signalweg' -and $title-match'(?i)(APL|TAE|DSL)'){$section='<section data-gk-dsl-signalweg="v2"><h2>Der DSL-Signalweg in korrekter Reihenfolge</h2><figure><img src="'+$signalUrl+'" alt="'+$signalAlt+'" width="1200" height="630"><figcaption>Vom aktiven DSL-Port &#252;ber das Kupfer-Zugangsnetz zum APL und von dort &#252;ber Endleitung und erste TAE zum Router.</figcaption></figure><ol><li><strong>DSLAM/MSAN:</strong> stellt das DSL-Signal bereit; bei VDSL meist im Multifunktionsgeh&#228;use, bei ADSL je nach Ausbau auch in der Vermittlungsstelle.</li><li><strong>Kupfer-Zugangsnetz:</strong> Kabel, Kabelverzweiger und Muffen liegen netzseitig vor dem Geb&#228;udeabschluss.</li><li><strong>APL:</strong> passiver Abschlusspunkt des Betreiber-Zugangsnetzes im Geb&#228;ude.</li><li><strong>Endleitung:</strong> verbindet den APL mit der ersten TAE-Dose.</li><li><strong>Erste TAE:</strong> regul&#228;rer Anschluss- und Messpunkt in der Wohnung.</li><li><strong>DSL-Kabel und Router:</strong> erst hinter der TAE folgt das Anschlusskabel zum DSL-Modem beziehungsweise Router.</li></ol></section>';$new=[regex]::Replace($new,'(?is)<section\b[^>]*data-gk-dsl-signalweg=["''][^"'']+["''][^>]*>.*?</section>','');$new=[regex]::Replace($new,'(?is)<h2\b[^>]*>\s*Signalweg\s*</h2>.*?(?=<h2\b|\z)',$section);if($new-notmatch'data-gk-dsl-signalweg="v2"'){$new+=$section}}
 if($new-cne$old){[IO.File]::WriteAllText((Join-Path $backup("post-$id.html")),$old,[Text.UTF8Encoding]::new($false));$payload=[Text.Encoding]::UTF8.GetBytes((@{id=$id;content=$new}|ConvertTo-Json -Compress));$u=Invoke-RestMethod ($site+'/wp-json/gk-unified-api/v1/update-post') -Method Post -Headers $uh -ContentType 'application/json; charset=utf-8' -Body $payload;if($u.updated-ne$true){throw "Inhalt nicht bestaetigt: $id"};$verify=Invoke-RestMethod ($site+'/wp-json/gk-unified-api/v1/read-post') -Method Post -Headers $uh -ContentType 'application/json; charset=utf-8' -Body $rb;if([string]$verify.content-cne$new){throw "Inhalt nicht verifiziert: $id"};$changed++}
 $targetMedia=0;if($title-match'(?i)(APL|TAE|Endleitung).*(Signalweg)|Signalweg.*(APL|TAE|DSL)'){$targetMedia=$signalId}elseif($title-match'(?i)\bAPL\b'){$targetMedia=$aplId};if($targetMedia-gt0){$set=@{post_id=$id;attachment_id=$targetMedia}|ConvertTo-Json -Compress;Invoke-RestMethod ($site+'/wp-json/gk-control/v1/media/set-featured') -Method Post -Headers $ch -ContentType 'application/json; charset=utf-8' -Body ([Text.Encoding]::UTF8.GetBytes($set))|Out-Null;$assigned++}
}
$cache=Invoke-RestMethod ($site+'/wp-json/gk-unified-api/v1/clear-cache') -Method Post -Headers $uh -ContentType 'application/json; charset=utf-8' -Body ([Text.Encoding]::UTF8.GetBytes('{}'));if($cache.cache_cleared-ne$true){throw 'Cache nicht geleert.'};Write-Host("FERTIG: Textkorrekturen=$changed | Bildzuweisungen=$assigned | Signalbild=$signalId | APL-Bild=$aplId | Backup=$backup")
