param([string]$EnvFile='.\.env',[ValidateSet('Preview','Apply')][string]$Mode='Preview',[string]$Confirm='')
$ErrorActionPreference='Stop'
if($Mode-eq'Apply'-and$Confirm-cne'DYNAMISCHE DOPPELBLOECKE BEREINIGEN'){throw'Bestaetigung fehlt.'}
$v=@{};Get-Content $EnvFile|Where-Object{$_-match'^[^#].*='}|ForEach-Object{$p=$_-split'=',2;$v[$p[0].Trim()]=$p[1].Trim()}
foreach($n in @('GK_SITE_URL','GK_CONTROL_TOKEN','GK_UNIFIED_API_TOKEN')){if([string]::IsNullOrWhiteSpace($v[$n])){throw"$n fehlt."}}
$site=$v.GK_SITE_URL.TrimEnd('/');$headers=@{Authorization='Bearer '+$v.GK_CONTROL_TOKEN};$style='<style id="gk-dynamic-dedup">.gkpr-author,.gkpr-affiliate{display:none!important}</style>'
$items=@();foreach($kind in @('posts','pages')){$page=1;do{try{$batch=@(Invoke-RestMethod($site+"/wp-json/wp/v2/$kind`?status=publish&per_page=100&page=$page&_fields=id,title,link")-TimeoutSec 45)}catch{if($_.Exception.Response-and[int]$_.Exception.Response.StatusCode-eq400){$batch=@()}else{throw}};$items+=$batch;$page++}while($batch.Count-eq100)}
$root=Split-Path -Parent $PSScriptRoot;$stamp=Get-Date -Format'yyyyMMdd-HHmmss';$backup=Join-Path $root("backups\dynamic-dedup-$stamp");$report=Join-Path $root'reports';New-Item $report -ItemType Directory -Force|Out-Null;if($Mode-eq'Apply'){New-Item $backup -ItemType Directory -Force|Out-Null};$rows=@()
foreach($item in($items|Sort-Object{[long]$_.id}-Unique)){$id=[long]$item.id;$read=Invoke-RestMethod($site+"/wp-json/gk-control/v1/content/$id")-Headers $headers -TimeoutSec 45;$old=[string]$read.content;if($old-match'id=["'']gk-dynamic-dedup["'']'){continue};$new=$style+$old;$status='READY'
 if($Mode-eq'Apply'){[IO.File]::WriteAllText((Join-Path $backup("post-$id.html")),$old,[Text.UTF8Encoding]::new($false));$payload=[Text.Encoding]::UTF8.GetBytes((@{content=$new}|ConvertTo-Json -Compress));$updated=Invoke-RestMethod ($site+"/wp-json/gk-control/v1/content/$id") -Method Put -Headers $headers -ContentType 'application/json; charset=utf-8' -Body $payload -TimeoutSec 45;$verify=Invoke-RestMethod ($site+"/wp-json/gk-control/v1/content/$id") -Headers $headers -TimeoutSec 45;if(([string]$verify.content)-notmatch'gk-dynamic-dedup'){throw"Style nicht gespeichert: $id"};$status='UPDATED_AND_VERIFIED'}
 $rows+=[pscustomobject]@{id=$id;title=[Net.WebUtility]::HtmlDecode([string]$item.title.rendered);link=[string]$item.link;status=$status};Write-Host("$id $status")}
if($Mode-eq'Apply'-and$rows.Count){$uh=@{Authorization='Bearer '+$v.GK_UNIFIED_API_TOKEN};$cache=Invoke-RestMethod ($site+'/wp-json/gk-unified-api/v1/clear-cache') -Method Post -Headers $uh -ContentType 'application/json; charset=utf-8' -Body ([Text.Encoding]::UTF8.GetBytes('{}'));if($cache.cache_cleared-ne$true){throw'Cache nicht geleert.'}}
$rows|Export-Csv (Join-Path $report("dynamic-dedup-$Mode-$stamp.csv")) -NoTypeInformation -Encoding UTF8;Write-Host("FERTIG: Modus=$Mode | Aktualisiert=$($rows.Count)")
