param([string]$EnvFile='.\.env')
$ErrorActionPreference='Stop'
$v=@{};Get-Content $EnvFile|Where-Object{$_-match'^[^#].*='}|ForEach-Object{$p=$_-split'=',2;$v[$p[0].Trim()]=$p[1].Trim()}
foreach($n in @('GK_SITE_URL','GK_UNIFIED_API_TOKEN')){if([string]::IsNullOrWhiteSpace($v[$n])){throw "$n fehlt."}}
$site=$v.GK_SITE_URL.TrimEnd('/');$uh=@{Authorization='Bearer '+$v.GK_UNIFIED_API_TOKEN};$items=@()
foreach($kind in @('posts','pages')){$page=1;do{$url=$site+"/wp-json/wp/v2/$kind`?status=publish&per_page=100&page=$page&_fields=id,link,title";try{$batch=@(Invoke-RestMethod $url -TimeoutSec 45);if($batch.Count-eq1-and$batch[0]-is[Array]){$batch=@($batch[0])}}catch{if($_.Exception.Response-and[int]$_.Exception.Response.StatusCode-eq400){$batch=@()}else{throw}};$items+=$batch;$page++}while($batch.Count-eq100)}
function Plain([string]$html){return (([Net.WebUtility]::HtmlDecode([regex]::Replace($html,'(?is)<[^>]+>',' ')))-replace'\s+',' ').Trim()}
function Count-Text([string]$value,[string]$needle){return [regex]::Matches($value,[regex]::Escape($needle),[Text.RegularExpressions.RegexOptions]::IgnoreCase).Count}
$rows=@();$details=@()
foreach($x in($items|Sort-Object{[long]$_.id}-Unique)){$id=[long]$x.id;$body=[Text.Encoding]::UTF8.GetBytes((@{id=$id}|ConvertTo-Json -Compress));$p=Invoke-RestMethod ($site+'/wp-json/gk-unified-api/v1/read-post') -Method Post -Headers $uh -ContentType 'application/json; charset=utf-8' -Body $body;$html=[string]$p.content;$text=Plain $html;$issues=New-Object Collections.Generic.List[string]
 $images=@([regex]::Matches($html,'(?is)<img\b[^>]*>'));$objectPath=($text-match'(?i)Objektpfad|Prozesskette zeigt, wo das aktuelle Objekt');if($objectPath-and$images.Count-eq0){$issues.Add('OBJECT_PATH_WITHOUT_IMAGE')}
 $headings=@([regex]::Matches($html,'(?is)<h[1-6]\b[^>]*>(.*?)</h[1-6]>')|ForEach-Object{Plain $_.Groups[1].Value}|Where-Object{$_});$dupeHeadings=@($headings|Group-Object|Where-Object Count-gt1|ForEach-Object{$_.Name});if($dupeHeadings.Count){$issues.Add('DUPLICATE_HEADINGS')}
 $srcs=@([regex]::Matches($html,'(?is)<img\b[^>]*\bsrc=["'']([^"'']+)')|ForEach-Object{$_.Groups[1].Value});if(@($srcs|Group-Object|Where-Object Count-gt1).Count){$issues.Add('DUPLICATE_IMAGES')}
 if((Count-Text $text 'Fachlich eingeordnet')-gt1){$issues.Add('DUPLICATE_AUTHOR_BLOCK')};if((Count-Text $text 'Internet an Ihrer Adresse verfügbar?')-gt1){$issues.Add('DUPLICATE_AFFILIATE_BLOCK')};if((Count-Text $text 'Weiterführende Artikel')-gt1){$issues.Add('DUPLICATE_RELATED_BLOCK')};if((Count-Text $text 'Praxiswissen')-gt1){$issues.Add('DUPLICATE_PRACTICE_BLOCK')}
 if($text-match'(?i)Überblick\s*Praxis\s*FAQ'){ $issues.Add('CONCATENATED_NAVIGATION')};if($text-match'(?i)\{[„"]@context[“"]\s*:'){ $issues.Add('VISIBLE_SCHEMA_JSON')};if($text-match'[ÃÂ]|â€“|â€”|ï¿½'){ $issues.Add('MOJIBAKE')};if($text-match'(?i)Dieser Abschnitt erweitert den Beitrag um zusätzliche Tiefe|Kurz eingeordnet:.*erklärt die wichtigsten Punkte verständlich|Dieser Beitrag ordnet .* praxisnah ein'){ $issues.Add('GENERIC_TEMPLATE_TEXT')}
 if($text-match'(?i)APL|TAE|DSLAM|MFG|KVz|HVt|Endleitung|Kupfer'-and$images.Count-eq0){$issues.Add('COPPER_PAGE_WITHOUT_IMAGE')}
 $row=[pscustomobject]@{id=$id;title=[string]$p.title;link=[string]$x.link;images=$images.Count;headings=$headings.Count;words=@(($text-split'\s+')|Where-Object{$_}).Count;issues=@($issues);duplicate_headings=$dupeHeadings};$rows+=$row
 if($issues.Count){$details+=[pscustomobject]@{id=$id;title=[string]$p.title;link=[string]$x.link;issues=@($issues);content=$html}}
 Write-Host("AUDIT $id | Bilder=$($images.Count) | Probleme=$($issues.Count)")
}
$root=Split-Path -Parent $PSScriptRoot;$out=Join-Path $root 'reports';New-Item $out -ItemType Directory -Force|Out-Null;$rows|ConvertTo-Json -Depth 8|Set-Content (Join-Path $out 'site-editorial-audit.json') -Encoding UTF8;$details|ConvertTo-Json -Depth 8|Set-Content (Join-Path $out 'site-editorial-details.json') -Encoding UTF8
$summary=[ordered]@{pages=$rows.Count;problem_pages=@($rows|Where-Object{$_.issues.Count}).Count;object_without_image=@($rows|Where-Object{$_.issues-contains'OBJECT_PATH_WITHOUT_IMAGE'}).Count;copper_without_image=@($rows|Where-Object{$_.issues-contains'COPPER_PAGE_WITHOUT_IMAGE'}).Count;duplicate_headings=@($rows|Where-Object{$_.issues-contains'DUPLICATE_HEADINGS'}).Count;duplicate_images=@($rows|Where-Object{$_.issues-contains'DUPLICATE_IMAGES'}).Count;duplicate_author=@($rows|Where-Object{$_.issues-contains'DUPLICATE_AUTHOR_BLOCK'}).Count;duplicate_affiliate=@($rows|Where-Object{$_.issues-contains'DUPLICATE_AFFILIATE_BLOCK'}).Count;visible_schema=@($rows|Where-Object{$_.issues-contains'VISIBLE_SCHEMA_JSON'}).Count;template_text=@($rows|Where-Object{$_.issues-contains'GENERIC_TEMPLATE_TEXT'}).Count};$summary|ConvertTo-Json|Set-Content (Join-Path $out 'site-editorial-summary.json') -Encoding UTF8;Write-Host($summary|ConvertTo-Json -Compress)
