param([string]$SiteUrl=$env:GK_SITE_URL)
$ErrorActionPreference='Stop'
$site=$SiteUrl.TrimEnd('/');$out=Join-Path (Split-Path -Parent $PSScriptRoot) 'reports/schema-inventory';New-Item $out -ItemType Directory -Force|Out-Null
function All($route,$fields){$all=New-Object System.Collections.Generic.List[object];$page=1;do{try{$raw=Invoke-RestMethod ($site+$route+($(if($route.Contains('?')){'&'}else{'?'}))+"per_page=100&page=$page&_fields="+[uri]::EscapeDataString($fields))-TimeoutSec 60}catch{if($_.Exception.Response-and[int]$_.Exception.Response.StatusCode-eq400){break};throw};$count=0;foreach($entry in $raw){$all.Add($entry);$count++};$page++}while($count-eq100);foreach($entry in $all){Write-Output $entry}}
$media=@(All '/wp-json/wp/v2/media?orderby=id&order=asc' 'id,date,slug,title,alt_text,mime_type,source_url,media_details')
$items=@(All '/wp-json/wp/v2/posts?status=publish&orderby=id&order=asc' 'id,type,slug,link,title,content,featured_media')+@(All '/wp-json/wp/v2/pages?status=publish&orderby=id&order=asc' 'id,type,slug,link,title,content,featured_media')
$mr=foreach($m in $media){$u=[string]$m.source_url;$f=try{[IO.Path]::GetFileName(([Uri]$u).AbsolutePath)}catch{$u};$t=[string]$m.title.rendered+' '+[string]$m.alt_text+' '+$f;[pscustomobject]@{id=[long](@($m.id)[0]);date=[string]$m.date;filename=$f;url=$u;mime=[string]$m.mime_type;width=[int](@($m.media_details.width)[0]);height=[int](@($m.media_details.height)[0]);title=[Net.WebUtility]::HtmlDecode([string]$m.title.rendered);alt=[string]$m.alt_text;candidate=($t-match'(?i)(schema|diagram|signalweg|objekt|ablauf|netzstruktur|apl|tae|dsl|glasfaser|gf.?ap|gf.?ta|ont|olt|splitter|router|wlan|mesh|splei|muffe|kabel)')}}
$mr|Export-Csv (Join-Path $out 'media.csv') -NoTypeInformation -Encoding UTF8
$usage=foreach($i in $items){$iid=[long]($i.id|Select-Object -First 1);$featured=[long]($i.featured_media|Select-Object -First 1);$html=[string]$i.content.rendered;if($featured-gt0){[pscustomobject]@{post_id=$iid;type=[string]$i.type;title=[Net.WebUtility]::HtmlDecode([string]$i.title.rendered);link=[string]$i.link;kind='featured';media_id=$featured;url='';alt=''}};foreach($m in [regex]::Matches($html,'(?is)<img\b(?<a>[^>]*)>')){$a=$m.Groups['a'].Value;$src=[regex]::Match($a,'(?is)\bsrc=["''](?<v>[^"'']+)').Groups['v'].Value;$alt=[Net.WebUtility]::HtmlDecode([regex]::Match($a,'(?is)\balt=["''](?<v>[^"'']*)').Groups['v'].Value);$mid=[regex]::Match($a,'(?is)\bclass=["''][^"'']*wp-image-(?<id>\d+)').Groups['id'].Value;[pscustomobject]@{post_id=$iid;type=[string]$i.type;title=[Net.WebUtility]::HtmlDecode([string]$i.title.rendered);link=[string]$i.link;kind='content';media_id=$(if($mid){[long]$mid}else{0});url=$src;alt=$alt}}}
$usage|Export-Csv (Join-Path $out 'usage.csv') -NoTypeInformation -Encoding UTF8
$cr=foreach($i in $items){$h=[string]$i.content.rendered;[pscustomobject]@{id=[long]($i.id|Select-Object -First 1);type=[string]$i.type;title=[Net.WebUtility]::HtmlDecode([string]$i.title.rendered);slug=[string]$i.slug;link=[string]$i.link;featured_media=[long]($i.featured_media|Select-Object -First 1);image_count=[regex]::Matches($h,'(?is)<img\b').Count;svg_count=[regex]::Matches($h,'(?i)\.svg').Count}}
$cr|Export-Csv (Join-Path $out 'content.csv') -NoTypeInformation -Encoding UTF8
$s=[pscustomobject]@{media=$media.Count;items=$items.Count;usages=@($usage).Count;candidates=@($mr|Where-Object candidate).Count};$s|ConvertTo-Json|Set-Content (Join-Path $out 'summary.json') -Encoding UTF8
foreach($m in @($mr|Where-Object{$_.candidate-and$_.mime-ne'image/svg+xml'}|Sort-Object id)){Write-Host('MEDIA|'+$m.id+'|'+$m.mime+'|'+$m.width+'x'+$m.height+'|'+$m.filename+'|'+$m.title+'|'+$m.alt)}
foreach($u in @($usage|Where-Object{$_.url-match'(?i)\.svg(?:\?|$)'}|Sort-Object post_id)){Write-Host('SVGUSE|'+$u.post_id+'|'+$u.title+'|'+$u.url+'|'+$u.alt)}
Write-Host('FERTIG: '+($s|ConvertTo-Json -Compress))
